package com.wdy.abc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setKey(java.lang.String key) {
		set("key", key);
		return (M)this;
	}
	
	public java.lang.String getKey() {
		return getStr("key");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setAccount(java.lang.String account) {
		set("account", account);
		return (M)this;
	}
	
	public java.lang.String getAccount() {
		return getStr("account");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setSalt2(java.lang.String salt2) {
		set("salt2", salt2);
		return (M)this;
	}
	
	public java.lang.String getSalt2() {
		return getStr("salt2");
	}

	public M setOrgKey(java.lang.String orgKey) {
		set("org_key", orgKey);
		return (M)this;
	}
	
	public java.lang.String getOrgKey() {
		return getStr("org_key");
	}

	public M setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
		return (M)this;
	}
	
	public java.lang.String getOrgName() {
		return getStr("org_name");
	}

	public M setPicture(java.lang.String picture) {
		set("picture", picture);
		return (M)this;
	}
	
	public java.lang.String getPicture() {
		return getStr("picture");
	}

	public M setPictureObj(java.lang.String pictureObj) {
		set("picture_obj", pictureObj);
		return (M)this;
	}
	
	public java.lang.String getPictureObj() {
		return getStr("picture_obj");
	}

	public M setOpenId(java.lang.String openId) {
		set("open_id", openId);
		return (M)this;
	}
	
	public java.lang.String getOpenId() {
		return getStr("open_id");
	}

	public M setUnionId(java.lang.String unionId) {
		set("union_id", unionId);
		return (M)this;
	}
	
	public java.lang.String getUnionId() {
		return getStr("union_id");
	}

	public M setGender(java.lang.Integer gender) {
		set("gender", gender);
		return (M)this;
	}
	
	public java.lang.Integer getGender() {
		return getInt("gender");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setOnlineStatus(java.lang.Integer onlineStatus) {
		set("online_status", onlineStatus);
		return (M)this;
	}
	
	public java.lang.Integer getOnlineStatus() {
		return getInt("online_status");
	}

	public M setLoginFailTimes(java.lang.Integer loginFailTimes) {
		set("login_fail_times", loginFailTimes);
		return (M)this;
	}
	
	public java.lang.Integer getLoginFailTimes() {
		return getInt("login_fail_times");
	}

	public M setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
		return (M)this;
	}
	
	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	public M setUnlockTime(java.util.Date unlockTime) {
		set("unlock_time", unlockTime);
		return (M)this;
	}
	
	public java.util.Date getUnlockTime() {
		return get("unlock_time");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setUpdator(java.lang.String updator) {
		set("updator", updator);
		return (M)this;
	}
	
	public java.lang.String getUpdator() {
		return getStr("updator");
	}

	public M setVersion(java.util.Date version) {
		set("version", version);
		return (M)this;
	}
	
	public java.util.Date getVersion() {
		return get("version");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setDeleted(java.lang.Boolean deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Boolean getDeleted() {
		return get("deleted");
	}

	public M setManagerLevel(java.lang.String managerLevel) {
		set("manager_level", managerLevel);
		return (M)this;
	}
	
	public java.lang.String getManagerLevel() {
		return getStr("manager_level");
	}

	public M setManagerLevelName(java.lang.String managerLevelName) {
		set("manager_level_name", managerLevelName);
		return (M)this;
	}
	
	public java.lang.String getManagerLevelName() {
		return getStr("manager_level_name");
	}

}
