package com.wdy.generator.mysql.model;

import com.wdy.generator.mysql.model.base.BaseBlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Blog extends BaseBlog<Blog> {
	
}
