package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserRolePermission<M extends BaseUserRolePermission<M>> extends Model<M> implements IBean {

	/**
	 * uuid不能为null
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * uuid不能为null
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 用户id不能为null
	 */
	public void setUserID(java.lang.String userID) {
		set("userID", userID);
	}
	
	/**
	 * 用户id不能为null
	 */
	public java.lang.String getUserID() {
		return getStr("userID");
	}

	/**
	 * 角色id不能为null
	 */
	public void setRoleID(java.lang.String roleID) {
		set("roleID", roleID);
	}
	
	/**
	 * 角色id不能为null
	 */
	public java.lang.String getRoleID() {
		return getStr("roleID");
	}

	/**
	 * 权限码不能为null,第一次创建权限码为角色默认权限码
	 */
	public void setPermission(java.lang.String permission) {
		set("permission", permission);
	}
	
	/**
	 * 权限码不能为null,第一次创建权限码为角色默认权限码
	 */
	public java.lang.String getPermission() {
		return getStr("permission");
	}

	/**
	 * 组织配置数组,例如:[{'orgId':'xxx','isReadOnly':0}]
	 */
	public void setOrgArray(java.lang.Object orgArray) {
		set("orgArray", orgArray);
	}
	
	/**
	 * 组织配置数组,例如:[{'orgId':'xxx','isReadOnly':0}]
	 */
	public java.lang.Object getOrgArray() {
		return get("orgArray");
	}

	/**
	 * 创建时间不能为null
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间不能为null
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 更新时间不能为null,默认为createTime
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间不能为null,默认为createTime
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	/**
	 * 角色名称不能为null
	 */
	public void setRoleName(java.lang.String roleName) {
		set("roleName", roleName);
	}
	
	/**
	 * 角色名称不能为null
	 */
	public java.lang.String getRoleName() {
		return getStr("roleName");
	}

	/**
	 * 角色是否内建0 非内建 1内建
	 */
	public void setIsBuilt(java.lang.Integer isBuilt) {
		set("isBuilt", isBuilt);
	}
	
	/**
	 * 角色是否内建0 非内建 1内建
	 */
	public java.lang.Integer getIsBuilt() {
		return getInt("isBuilt");
	}

}
