package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJobInfo<M extends BaseJobInfo<M>> extends Model<M> implements IBean {

	/**
	 * 主键uuid非空
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 主键uuid非空
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 组织ID非空,外键
	 */
	public void setOrgId(java.lang.String orgId) {
		set("orgId", orgId);
	}
	
	/**
	 * 组织ID非空,外键
	 */
	public java.lang.String getOrgId() {
		return getStr("orgId");
	}

	/**
	 * 岗位名称 非NULL
	 */
	public void setJobName(java.lang.String jobName) {
		set("jobName", jobName);
	}
	
	/**
	 * 岗位名称 非NULL
	 */
	public java.lang.String getJobName() {
		return getStr("jobName");
	}

	/**
	 * 岗位类型1 正职 2副职 3其他 非NULL
	 */
	public void setJobType(java.lang.Integer jobType) {
		set("jobType", jobType);
	}
	
	/**
	 * 岗位类型1 正职 2副职 3其他 非NULL
	 */
	public java.lang.Integer getJobType() {
		return getInt("jobType");
	}

	/**
	 * 岗位级别类型,参照字典表ZB03 非NULL
	 */
	public void setJobLevelCode(java.lang.String jobLevelCode) {
		set("jobLevelCode", jobLevelCode);
	}
	
	/**
	 * 岗位级别类型,参照字典表ZB03 非NULL
	 */
	public java.lang.String getJobLevelCode() {
		return getStr("jobLevelCode");
	}

	/**
	 * 岗位级别类型名称 非NULL
	 */
	public void setJobLevelName(java.lang.String jobLevelName) {
		set("jobLevelName", jobLevelName);
	}
	
	/**
	 * 岗位级别类型名称 非NULL
	 */
	public java.lang.String getJobLevelName() {
		return getStr("jobLevelName");
	}

	/**
	 * 岗位领导类型 1 领导职务 2非领导职务 3其他 非NULL
	 */
	public void setLeadJobType(java.lang.Integer leadJobType) {
		set("leadJobType", leadJobType);
	}
	
	/**
	 * 岗位领导类型 1 领导职务 2非领导职务 3其他 非NULL
	 */
	public java.lang.Integer getLeadJobType() {
		return getInt("leadJobType");
	}

	/**
	 * 排序ID不能为null 默认为0
	 */
	public void setSortId(java.lang.Integer sortId) {
		set("sortId", sortId);
	}
	
	/**
	 * 排序ID不能为null 默认为0
	 */
	public java.lang.Integer getSortId() {
		return getInt("sortId");
	}

	/**
	 * 0 非占有 1占有 不能为null 默认为0
	 */
	public void setIsOccupy(java.lang.Integer isOccupy) {
		set("isOccupy", isOccupy);
	}
	
	/**
	 * 0 非占有 1占有 不能为null 默认为0
	 */
	public java.lang.Integer getIsOccupy() {
		return getInt("isOccupy");
	}

	/**
	 * 创建者ID 不能为null
	 */
	public void setCreateUser(java.lang.String createUser) {
		set("createUser", createUser);
	}
	
	/**
	 * 创建者ID 不能为null
	 */
	public java.lang.String getCreateUser() {
		return getStr("createUser");
	}

	/**
	 * 0 未删除 1删除 不能为null 默认为0
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("isDelete", isDelete);
	}
	
	/**
	 * 0 未删除 1删除 不能为null 默认为0
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("isDelete");
	}

	/**
	 * 描述
	 */
	public void setDes(java.lang.String des) {
		set("des", des);
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getDes() {
		return getStr("des");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
