package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYoungFouMust<M extends BaseYoungFouMust<M>> extends Model<M> implements IBean {

	/**
	 * 唯一标示
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 唯一标示
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * a01人员唯一标示
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * a01人员唯一标示
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 是否核查干部人事档案 1是 0否
	 */
	public void setIsCadreCheck(java.lang.Integer isCadreCheck) {
		set("isCadreCheck", isCadreCheck);
	}
	
	/**
	 * 是否核查干部人事档案 1是 0否
	 */
	public java.lang.Integer getIsCadreCheck() {
		return getInt("isCadreCheck");
	}

	/**
	 * 干部人事档案核查结果代码
	 */
	public void setCadreCheckResult(java.lang.String cadreCheckResult) {
		set("cadreCheckResult", cadreCheckResult);
	}
	
	/**
	 * 干部人事档案核查结果代码
	 */
	public java.lang.String getCadreCheckResult() {
		return getStr("cadreCheckResult");
	}

	/**
	 * 干部人事档案核查附加文件
	 */
	public void setCadreCheckFileUrl(java.lang.String cadreCheckFileUrl) {
		set("cadreCheckFileUrl", cadreCheckFileUrl);
	}
	
	/**
	 * 干部人事档案核查附加文件
	 */
	public java.lang.String getCadreCheckFileUrl() {
		return getStr("cadreCheckFileUrl");
	}

	/**
	 * 是否个人有关事项报告 1是 0否
	 */
	public void setIsPersonalCheck(java.lang.Integer isPersonalCheck) {
		set("isPersonalCheck", isPersonalCheck);
	}
	
	/**
	 * 是否个人有关事项报告 1是 0否
	 */
	public java.lang.Integer getIsPersonalCheck() {
		return getInt("isPersonalCheck");
	}

	/**
	 * 个人有关事项报告结果代码
	 */
	public void setPersonalCheckResult(java.lang.String personalCheckResult) {
		set("personalCheckResult", personalCheckResult);
	}
	
	/**
	 * 个人有关事项报告结果代码
	 */
	public java.lang.String getPersonalCheckResult() {
		return getStr("personalCheckResult");
	}

	/**
	 * 个人有关事项报告附加文件
	 */
	public void setPersonalCheckFileUrl(java.lang.String personalCheckFileUrl) {
		set("personalCheckFileUrl", personalCheckFileUrl);
	}
	
	/**
	 * 个人有关事项报告附加文件
	 */
	public java.lang.String getPersonalCheckFileUrl() {
		return getStr("personalCheckFileUrl");
	}

	/**
	 * 是否核查纪检监察机关意见 1是 0否
	 */
	public void setIsSuperviseCheck(java.lang.Integer isSuperviseCheck) {
		set("isSuperviseCheck", isSuperviseCheck);
	}
	
	/**
	 * 是否核查纪检监察机关意见 1是 0否
	 */
	public java.lang.Integer getIsSuperviseCheck() {
		return getInt("isSuperviseCheck");
	}

	/**
	 * 纪检监察机关意见核查结果代码
	 */
	public void setSuperviseCheckResult(java.lang.String superviseCheckResult) {
		set("superviseCheckResult", superviseCheckResult);
	}
	
	/**
	 * 纪检监察机关意见核查结果代码
	 */
	public java.lang.String getSuperviseCheckResult() {
		return getStr("superviseCheckResult");
	}

	/**
	 * 纪检监察机关意见核查结果附加文件
	 */
	public void setSuperviseCheckFileUrl(java.lang.String superviseCheckFileUrl) {
		set("superviseCheckFileUrl", superviseCheckFileUrl);
	}
	
	/**
	 * 纪检监察机关意见核查结果附加文件
	 */
	public java.lang.String getSuperviseCheckFileUrl() {
		return getStr("superviseCheckFileUrl");
	}

	/**
	 * 是否有可查性的信访举报核查 1是 0否
	 */
	public void setIsPetitionCheck(java.lang.Integer isPetitionCheck) {
		set("isPetitionCheck", isPetitionCheck);
	}
	
	/**
	 * 是否有可查性的信访举报核查 1是 0否
	 */
	public java.lang.Integer getIsPetitionCheck() {
		return getInt("isPetitionCheck");
	}

	/**
	 * 是否有可查性的信访举报核查结果意见代码
	 */
	public void setPetitionCheckResult(java.lang.String petitionCheckResult) {
		set("petitionCheckResult", petitionCheckResult);
	}
	
	/**
	 * 是否有可查性的信访举报核查结果意见代码
	 */
	public java.lang.String getPetitionCheckResult() {
		return getStr("petitionCheckResult");
	}

	/**
	 * 是否有可查性的信访举报核查结果附加文件
	 */
	public void setPetitionCheckFileUrl(java.lang.String petitionCheckFileUrl) {
		set("petitionCheckFileUrl", petitionCheckFileUrl);
	}
	
	/**
	 * 是否有可查性的信访举报核查结果附加文件
	 */
	public java.lang.String getPetitionCheckFileUrl() {
		return getStr("petitionCheckFileUrl");
	}

	/**
	 * 未检查原因
	 */
	public void setNoCheckReason(java.lang.String noCheckReason) {
		set("noCheckReason", noCheckReason);
	}
	
	/**
	 * 未检查原因
	 */
	public java.lang.String getNoCheckReason() {
		return getStr("noCheckReason");
	}

	/**
	 * 房产几套
	 */
	public void setHouse(java.lang.Long house) {
		set("house", house);
	}
	
	/**
	 * 房产几套
	 */
	public java.lang.Long getHouse() {
		return getLong("house");
	}

	/**
	 * 股票基金等理财产品代码
	 */
	public void setShares(java.lang.String shares) {
		set("shares", shares);
	}
	
	/**
	 * 股票基金等理财产品代码
	 */
	public java.lang.String getShares() {
		return getStr("shares");
	}

}
