package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA15<M extends BaseA15<M>> extends Model<M> implements IBean {

	/**
	 * 人员统一标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员统一标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 主键
	 */
	public void setA1500(java.lang.String A1500) {
		set("A1500", A1500);
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getA1500() {
		return getStr("A1500");
	}

	/**
	 * 考核结论   等
	 */
	public void setA1517(java.lang.String A1517) {
		set("A1517", A1517);
	}
	
	/**
	 * 考核结论   等
	 */
	public java.lang.String getA1517() {
		return getStr("A1517");
	}

	/**
	 * 考核年度   等
	 */
	public void setA1521(java.util.Date A1521) {
		set("A1521", A1521);
	}
	
	/**
	 * 考核年度   等
	 */
	public java.util.Date getA1521() {
		return get("A1521");
	}

	/**
	 * null   少
	 */
	public void setA1527(java.lang.String A1527) {
		set("A1527", A1527);
	}
	
	/**
	 * null   少
	 */
	public java.lang.String getA1527() {
		return getStr("A1527");
	}

	/**
	 * 标识   少
	 */
	public void setUPDATED(java.lang.String UPDATED) {
		set("UPDATED", UPDATED);
	}
	
	/**
	 * 标识   少
	 */
	public java.lang.String getUPDATED() {
		return getStr("UPDATED");
	}

	/**
	 * 1:是3年连续优秀 2:不是3年连续优秀
	 */
	public void setA1599(java.lang.Integer A1599) {
		set("A1599", A1599);
	}
	
	/**
	 * 1:是3年连续优秀 2:不是3年连续优秀
	 */
	public java.lang.Integer getA1599() {
		return getInt("A1599");
	}

	/**
	 * 上传word名称
	 */
	public void setA15Z101(java.lang.String A15Z101) {
		set("A15Z101", A15Z101);
	}
	
	/**
	 * 上传word名称
	 */
	public java.lang.String getA15Z101() {
		return getStr("A15Z101");
	}

	/**
	 * 上传wordurl
	 */
	public void setA15Z102(java.lang.String A15Z102) {
		set("A15Z102", A15Z102);
	}
	
	/**
	 * 上传wordurl
	 */
	public java.lang.String getA15Z102() {
		return getStr("A15Z102");
	}

	/**
	 * 上传wordurl2
	 */
	public void setA15Z103(java.lang.String A15Z103) {
		set("A15Z103", A15Z103);
	}
	
	/**
	 * 上传wordurl2
	 */
	public java.lang.String getA15Z103() {
		return getStr("A15Z103");
	}

}
