package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseB01Temp<M extends BaseB01Temp<M>> extends Model<M> implements IBean {

    public M setImpId(String impId) {
        set("impId", impId);
        return (M) this;
    }

    public String getImpId() {
        return getStr("impId");
    }

    /**
     * 机构名称
     */
    public M setB0101(String B0101) {
        set("B0101", B0101);
        return (M) this;
    }

    /**
     * 机构名称
     */
    public String getB0101() {
        return getStr("B0101");
    }

    /**
     * 机构简称
     */
    public M setB0104(String B0104) {
        set("B0104", B0104);
        return (M) this;
    }

    /**
     * 机构简称
     */
    public String getB0104() {
        return getStr("B0104");
    }

    /**
     * 机构简拼
     */
    public M setB0107(String B0107) {
        set("B0107", B0107);
        return (M) this;
    }

    /**
     * 机构简拼
     */
    public String getB0107() {
        return getStr("B0107");
    }

    /**
     * 机构主键
     */
    public M setB0111(String B0111) {
        set("B0111", B0111);
        return (M) this;
    }

    /**
     * 机构主键
     */
    public String getB0111() {
        return getStr("B0111");
    }

    /**
     * 法人单位编码(机构分组编码)   少
     */
    public M setB0114(String B0114) {
        set("B0114", B0114);
        return (M) this;
    }

    /**
     * 法人单位编码(机构分组编码)   少
     */
    public String getB0114() {
        return getStr("B0114");
    }

    /**
     * 机构所在政区 ZB01
     */
    public M setB0117(String B0117) {
        set("B0117", B0117);
        return (M) this;
    }

    /**
     * 机构所在政区 ZB01
     */
    public String getB0117() {
        return getStr("B0117");
    }

    /**
     * 上级单位id
     */
    public M setB0121(String B0121) {
        set("B0121", B0121);
        return (M) this;
    }

    /**
     * 上级单位id
     */
    public String getB0121() {
        return getStr("B0121");
    }

    /**
     * 单位隶属关系 ZB87
     */
    public M setB0124(String B0124) {
        set("B0124", B0124);
        return (M) this;
    }

    /**
     * 单位隶属关系 ZB87
     */
    public String getB0124() {
        return getStr("B0124");
    }

    /**
     * 机构级别 ZB03   等
     */
    public M setB0127(String B0127) {
        set("B0127", B0127);
        return (M) this;
    }

    /**
     * 机构级别 ZB03   等
     */
    public String getB0127() {
        return getStr("B0127");
    }

    /**
     * 机构性质类别 ZB04
     */
    public M setB0131(String B0131) {
        set("B0131", B0131);
        return (M) this;
    }

    /**
     * 机构性质类别 ZB04
     */
    public String getB0131() {
        return getStr("B0131");
    }

    /**
     * 统计单位编码 （未用）   少
     */
    public M setB0140(String B0140) {
        set("B0140", B0140);
        return (M) this;
    }

    /**
     * 统计单位编码 （未用）   少
     */
    public String getB0140() {
        return getStr("B0140");
    }

    /**
     * 统计单位上级编码 （未用）   少
     */
    public M setB0141(String B0141) {
        set("B0141", B0141);
        return (M) this;
    }

    /**
     * 统计单位上级编码 （未用）   少
     */
    public String getB0141() {
        return getStr("B0141");
    }

    /**
     * 单位排序 （未用）   少
     */
    public M setB0142(Integer B0142) {
        set("B0142", B0142);
        return (M) this;
    }

    /**
     * 单位排序 （未用）   少
     */
    public Integer getB0142() {
        return getInt("B0142");
    }

    /**
     * 统计单位选择 （未用）   少
     */
    public M setB0143(String B0143) {
        set("B0143", B0143);
        return (M) this;
    }

    /**
     * 统计单位选择 （未用）   少
     */
    public String getB0143() {
        return getStr("B0143");
    }

    /**
     * 内设领导职数
     */
    public M setB0150(Integer B0150) {
        set("B0150", B0150);
        return (M) this;
    }

    /**
     * 内设领导职数
     */
    public Integer getB0150() {
        return getInt("B0150");
    }

    public M setB0180(String B0180) {
        set("B0180", B0180);
        return (M) this;
    }

    public String getB0180() {
        return getStr("B0180");
    }

    /**
     * 正职领导职数
     */
    public M setB0183(Integer B0183) {
        set("B0183", B0183);
        return (M) this;
    }

    /**
     * 正职领导职数
     */
    public Integer getB0183() {
        return getInt("B0183");
    }

    /**
     * 副职领导职数
     */
    public M setB0185(Integer B0185) {
        set("B0185", B0185);
        return (M) this;
    }

    /**
     * 副职领导职数
     */
    public Integer getB0185() {
        return getInt("B0185");
    }

    /**
     * 同级正职非领导职数(无效)   少
     */
    public M setB0188(Integer B0188) {
        set("B0188", B0188);
        return (M) this;
    }

    /**
     * 同级正职非领导职数(无效)   少
     */
    public Integer getB0188() {
        return getInt("B0188");
    }

    /**
     * 同级副职非领导职数(无效)   少
     */
    public M setB0189(Integer B0189) {
        set("B0189", B0189);
        return (M) this;
    }

    /**
     * 同级副职非领导职数(无效)   少
     */
    public Integer getB0189() {
        return getInt("B0189");
    }

    /**
     * 内设机构正职领导职数(无效)   少
     */
    public M setB0190(Integer B0190) {
        set("B0190", B0190);
        return (M) this;
    }

    /**
     * 内设机构正职领导职数(无效)   少
     */
    public Integer getB0190() {
        return getInt("B0190");
    }

    /**
     * 法人单位(组织机构) （未用）   少
     */
    public M setB0191(String B0191) {
        set("B0191", B0191);
        return (M) this;
    }

    /**
     * 法人单位(组织机构) （未用）   少
     */
    public String getB0191() {
        return getStr("B0191");
    }

    /**
     * 内设副职领导职数(无效)   少
     */
    public M setB0191A(Integer B0191A) {
        set("B0191A", B0191A);
        return (M) this;
    }

    /**
     * 内设副职领导职数(无效)   少
     */
    public Integer getB0191A() {
        return getInt("B0191A");
    }

    /**
     * 内设机构正职非领导职数(无效)   少
     */
    public M setB0192(Integer B0192) {
        set("B0192", B0192);
        return (M) this;
    }

    /**
     * 内设机构正职非领导职数(无效)   少
     */
    public Integer getB0192() {
        return getInt("B0192");
    }

    /**
     * 内设机构副职非领导职数(无效)   少
     */
    public M setB0193(Integer B0193) {
        set("B0193", B0193);
        return (M) this;
    }

    /**
     * 内设机构副职非领导职数(无效)   少
     */
    public Integer getB0193() {
        return getInt("B0193");
    }

    /**
     * 机构类型 1法人单位 2内设机构 3机构分组 0领导机构
     */
    public M setB0194(String B0194) {
        set("B0194", B0194);
        return (M) this;
    }

    /**
     * 机构类型 1法人单位 2内设机构 3机构分组 0领导机构
     */
    public String getB0194() {
        return getStr("B0194");
    }

    /**
     * 导出标志 （未用）   少
     */
    public M setB01TRANS(Integer B01TRANS) {
        set("B01TRANS", B01TRANS);
        return (M) this;
    }

    /**
     * 导出标志 （未用）   少
     */
    public Integer getB01TRANS() {
        return getInt("B01TRANS");
    }

    /**
     * 同步标志 （未用）   少
     */
    public M setB01IP(String B01IP) {
        set("B01IP", B01IP);
        return (M) this;
    }

    /**
     * 同步标志 （未用）   少
     */
    public String getB01IP() {
        return getStr("B01IP");
    }

    /**
     * 行政编制数   等
     */
    public M setB0227(Integer B0227) {
        set("B0227", B0227);
        return (M) this;
    }

    /**
     * 行政编制数   等
     */
    public Integer getB0227() {
        return getInt("B0227");
    }

    /**
     * 事业编制数(参公)
     */
    public M setB0232(Integer B0232) {
        set("B0232", B0232);
        return (M) this;
    }

    /**
     * 事业编制数(参公)
     */
    public Integer getB0232() {
        return getInt("B0232");
    }

    /**
     * 事业编制数(其他)
     */
    public M setB0233(Integer B0233) {
        set("B0233", B0233);
        return (M) this;
    }

    /**
     * 事业编制数(其他)
     */
    public Integer getB0233() {
        return getInt("B0233");
    }

    /**
     * 排序字段   少
     */
    public M setSORTID(Integer SORTID) {
        set("SORTID", SORTID);
        return (M) this;
    }

    /**
     * 排序字段   少
     */
    public Integer getSORTID() {
        return getInt("SORTID");
    }

    /**
     * （未用）1   少
     */
    public M setUSED(String USED) {
        set("USED", USED);
        return (M) this;
    }

    /**
     * （未用）1   少
     */
    public String getUSED() {
        return getStr("USED");
    }

    /**
     * 校验标识：0-未校验或校验未通过，1-校验通过   少
     */
    public M setUPDATED(String UPDATED) {
        set("UPDATED", UPDATED);
        return (M) this;
    }

    /**
     * 校验标识：0-未校验或校验未通过，1-校验通过   少
     */
    public String getUPDATED() {
        return getStr("UPDATED");
    }

    /**
     * 创建人，为空表示非本系统创建？   少
     */
    public M setCreateUser(String createUser) {
        set("CREATE_USER", createUser);
        return (M) this;
    }

    /**
     * 创建人，为空表示非本系统创建？   少
     */
    public String getCreateUser() {
        return getStr("CREATE_USER");
    }

    /**
     * 创建时间？   少
     */
    public M setCreateDate(Date createDate) {
        set("CREATE_DATE", createDate);
        return (M) this;
    }

    /**
     * 创建时间？   少
     */
    public Date getCreateDate() {
        return get("CREATE_DATE");
    }

    /**
     * 修改人？   少
     */
    public M setUpdateUser(String updateUser) {
        set("UPDATE_USER", updateUser);
        return (M) this;
    }

    /**
     * 修改人？   少
     */
    public String getUpdateUser() {
        return getStr("UPDATE_USER");
    }

    /**
     * 修改时间？   少
     */
    public M setUpdateDate(Date updateDate) {
        set("UPDATE_DATE", updateDate);
        return (M) this;
    }

    /**
     * 修改时间？   少
     */
    public Date getUpdateDate() {
        return get("UPDATE_DATE");
    }

    /**
     * 状态 （未用）？   少
     */
    public M setSTATUS(String STATUS) {
        set("STATUS", STATUS);
        return (M) this;
    }

    /**
     * 状态 （未用）？   少
     */
    public String getSTATUS() {
        return getStr("STATUS");
    }

    /**
     * 参照公务员法管理审批时间
     */
    public M setB0238(Date B0238) {
        set("B0238", B0238);
        return (M) this;
    }

    /**
     * 参照公务员法管理审批时间
     */
    public Date getB0238() {
        return getDate("B0238");
    }

    /**
     * 参照公务员法管理审批文号
     */
    public M setB0239(String B0239) {
        set("B0239", B0239);
        return (M) this;
    }

    /**
     * 参照公务员法管理审批文号
     */
    public String getB0239() {
        return getStr("B0239");
    }

    /**
     * 其他编制数
     */
    public M setB0234(Integer B0234) {
        set("B0234", B0234);
        return (M) this;
    }

    /**
     * 其他编制数
     */
    public Integer getB0234() {
        return getInt("B0234");
    }

    /**
     * 政法专项编制数-已经取消
     */
    public M setB0235(Integer B0235) {
        set("B0235", B0235);
        return (M) this;
    }

    /**
     * 政法专项编制数-已经取消
     */
    public Integer getB0235() {
        return getInt("B0235");
    }

    /**
     * 工勤编制数
     */
    public M setB0236(Integer B0236) {
        set("B0236", B0236);
        return (M) this;
    }

    /**
     * 工勤编制数
     */
    public Integer getB0236() {
        return getInt("B0236");
    }

    public M setId(String id) {
        set("id", id);
        return (M) this;
    }

    public String getId() {
        return getStr("id");
    }

    /**
     * 1 删除 0 未删除
     */
    public M setIsDelete(Integer isDelete) {
        set("isDelete", isDelete);
        return (M) this;
    }

    /**
     * 1 删除 0 未删除
     */
    public Integer getIsDelete() {
        return getInt("isDelete");
    }

    /**
     * 统一社会性用代码
     */
    public M setB0194A(String B0194A) {
        set("B0194A", B0194A);
        return (M) this;
    }

    /**
     * 统一社会性用代码
     */
    public String getB0194A() {
        return getStr("B0194A");
    }


    /**
     * 参照公务员法管理审批时间
     */
    public M setB0164(Date B0164) {
        set("B0164", B0164);
        return (M) this;
    }

    /**
     * 参照公务员法管理审批时间
     */
    public Date getB0164() {
        return getDate("B0164");
    }

    /**
     * 参照公务员法管理审批文号
     */
    public M setB0167(String B0167) {
        set("B0167", B0167);
        return (M) this;
    }

    /**
     * 参照公务员法管理审批文号
     */
    public String getB0167() {
        return getStr("B0167");
    }


    /**
     * 参照公务员法管理审批时间
     */
    public M setB0268(Date B0268) {
        set("B0268", B0268);
        return (M) this;
    }

    /**
     * 参照公务员法管理审批时间
     */
    public Date getB0268() {
        return getDate("B0268");
    }

    /**
     * 参照公务员法管理审批文号
     */
    public M setB0269(String B0269) {
        set("B0269", B0269);
        return (M) this;
    }

    /**
     * 参照公务员法管理审批文号
     */
    public String getB0269() {
        return getStr("B0269");
    }
}
