package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA62<M extends BaseA62<M>> extends Model<M> implements IBean {

	/**
	 * 人员统一标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员统一标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 遴选方式   等
	 */
	public void setA6203(java.lang.String A6203) {
		set("A6203", A6203);
	}
	
	/**
	 * 遴选方式   等
	 */
	public java.lang.String getA6203() {
		return getStr("A6203");
	}

	/**
	 * 原单位层级   等
	 */
	public void setA6204(java.lang.String A6204) {
		set("A6204", A6204);
	}
	
	/**
	 * 原单位层级   等
	 */
	public java.lang.String getA6204() {
		return getStr("A6204");
	}

	/**
	 * 遴选时间   等
	 */
	public void setA6205(java.lang.String A6205) {
		set("A6205", A6205);
	}
	
	/**
	 * 遴选时间   等
	 */
	public java.lang.String getA6205() {
		return getStr("A6205");
	}

	/**
	 * 公开遴选   等
	 */
	public void setA2950(java.lang.String A2950) {
		set("A2950", A2950);
	}
	
	/**
	 * 公开遴选   等
	 */
	public java.lang.String getA2950() {
		return getStr("A2950");
	}

	/**
	 * 遴选类别   等
	 */
	public void setA6202(java.lang.String A6202) {
		set("A6202", A6202);
	}
	
	/**
	 * 遴选类别   等
	 */
	public java.lang.String getA6202() {
		return getStr("A6202");
	}

}
