package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA08<M extends BaseA08<M>> extends Model<M> implements IBean {

	/**
	 * 人员统一标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员统一标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 学历学位ID
	 */
	public void setA0800(java.lang.String A0800) {
		set("A0800", A0800);
	}
	
	/**
	 * 学历学位ID
	 */
	public java.lang.String getA0800() {
		return getStr("A0800");
	}

	/**
	 * 学历名称   等
	 */
	public void setA0801A(java.lang.String A0801A) {
		set("A0801A", A0801A);
	}
	
	/**
	 * 学历名称   等
	 */
	public java.lang.String getA0801A() {
		return getStr("A0801A");
	}

	/**
	 * 学历代码   等
	 */
	public void setA0801B(java.lang.String A0801B) {
		set("A0801B", A0801B);
	}
	
	/**
	 * 学历代码   等
	 */
	public java.lang.String getA0801B() {
		return getStr("A0801B");
	}

	/**
	 * 学位名称   等
	 */
	public void setA0901A(java.lang.String A0901A) {
		set("A0901A", A0901A);
	}
	
	/**
	 * 学位名称   等
	 */
	public java.lang.String getA0901A() {
		return getStr("A0901A");
	}

	/**
	 * 学位代码   等
	 */
	public void setA0901B(java.lang.String A0901B) {
		set("A0901B", A0901B);
	}
	
	/**
	 * 学位代码   等
	 */
	public java.lang.String getA0901B() {
		return getStr("A0901B");
	}

	/**
	 * 入学日期   等
	 */
	public void setA0804(java.util.Date A0804) {
		set("A0804", A0804);
	}
	
	/**
	 * 入学日期   等
	 */
	public java.util.Date getA0804() {
		return get("A0804");
	}

	/**
	 * 毕（肄）业日期   等
	 */
	public void setA0807(java.util.Date A0807) {
		set("A0807", A0807);
	}
	
	/**
	 * 毕（肄）业日期   等
	 */
	public java.util.Date getA0807() {
		return get("A0807");
	}

	/**
	 * 学位授予日期   等
	 */
	public void setA0904(java.util.Date A0904) {
		set("A0904", A0904);
	}
	
	/**
	 * 学位授予日期   等
	 */
	public java.util.Date getA0904() {
		return get("A0904");
	}

	/**
	 * 学校（单位）名称   等
	 */
	public void setA0814(java.lang.String A0814) {
		set("A0814", A0814);
	}
	
	/**
	 * 学校（单位）名称   等
	 */
	public java.lang.String getA0814() {
		return getStr("A0814");
	}

	/**
	 * 所学专业名称   等
	 */
	public void setA0824(java.lang.String A0824) {
		set("A0824", A0824);
	}
	
	/**
	 * 所学专业名称   等
	 */
	public java.lang.String getA0824() {
		return getStr("A0824");
	}

	/**
	 * 所学专业类别   等
	 */
	public void setA0827(java.lang.String A0827) {
		set("A0827", A0827);
	}
	
	/**
	 * 所学专业类别   等
	 */
	public java.lang.String getA0827() {
		return getStr("A0827");
	}

	/**
	 * 教育类别   等（1全日制，0在职）
	 */
	public void setA0837(java.lang.String A0837) {
		set("A0837", A0837);
	}
	
	/**
	 * 教育类别   等（1全日制，0在职）
	 */
	public java.lang.String getA0837() {
		return getStr("A0837");
	}

	/**
	 * 学制年限   等
	 */
	public void setA0811(java.lang.String A0811) {
		set("A0811", A0811);
	}
	
	/**
	 * 学制年限   等
	 */
	public java.lang.String getA0811() {
		return getStr("A0811");
	}

	/**
	 * 输出标识   等（1是，0否）
	 */
	public void setA0898(java.lang.String A0898) {
		set("A0898", A0898);
	}
	
	/**
	 * 输出标识   等（1是，0否）
	 */
	public java.lang.String getA0898() {
		return getStr("A0898");
	}

	/**
	 * 最高全日制学历
	 */
	public void setA0831(java.lang.String A0831) {
		set("A0831", A0831);
	}
	
	/**
	 * 最高全日制学历
	 */
	public java.lang.String getA0831() {
		return getStr("A0831");
	}

	/**
	 * 最高全日制学位
	 */
	public void setA0832(java.lang.String A0832) {
		set("A0832", A0832);
	}
	
	/**
	 * 最高全日制学位
	 */
	public java.lang.String getA0832() {
		return getStr("A0832");
	}

	/**
	 * 最高学历
	 */
	public void setA0834(java.lang.String A0834) {
		set("A0834", A0834);
	}
	
	/**
	 * 最高学历
	 */
	public java.lang.String getA0834() {
		return getStr("A0834");
	}

	/**
	 * 最高学位（自动生成）
	 */
	public void setA0835(java.lang.String A0835) {
		set("A0835", A0835);
	}
	
	/**
	 * 最高学位（自动生成）
	 */
	public java.lang.String getA0835() {
		return getStr("A0835");
	}

	/**
	 * 最高在职学历
	 */
	public void setA0838(java.lang.String A0838) {
		set("A0838", A0838);
	}
	
	/**
	 * 最高在职学历
	 */
	public java.lang.String getA0838() {
		return getStr("A0838");
	}

	/**
	 * 最高在职学位
	 */
	public void setA0839(java.lang.String A0839) {
		set("A0839", A0839);
	}
	
	/**
	 * 最高在职学位
	 */
	public java.lang.String getA0839() {
		return getStr("A0839");
	}

	/**
	 * 任免表输出.最高学历的标识。true—是；false—否。
	 */
	public void setA0899(java.lang.String A0899) {
		set("A0899", A0899);
	}
	
	/**
	 * 任免表输出.最高学历的标识。true—是；false—否。
	 */
	public java.lang.String getA0899() {
		return getStr("A0899");
	}

	/**
	 * 标识
	 */
	public void setUPDATED(java.lang.String UPDATED) {
		set("UPDATED", UPDATED);
	}
	
	/**
	 * 标识
	 */
	public java.lang.String getUPDATED() {
		return getStr("UPDATED");
	}

	/**
	 * 排序字段
	 */
	public void setSORTID(java.lang.Integer SORTID) {
		set("SORTID", SORTID);
	}
	
	/**
	 * 排序字段
	 */
	public java.lang.Integer getSORTID() {
		return getInt("SORTID");
	}

	/**
	 *    少
	 */
	public void setWageUsed(java.lang.Integer wageUsed) {
		set("WAGE_USED", wageUsed);
	}
	
	/**
	 *    少
	 */
	public java.lang.Integer getWageUsed() {
		return getInt("WAGE_USED");
	}

}
