package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUserRolePermission<M extends BaseSysUserRolePermission<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setUserID(java.lang.String userID) {
		set("userID", userID);
	}
	
	public java.lang.String getUserID() {
		return getStr("userID");
	}

	public void setRoleID(java.lang.String roleID) {
		set("roleID", roleID);
	}
	
	public java.lang.String getRoleID() {
		return getStr("roleID");
	}

	public void setPermission(java.lang.String permission) {
		set("permission", permission);
	}
	
	public java.lang.String getPermission() {
		return getStr("permission");
	}

	public void setOrgCode(java.lang.String orgCode) {
		set("orgCode", orgCode);
	}
	
	public java.lang.String getOrgCode() {
		return getStr("orgCode");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
