package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseImpFile<M extends BaseImpFile<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setFileId(java.lang.String fileId) {
		set("fileId", fileId);
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getFileId() {
		return getStr("fileId");
	}

	/**
	 * 文件路径
	 */
	public void setUploadUrl(java.lang.String uploadUrl) {
		set("uploadUrl", uploadUrl);
	}
	
	/**
	 * 文件路径
	 */
	public java.lang.String getUploadUrl() {
		return getStr("uploadUrl");
	}

	/**
	 * 文件名
	 */
	public void setFileName(java.lang.String fileName) {
		set("fileName", fileName);
	}
	
	/**
	 * 文件名
	 */
	public java.lang.String getFileName() {
		return getStr("fileName");
	}

	/**
	 * 匹配是否成功（true，false）
	 */
	public void setIsSuccessful(java.lang.String isSuccessful) {
		set("isSuccessful", isSuccessful);
	}
	
	/**
	 * 匹配是否成功（true，false）
	 */
	public java.lang.String getIsSuccessful() {
		return getStr("isSuccessful");
	}

}
