package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA99z1<M extends BaseA99z1<M>> extends Model<M> implements IBean {

	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	public void setA99Z100(java.lang.String A99Z100) {
		set("A99Z100", A99Z100);
	}
	
	public java.lang.String getA99Z100() {
		return getStr("A99Z100");
	}

	/**
	 * 该人员是否通过考录方式进入公务员队伍
	 */
	public void setA99Z101(java.lang.String A99Z101) {
		set("A99Z101", A99Z101);
	}
	
	/**
	 * 该人员是否通过考录方式进入公务员队伍
	 */
	public java.lang.String getA99Z101() {
		return getStr("A99Z101");
	}

	/**
	 * 公务员考录时间
	 */
	public void setA99Z102(java.lang.String A99Z102) {
		set("A99Z102", A99Z102);
	}
	
	/**
	 * 公务员考录时间
	 */
	public java.lang.String getA99Z102() {
		return getStr("A99Z102");
	}

	/**
	 * 该人员是否为选调生
	 */
	public void setA99Z103(java.lang.String A99Z103) {
		set("A99Z103", A99Z103);
	}
	
	/**
	 * 该人员是否为选调生
	 */
	public java.lang.String getA99Z103() {
		return getStr("A99Z103");
	}

	/**
	 * 该人员选调为选调生的具体时间。
	 */
	public void setA99Z104(java.lang.String A99Z104) {
		set("A99Z104", A99Z104);
	}
	
	/**
	 * 该人员选调为选调生的具体时间。
	 */
	public java.lang.String getA99Z104() {
		return getStr("A99Z104");
	}

}
