package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseB01<M extends BaseB01<M>> extends Model<M> implements IBean {

	public void setB0101(java.lang.String B0101) {
		set("B0101", B0101);
	}
	
	public java.lang.String getB0101() {
		return getStr("B0101");
	}

	public void setB0104(java.lang.String B0104) {
		set("B0104", B0104);
	}
	
	public java.lang.String getB0104() {
		return getStr("B0104");
	}

	public void setB0107(java.lang.String B0107) {
		set("B0107", B0107);
	}
	
	public java.lang.String getB0107() {
		return getStr("B0107");
	}

	public void setB0111(java.lang.String B0111) {
		set("B0111", B0111);
	}
	
	public java.lang.String getB0111() {
		return getStr("B0111");
	}

	public void setB0114(java.lang.String B0114) {
		set("B0114", B0114);
	}
	
	public java.lang.String getB0114() {
		return getStr("B0114");
	}

	public void setB0117(java.lang.String B0117) {
		set("B0117", B0117);
	}
	
	public java.lang.String getB0117() {
		return getStr("B0117");
	}

	public void setB0121(java.lang.String B0121) {
		set("B0121", B0121);
	}
	
	public java.lang.String getB0121() {
		return getStr("B0121");
	}

	public void setB0124(java.lang.String B0124) {
		set("B0124", B0124);
	}
	
	public java.lang.String getB0124() {
		return getStr("B0124");
	}

	public void setB0127(java.lang.String B0127) {
		set("B0127", B0127);
	}
	
	public java.lang.String getB0127() {
		return getStr("B0127");
	}

	public void setB0131(java.lang.String B0131) {
		set("B0131", B0131);
	}
	
	public java.lang.String getB0131() {
		return getStr("B0131");
	}

	public void setB0140(java.lang.String B0140) {
		set("B0140", B0140);
	}
	
	public java.lang.String getB0140() {
		return getStr("B0140");
	}

	public void setB0141(java.lang.String B0141) {
		set("B0141", B0141);
	}
	
	public java.lang.String getB0141() {
		return getStr("B0141");
	}

	public void setB0142(java.lang.Integer B0142) {
		set("B0142", B0142);
	}
	
	public java.lang.Integer getB0142() {
		return getInt("B0142");
	}

	public void setB0143(java.lang.String B0143) {
		set("B0143", B0143);
	}
	
	public java.lang.String getB0143() {
		return getStr("B0143");
	}

	public void setB0150(java.lang.Integer B0150) {
		set("B0150", B0150);
	}
	
	public java.lang.Integer getB0150() {
		return getInt("B0150");
	}

	public void setB0180(java.lang.String B0180) {
		set("B0180", B0180);
	}
	
	public java.lang.String getB0180() {
		return getStr("B0180");
	}

	public void setB0183(java.lang.Integer B0183) {
		set("B0183", B0183);
	}
	
	public java.lang.Integer getB0183() {
		return getInt("B0183");
	}

	public void setB0185(java.lang.Integer B0185) {
		set("B0185", B0185);
	}
	
	public java.lang.Integer getB0185() {
		return getInt("B0185");
	}

	public void setB0188(java.lang.Integer B0188) {
		set("B0188", B0188);
	}
	
	public java.lang.Integer getB0188() {
		return getInt("B0188");
	}

	public void setB0189(java.lang.Integer B0189) {
		set("B0189", B0189);
	}
	
	public java.lang.Integer getB0189() {
		return getInt("B0189");
	}

	public void setB0190(java.lang.Integer B0190) {
		set("B0190", B0190);
	}
	
	public java.lang.Integer getB0190() {
		return getInt("B0190");
	}

	public void setB0191(java.lang.String B0191) {
		set("B0191", B0191);
	}
	
	public java.lang.String getB0191() {
		return getStr("B0191");
	}

	public void setB0191A(java.lang.Integer B0191A) {
		set("B0191A", B0191A);
	}
	
	public java.lang.Integer getB0191A() {
		return getInt("B0191A");
	}

	public void setB0192(java.lang.Integer B0192) {
		set("B0192", B0192);
	}
	
	public java.lang.Integer getB0192() {
		return getInt("B0192");
	}

	public void setB0193(java.lang.Integer B0193) {
		set("B0193", B0193);
	}
	
	public java.lang.Integer getB0193() {
		return getInt("B0193");
	}

	public void setB0194(java.lang.String B0194) {
		set("B0194", B0194);
	}
	
	public java.lang.String getB0194() {
		return getStr("B0194");
	}

	public void setB01TRANS(java.lang.Integer B01TRANS) {
		set("B01TRANS", B01TRANS);
	}
	
	public java.lang.Integer getB01TRANS() {
		return getInt("B01TRANS");
	}

	public void setB01IP(java.lang.String B01IP) {
		set("B01IP", B01IP);
	}
	
	public java.lang.String getB01IP() {
		return getStr("B01IP");
	}

	public void setB0227(java.lang.Integer B0227) {
		set("B0227", B0227);
	}
	
	public java.lang.Integer getB0227() {
		return getInt("B0227");
	}

	public void setB0232(java.lang.Integer B0232) {
		set("B0232", B0232);
	}
	
	public java.lang.Integer getB0232() {
		return getInt("B0232");
	}

	public void setB0233(java.lang.Integer B0233) {
		set("B0233", B0233);
	}
	
	public java.lang.Integer getB0233() {
		return getInt("B0233");
	}

	public void setSORTID(java.lang.Integer SORTID) {
		set("SORTID", SORTID);
	}
	
	public java.lang.Integer getSORTID() {
		return getInt("SORTID");
	}

	public void setUSED(java.lang.String USED) {
		set("USED", USED);
	}
	
	public java.lang.String getUSED() {
		return getStr("USED");
	}

	public void setUPDATED(java.lang.String UPDATED) {
		set("UPDATED", UPDATED);
	}
	
	public java.lang.String getUPDATED() {
		return getStr("UPDATED");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("CREATE_USER", createUser);
	}
	
	public java.lang.String getCreateUser() {
		return getStr("CREATE_USER");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("CREATE_DATE", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("CREATE_DATE");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("UPDATE_USER", updateUser);
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("UPDATE_USER");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("UPDATE_DATE", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("UPDATE_DATE");
	}

	public void setSTATUS(java.lang.String STATUS) {
		set("STATUS", STATUS);
	}
	
	public java.lang.String getSTATUS() {
		return getStr("STATUS");
	}

	public void setB0238(java.util.Date B0238) {
		set("B0238", B0238);
	}
	
	public java.util.Date getB0238() {
		return get("B0238");
	}

	public void setB0239(java.lang.String B0239) {
		set("B0239", B0239);
	}
	
	public java.lang.String getB0239() {
		return getStr("B0239");
	}

	public void setB0234(java.lang.Integer B0234) {
		set("B0234", B0234);
	}
	
	public java.lang.Integer getB0234() {
		return getInt("B0234");
	}

	public void setB0235(java.lang.Integer B0235) {
		set("B0235", B0235);
	}
	
	public java.lang.Integer getB0235() {
		return getInt("B0235");
	}

	public void setB0236(java.lang.Integer B0236) {
		set("B0236", B0236);
	}
	
	public java.lang.Integer getB0236() {
		return getInt("B0236");
	}

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("isDelete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("isDelete");
	}

	public void setB0194A(java.lang.String B0194A) {
		set("B0194A", B0194A);
	}
	
	public java.lang.String getB0194A() {
		return getStr("B0194A");
	}

	public void setSystem(java.lang.String system) {
		set("system", system);
	}
	
	public java.lang.String getSystem() {
		return getStr("system");
	}

	public void setB01Z101(java.lang.String B01Z101) {
		set("B01Z101", B01Z101);
	}
	
	public java.lang.String getB01Z101() {
		return getStr("B01Z101");
	}

	public void setB01Z103(java.lang.String B01Z103) {
		set("B01Z103", B01Z103);
	}
	
	public java.lang.String getB01Z103() {
		return getStr("B01Z103");
	}

	public void setB01Z104(java.lang.String B01Z104) {
		set("B01Z104", B01Z104);
	}
	
	public java.lang.String getB01Z104() {
		return getStr("B01Z104");
	}

	public void setB01Z105(java.lang.String B01Z105) {
		set("B01Z105", B01Z105);
	}
	
	public java.lang.String getB01Z105() {
		return getStr("B01Z105");
	}

	public void setB01Z106(java.lang.String B01Z106) {
		set("B01Z106", B01Z106);
	}
	
	public java.lang.String getB01Z106() {
		return getStr("B01Z106");
	}

	public void setB01Z107(java.lang.String B01Z107) {
		set("B01Z107", B01Z107);
	}
	
	public java.lang.String getB01Z107() {
		return getStr("B01Z107");
	}

	public void setB01Z102(java.lang.String B01Z102) {
		set("B01Z102", B01Z102);
	}
	
	public java.lang.String getB01Z102() {
		return getStr("B01Z102");
	}

	public void setOrgTreeSort(java.lang.Long orgTreeSort) {
		set("orgTreeSort", orgTreeSort);
	}
	
	public java.lang.Long getOrgTreeSort() {
		return getLong("orgTreeSort");
	}

	public void setBzcyzz(java.lang.Long bzcyzz) {
		set("bzcyzz", bzcyzz);
	}
	
	public java.lang.Long getBzcyzz() {
		return getLong("bzcyzz");
	}

	public void setBzcyfz(java.lang.Long bzcyfz) {
		set("bzcyfz", bzcyfz);
	}
	
	public java.lang.Long getBzcyfz() {
		return getLong("bzcyfz");
	}

	public void setBzcyhj(java.lang.Long bzcyhj) {
		set("bzcyhj", bzcyhj);
	}
	
	public java.lang.Long getBzcyhj() {
		return getLong("bzcyhj");
	}

	public void setB0164(java.util.Date B0164) {
		set("B0164", B0164);
	}
	
	public java.util.Date getB0164() {
		return get("B0164");
	}

	public void setB0167(java.lang.String B0167) {
		set("B0167", B0167);
	}
	
	public java.lang.String getB0167() {
		return getStr("B0167");
	}

	public void setB0268(java.util.Date B0268) {
		set("B0268", B0268);
	}
	
	public java.util.Date getB0268() {
		return get("B0268");
	}

	public void setB0269(java.lang.String B0269) {
		set("B0269", B0269);
	}
	
	public java.lang.String getB0269() {
		return getStr("B0269");
	}

}
