package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVerifyRule<M extends BaseVerifyRule<M>> extends Model<M> implements IBean {

	public void setVSC001(java.lang.String VSC001) {
		set("VSC001", VSC001);
	}
	
	public java.lang.String getVSC001() {
		return getStr("VSC001");
	}

	public void setVRU001(java.lang.String VRU001) {
		set("VRU001", VRU001);
	}
	
	public java.lang.String getVRU001() {
		return getStr("VRU001");
	}

	public void setVRU002(java.lang.String VRU002) {
		set("VRU002", VRU002);
	}
	
	public java.lang.String getVRU002() {
		return getStr("VRU002");
	}

	public void setVRU003(java.lang.String VRU003) {
		set("VRU003", VRU003);
	}
	
	public java.lang.String getVRU003() {
		return getStr("VRU003");
	}

	public void setVRU004(java.lang.String VRU004) {
		set("VRU004", VRU004);
	}
	
	public java.lang.String getVRU004() {
		return getStr("VRU004");
	}

	public void setVRU005(java.lang.String VRU005) {
		set("VRU005", VRU005);
	}
	
	public java.lang.String getVRU005() {
		return getStr("VRU005");
	}

	public void setVRU006(java.lang.String VRU006) {
		set("VRU006", VRU006);
	}
	
	public java.lang.String getVRU006() {
		return getStr("VRU006");
	}

	public void setVRU007(java.lang.String VRU007) {
		set("VRU007", VRU007);
	}
	
	public java.lang.String getVRU007() {
		return getStr("VRU007");
	}

	public void setVRU008(java.lang.String VRU008) {
		set("VRU008", VRU008);
	}
	
	public java.lang.String getVRU008() {
		return getStr("VRU008");
	}

	public void setVRU009(java.lang.String VRU009) {
		set("VRU009", VRU009);
	}
	
	public java.lang.String getVRU009() {
		return getStr("VRU009");
	}

}
