package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCodeValue<M extends BaseCodeValue<M>> extends Model<M> implements IBean {

	/**
	 * 代码项序号
	 */
	public void setCodeValueSeq(java.lang.Integer codeValueSeq) {
		set("CODE_VALUE_SEQ", codeValueSeq);
	}
	
	/**
	 * 代码项序号
	 */
	public java.lang.Integer getCodeValueSeq() {
		return getInt("CODE_VALUE_SEQ");
	}

	/**
	 * 代码类别编码
	 */
	public void setCodeType(java.lang.String codeType) {
		set("CODE_TYPE", codeType);
	}
	
	/**
	 * 代码类别编码
	 */
	public java.lang.String getCodeType() {
		return getStr("CODE_TYPE");
	}

	public void setCodeColumnName(java.lang.String codeColumnName) {
		set("CODE_COLUMN_NAME", codeColumnName);
	}
	
	public java.lang.String getCodeColumnName() {
		return getStr("CODE_COLUMN_NAME");
	}

	public void setCodeLevel(java.lang.String codeLevel) {
		set("CODE_LEVEL", codeLevel);
	}
	
	public java.lang.String getCodeLevel() {
		return getStr("CODE_LEVEL");
	}

	/**
	 * 代码值
	 */
	public void setCodeValue(java.lang.String codeValue) {
		set("CODE_VALUE", codeValue);
	}
	
	/**
	 * 代码值
	 */
	public java.lang.String getCodeValue() {
		return getStr("CODE_VALUE");
	}

	public void setININO(java.math.BigDecimal ININO) {
		set("ININO", ININO);
	}
	
	public java.math.BigDecimal getININO() {
		return get("ININO");
	}

	/**
	 * 父代码值
	 */
	public void setSubCodeValue(java.lang.String subCodeValue) {
		set("SUB_CODE_VALUE", subCodeValue);
	}
	
	/**
	 * 父代码值
	 */
	public java.lang.String getSubCodeValue() {
		return getStr("SUB_CODE_VALUE");
	}

	/**
	 * 代码名称
	 */
	public void setCodeName(java.lang.String codeName) {
		set("CODE_NAME", codeName);
	}
	
	/**
	 * 代码名称
	 */
	public java.lang.String getCodeName() {
		return getStr("CODE_NAME");
	}

	/**
	 * 代码名称2
	 */
	public void setCodeName2(java.lang.String codeName2) {
		set("CODE_NAME2", codeName2);
	}
	
	/**
	 * 代码名称2
	 */
	public java.lang.String getCodeName2() {
		return getStr("CODE_NAME2");
	}

	/**
	 * 代码名称3
	 */
	public void setCodeName3(java.lang.String codeName3) {
		set("CODE_NAME3", codeName3);
	}
	
	/**
	 * 代码名称3
	 */
	public java.lang.String getCodeName3() {
		return getStr("CODE_NAME3");
	}

	public void setCodeRemark(java.lang.String codeRemark) {
		set("CODE_REMARK", codeRemark);
	}
	
	public java.lang.String getCodeRemark() {
		return getStr("CODE_REMARK");
	}

	/**
	 * 代码名称首字母
	 */
	public void setCodeSpelling(java.lang.String codeSpelling) {
		set("CODE_SPELLING", codeSpelling);
	}
	
	/**
	 * 代码名称首字母
	 */
	public java.lang.String getCodeSpelling() {
		return getStr("CODE_SPELLING");
	}

	/**
	 * 是否为自定义代码（0：否，1：是）
	 */
	public void setISCUSTOMIZE(java.lang.String ISCUSTOMIZE) {
		set("ISCUSTOMIZE", ISCUSTOMIZE);
	}
	
	/**
	 * 是否为自定义代码（0：否，1：是）
	 */
	public java.lang.String getISCUSTOMIZE() {
		return getStr("ISCUSTOMIZE");
	}

	public void setCodeAssist(java.lang.String codeAssist) {
		set("CODE_ASSIST", codeAssist);
	}
	
	public java.lang.String getCodeAssist() {
		return getStr("CODE_ASSIST");
	}

	/**
	 * 代码状态（0：不显示，1：显示）
	 */
	public void setCodeStatus(java.lang.String codeStatus) {
		set("CODE_STATUS", codeStatus);
	}
	
	/**
	 * 代码状态（0：不显示，1：显示）
	 */
	public java.lang.String getCodeStatus() {
		return getStr("CODE_STATUS");
	}

	/**
	 * 是否可选（0：不可，1：可以选择）
	 */
	public void setCodeLeaf(java.lang.String codeLeaf) {
		set("CODE_LEAF", codeLeaf);
	}
	
	/**
	 * 是否可选（0：不可，1：可以选择）
	 */
	public java.lang.String getCodeLeaf() {
		return getStr("CODE_LEAF");
	}

	public void setStartDate(java.lang.String startDate) {
		set("START_DATE", startDate);
	}
	
	public java.lang.String getStartDate() {
		return getStr("START_DATE");
	}

	public void setStopDate(java.lang.String stopDate) {
		set("STOP_DATE", stopDate);
	}
	
	public java.lang.String getStopDate() {
		return getStr("STOP_DATE");
	}

}
