package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA63<M extends BaseA63<M>> extends Model<M> implements IBean {

	/**
	 * 人员唯一标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员唯一标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 公开选调   等
	 */
	public void setA2951(java.lang.String A2951) {
		set("A2951", A2951);
	}
	
	/**
	 * 公开选调   等
	 */
	public java.lang.String getA2951() {
		return getStr("A2951");
	}

	/**
	 * 选调类别                    ZB142《遴选或选调类别》   等
	 */
	public void setA6302(java.lang.String A6302) {
		set("A6302", A6302);
	}
	
	/**
	 * 选调类别                    ZB142《遴选或选调类别》   等
	 */
	public java.lang.String getA6302() {
		return getStr("A6302");
	}

	/**
	 * 原单位类别               ZB144《原单位类别》   等
	 */
	public void setA6303(java.lang.String A6303) {
		set("A6303", A6303);
	}
	
	/**
	 * 原单位类别               ZB144《原单位类别》   等
	 */
	public java.lang.String getA6303() {
		return getStr("A6303");
	}

	/**
	 * 原单位层级               ZB141《工作单位层次代码》   等
	 */
	public void setA6304(java.lang.String A6304) {
		set("A6304", A6304);
	}
	
	/**
	 * 原单位层级               ZB141《工作单位层次代码》   等
	 */
	public java.lang.String getA6304() {
		return getStr("A6304");
	}

	/**
	 * 原单位职称或职务ZB145《职称代码》   等
	 */
	public void setA6305(java.lang.String A6305) {
		set("A6305", A6305);
	}
	
	/**
	 * 原单位职称或职务ZB145《职称代码》   等
	 */
	public java.lang.String getA6305() {
		return getStr("A6305");
	}

	/**
	 * 公开选调时间   等
	 */
	public void setA6306(java.lang.String A6306) {
		set("A6306", A6306);
	}
	
	/**
	 * 公开选调时间   等
	 */
	public java.lang.String getA6306() {
		return getStr("A6306");
	}

	/**
	 * 是否有海外留学经历   等
	 */
	public void setA6307(java.lang.String A6307) {
		set("A6307", A6307);
	}
	
	/**
	 * 是否有海外留学经历   等
	 */
	public java.lang.String getA6307() {
		return getStr("A6307");
	}

	/**
	 * 留学年限   等
	 */
	public void setA6308(java.lang.String A6308) {
		set("A6308", A6308);
	}
	
	/**
	 * 留学年限   等
	 */
	public java.lang.String getA6308() {
		return getStr("A6308");
	}

	/**
	 * 是否有海外工作经历   等
	 */
	public void setA6309(java.lang.String A6309) {
		set("A6309", A6309);
	}
	
	/**
	 * 是否有海外工作经历   等
	 */
	public java.lang.String getA6309() {
		return getStr("A6309");
	}

	/**
	 * 海外工作年限   等
	 */
	public void setA6310(java.lang.String A6310) {
		set("A6310", A6310);
	}
	
	/**
	 * 海外工作年限   等
	 */
	public java.lang.String getA6310() {
		return getStr("A6310");
	}

}
