package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserB01Permission<M extends BaseUserB01Permission<M>> extends Model<M> implements IBean {

	/**
	 * 表的唯一标示
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 表的唯一标示
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 用户的唯一id
	 */
	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}
	
	/**
	 * 用户的唯一id
	 */
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	/**
	 * 用户管理的权限id(全息)
	 */
	public void setOrgId(java.lang.String orgId) {
		set("orgId", orgId);
	}
	
	/**
	 * 用户管理的权限id(全息)
	 */
	public java.lang.String getOrgId() {
		return getStr("orgId");
	}

	/**
	 * 是否只读 
	 */
	public void setIsReadOnly(java.lang.Integer isReadOnly) {
		set("isReadOnly", isReadOnly);
	}
	
	/**
	 * 是否只读 
	 */
	public java.lang.Integer getIsReadOnly() {
		return getInt("isReadOnly");
	}

	/**
	 * 系统标示
	 */
	public void setSystem(java.lang.String system) {
		set("system", system);
	}
	
	/**
	 * 系统标示
	 */
	public java.lang.String getSystem() {
		return getStr("system");
	}

	/**
	 * 是否是配置添加的（0用户模块，1单位设置模块）
	 */
	public void setIsConfig(java.lang.String isConfig) {
		set("isConfig", isConfig);
	}
	
	/**
	 * 是否是配置添加的（0用户模块，1单位设置模块）
	 */
	public java.lang.String getIsConfig() {
		return getStr("isConfig");
	}

}
