package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCodeTable<M extends BaseCodeTable<M>> extends Model<M> implements IBean {

	/**
	 * 信息表编码
	 */
	public void setTableCode(java.lang.String tableCode) {
		set("TABLE_CODE", tableCode);
	}
	
	/**
	 * 信息表编码
	 */
	public java.lang.String getTableCode() {
		return getStr("TABLE_CODE");
	}

	/**
	 * 信息表名称
	 */
	public void setTableName(java.lang.String tableName) {
		set("TABLE_NAME", tableName);
	}
	
	/**
	 * 信息表名称
	 */
	public java.lang.String getTableName() {
		return getStr("TABLE_NAME");
	}

	/**
	 * 是否在查询、统计、表册等功能中显示出字段
	 */
	public void setIslook(java.lang.String islook) {
		set("islook", islook);
	}
	
	/**
	 * 是否在查询、统计、表册等功能中显示出字段
	 */
	public java.lang.String getIslook() {
		return getStr("islook");
	}

}
