package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA01<M extends BaseA01<M>> extends Model<M> implements IBean {

	/**
	 * 人员统一标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员统一标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 姓名   等
	 */
	public void setA0101(java.lang.String A0101) {
		set("A0101", A0101);
	}
	
	/**
	 * 姓名   等
	 */
	public java.lang.String getA0101() {
		return getStr("A0101");
	}

	/**
	 * 姓名拼音缩写   等
	 */
	public void setA0102(java.lang.String A0102) {
		set("A0102", A0102);
	}
	
	/**
	 * 姓名拼音缩写   等
	 */
	public java.lang.String getA0102() {
		return getStr("A0102");
	}

	/**
	 * 性别   等
	 */
	public void setA0104(java.lang.String A0104) {
		set("A0104", A0104);
	}
	
	/**
	 * 性别   等
	 */
	public java.lang.String getA0104() {
		return getStr("A0104");
	}

	/**
	 * 出生日期   等
	 */
	public void setA0107(java.util.Date A0107) {
		set("A0107", A0107);
	}
	
	/**
	 * 出生日期   等
	 */
	public java.util.Date getA0107() {
		return get("A0107");
	}

	/**
	 * 籍贯   等
	 */
	public void setA0111A(java.lang.String A0111A) {
		set("A0111A", A0111A);
	}
	
	/**
	 * 籍贯   等
	 */
	public java.lang.String getA0111A() {
		return getStr("A0111A");
	}

	/**
	 * 出生地   等
	 */
	public void setA0114A(java.lang.String A0114A) {
		set("A0114A", A0114A);
	}
	
	/**
	 * 出生地   等
	 */
	public java.lang.String getA0114A() {
		return getStr("A0114A");
	}

	/**
	 * 成长地    多
	 */
	public void setA0115A(java.lang.String A0115A) {
		set("A0115A", A0115A);
	}
	
	/**
	 * 成长地    多
	 */
	public java.lang.String getA0115A() {
		return getStr("A0115A");
	}

	/**
	 * 民族   等
	 */
	public void setA0117(java.lang.String A0117) {
		set("A0117", A0117);
	}
	
	/**
	 * 民族   等
	 */
	public java.lang.String getA0117() {
		return getStr("A0117");
	}

	/**
	 * 健康状况   等
	 */
	public void setA0128(java.lang.String A0128) {
		set("A0128", A0128);
	}
	
	/**
	 * 健康状况   等
	 */
	public java.lang.String getA0128() {
		return getStr("A0128");
	}

	/**
	 * 参加工作时间   等
	 */
	public void setA0134(java.util.Date A0134) {
		set("A0134", A0134);
	}
	
	/**
	 * 参加工作时间   等
	 */
	public java.util.Date getA0134() {
		return get("A0134");
	}

	/**
	 * 入党时间文字   等
	 */
	public void setA0140(java.lang.String A0140) {
		set("A0140", A0140);
	}
	
	/**
	 * 入党时间文字   等
	 */
	public java.lang.String getA0140() {
		return getStr("A0140");
	}

	/**
	 * 政治面貌   等
	 */
	public void setA0141(java.lang.String A0141) {
		set("A0141", A0141);
	}
	
	/**
	 * 政治面貌   等
	 */
	public java.lang.String getA0141() {
		return getStr("A0141");
	}

	/**
	 * 入党时间   等
	 */
	public void setA0144(java.util.Date A0144) {
		set("A0144", A0144);
	}
	
	/**
	 * 入党时间   等
	 */
	public java.util.Date getA0144() {
		return get("A0144");
	}

	/**
	 * 第二党派   等
	 */
	public void setA3921(java.lang.String A3921) {
		set("A3921", A3921);
	}
	
	/**
	 * 第二党派   等
	 */
	public java.lang.String getA3921() {
		return getStr("A3921");
	}

	/**
	 * 第三党派   等
	 */
	public void setA3927(java.lang.String A3927) {
		set("A3927", A3927);
	}
	
	/**
	 * 第三党派   等
	 */
	public java.lang.String getA3927() {
		return getStr("A3927");
	}

	/**
	 * 人员类别   等
	 */
	public void setA0160(java.lang.String A0160) {
		set("A0160", A0160);
	}
	
	/**
	 * 人员类别   等
	 */
	public java.lang.String getA0160() {
		return getStr("A0160");
	}

	/**
	 * 人员管理状态   等
	 */
	public void setA0163(java.lang.String A0163) {
		set("A0163", A0163);
	}
	
	/**
	 * 人员管理状态   等
	 */
	public java.lang.String getA0163() {
		return getStr("A0163");
	}

	/**
	 * 管理类别   等
	 */
	public void setA0165(java.lang.String A0165) {
		set("A0165", A0165);
	}
	
	/**
	 * 管理类别   等
	 */
	public java.lang.String getA0165() {
		return getStr("A0165");
	}

	/**
	 * 公民身份号码   等
	 */
	public void setA0184(java.lang.String A0184) {
		set("A0184", A0184);
	}
	
	/**
	 * 公民身份号码   等
	 */
	public java.lang.String getA0184() {
		return getStr("A0184");
	}

	/**
	 * 专长   等
	 */
	public void setA0187A(java.lang.String A0187A) {
		set("A0187A", A0187A);
	}
	
	/**
	 * 专长   等
	 */
	public java.lang.String getA0187A() {
		return getStr("A0187A");
	}

	/**
	 * 现工作单位及职务简称   等
	 */
	public void setA0192(java.lang.String A0192) {
		set("A0192", A0192);
	}
	
	/**
	 * 现工作单位及职务简称   等
	 */
	public java.lang.String getA0192() {
		return getStr("A0192");
	}

	/**
	 * 现工作单位及职务全称   等
	 */
	public void setA0192A(java.lang.String A0192A) {
		set("A0192A", A0192A);
	}
	
	/**
	 * 现工作单位及职务全称   等
	 */
	public java.lang.String getA0192A() {
		return getStr("A0192A");
	}

	/**
	 * 职务层次    多
	 */
	public void setA0221(java.lang.String A0221) {
		set("A0221", A0221);
	}
	
	/**
	 * 职务层次    多
	 */
	public java.lang.String getA0221() {
		return getStr("A0221");
	}

	/**
	 * 任现职务层次时间   多
	 */
	public void setA0288(java.util.Date A0288) {
		set("A0288", A0288);
	}
	
	/**
	 * 任现职务层次时间   多
	 */
	public java.util.Date getA0288() {
		return get("A0288");
	}

	/**
	 * 职级   等
	 */
	public void setA0192D(java.lang.String A0192D) {
		set("A0192D", A0192D);
	}
	
	/**
	 * 职级   等
	 */
	public java.lang.String getA0192D() {
		return getStr("A0192D");
	}

	/**
	 * 任该职级时间   多
	 */
	public void setA0192C(java.util.Date A0192C) {
		set("A0192C", A0192C);
	}
	
	/**
	 * 任该职级时间   多
	 */
	public java.util.Date getA0192C() {
		return get("A0192C");
	}

	/**
	 * 专业技术职务   等
	 */
	public void setA0196(java.lang.String A0196) {
		set("A0196", A0196);
	}
	
	/**
	 * 专业技术职务   等
	 */
	public java.lang.String getA0196() {
		return getStr("A0196");
	}

	/**
	 * 是否具有两年以上基层工作经历   多 1 是 0 否
	 */
	public void setA0197(java.lang.String A0197) {
		set("A0197", A0197);
	}
	
	/**
	 * 是否具有两年以上基层工作经历   多 1 是 0 否
	 */
	public java.lang.String getA0197() {
		return getStr("A0197");
	}

	/**
	 * 统计关系所在单位   等
	 */
	public void setA0195(java.lang.String A0195) {
		set("A0195", A0195);
	}
	
	/**
	 * 统计关系所在单位   等
	 */
	public java.lang.String getA0195() {
		return getStr("A0195");
	}

	/**
	 * 简历   等
	 */
	public void setA1701(java.lang.String A1701) {
		set("A1701", A1701);
	}
	
	/**
	 * 简历   等
	 */
	public java.lang.String getA1701() {
		return getStr("A1701");
	}

	public void setA14Z101(java.lang.String A14Z101) {
		set("A14Z101", A14Z101);
	}
	
	public java.lang.String getA14Z101() {
		return getStr("A14Z101");
	}

	public void setA15Z101(java.lang.String A15Z101) {
		set("A15Z101", A15Z101);
	}
	
	public java.lang.String getA15Z101() {
		return getStr("A15Z101");
	}

	/**
	 * 级别   等
	 */
	public void setA0120(java.lang.String A0120) {
		set("A0120", A0120);
	}
	
	/**
	 * 级别   等
	 */
	public java.lang.String getA0120() {
		return getStr("A0120");
	}

	/**
	 * 编制类型   等
	 */
	public void setA0121(java.lang.String A0121) {
		set("A0121", A0121);
	}
	
	/**
	 * 编制类型   等
	 */
	public java.lang.String getA0121() {
		return getStr("A0121");
	}

	/**
	 * 公务员登记时间   多
	 */
	public void setA2949(java.util.Date A2949) {
		set("A2949", A2949);
	}
	
	/**
	 * 公务员登记时间   多
	 */
	public java.util.Date getA2949() {
		return get("A2949");
	}

	/**
	 * 专业技术类公务员任职资格   等
	 */
	public void setA0122(java.lang.String A0122) {
		set("A0122", A0122);
	}
	
	/**
	 * 专业技术类公务员任职资格   等
	 */
	public java.lang.String getA0122() {
		return getStr("A0122");
	}

	/**
	 * 性别(汉字)1
	 */
	public void setA0104A(java.lang.String A0104A) {
		set("A0104A", A0104A);
	}
	
	/**
	 * 性别(汉字)1
	 */
	public java.lang.String getA0104A() {
		return getStr("A0104A");
	}

	/**
	 * 籍贯
	 */
	public void setA0111(java.lang.String A0111) {
		set("A0111", A0111);
	}
	
	/**
	 * 籍贯
	 */
	public java.lang.String getA0111() {
		return getStr("A0111");
	}

	/**
	 * 出生地
	 */
	public void setA0114(java.lang.String A0114) {
		set("A0114", A0114);
	}
	
	/**
	 * 出生地
	 */
	public java.lang.String getA0114() {
		return getStr("A0114");
	}

	/**
	 * 民族(汉字)1
	 */
	public void setA0117A(java.lang.String A0117A) {
		set("A0117A", A0117A);
	}
	
	/**
	 * 民族(汉字)1
	 */
	public java.lang.String getA0117A() {
		return getStr("A0117A");
	}

	/**
	 * 健康状况1
	 */
	public void setA0128B(java.lang.String A0128B) {
		set("A0128B", A0128B);
	}
	
	/**
	 * 健康状况1
	 */
	public java.lang.String getA0128B() {
		return getStr("A0128B");
	}

	/**
	 * 记录本人三个政治面貌1
	 */
	public void setA0141D(java.lang.String A0141D) {
		set("A0141D", A0141D);
	}
	
	/**
	 * 记录本人三个政治面貌1
	 */
	public java.lang.String getA0141D() {
		return getStr("A0141D");
	}

	/**
	 * 参加组织时间二1
	 */
	public void setA0144B(java.lang.String A0144B) {
		set("A0144B", A0144B);
	}
	
	/**
	 * 参加组织时间二1
	 */
	public java.lang.String getA0144B() {
		return getStr("A0144B");
	}

	/**
	 * 参加组织时间三1
	 */
	public void setA0144C(java.lang.String A0144C) {
		set("A0144C", A0144C);
	}
	
	/**
	 * 参加组织时间三1
	 */
	public java.lang.String getA0144C() {
		return getStr("A0144C");
	}

	/**
	 * 最高职务层次
	 */
	public void setA0148(java.lang.String A0148) {
		set("A0148", A0148);
	}
	
	/**
	 * 最高职务层次
	 */
	public java.lang.String getA0148() {
		return getStr("A0148");
	}

	/**
	 * 职务层次批准时间1
	 */
	public void setA0148C(java.lang.String A0148C) {
		set("A0148C", A0148C);
	}
	
	/**
	 * 职务层次批准时间1
	 */
	public java.lang.String getA0148C() {
		return getStr("A0148C");
	}

	/**
	 * 职务层次
	 */
	public void setA0149(java.lang.String A0149) {
		set("A0149", A0149);
	}
	
	/**
	 * 职务层次
	 */
	public java.lang.String getA0149() {
		return getStr("A0149");
	}

	/**
	 * 该人参加公务员登记的标识。1—登记；2—暂缓登记；3—不予登记。
	 */
	public void setA0151(java.lang.String A0151) {
		set("A0151", A0151);
	}
	
	/**
	 * 该人参加公务员登记的标识。1—登记；2—暂缓登记；3—不予登记。
	 */
	public java.lang.String getA0151() {
		return getStr("A0151");
	}

	/**
	 * 公务员登记类别1—公务员；02—参照管理人员；3—其他
	 */
	public void setA0153(java.lang.String A0153) {
		set("A0153", A0153);
	}
	
	/**
	 * 公务员登记类别1—公务员；02—参照管理人员；3—其他
	 */
	public java.lang.String getA0153() {
		return getStr("A0153");
	}

	/**
	 * 人事关系所在单位名称1
	 */
	public void setA0157(java.lang.String A0157) {
		set("A0157", A0157);
	}
	
	/**
	 * 人事关系所在单位名称1
	 */
	public java.lang.String getA0157() {
		return getStr("A0157");
	}

	/**
	 * 公务员级别1
	 */
	public void setA0158(java.lang.String A0158) {
		set("A0158", A0158);
	}
	
	/**
	 * 公务员级别1
	 */
	public java.lang.String getA0158() {
		return getStr("A0158");
	}

	/**
	 * 公务员登记后所定职务
	 */
	public void setA0159(java.lang.String A0159) {
		set("A0159", A0159);
	}
	
	/**
	 * 公务员登记后所定职务
	 */
	public java.lang.String getA0159() {
		return getStr("A0159");
	}

	/**
	 * 职务拼接方式1
	 */
	public void setA015A(java.lang.String A015A) {
		set("A015A", A015A);
	}
	
	/**
	 * 职务拼接方式1
	 */
	public java.lang.String getA015A() {
		return getStr("A015A");
	}

	public void setA0161(java.lang.String A0161) {
		set("A0161", A0161);
	}
	
	public java.lang.String getA0161() {
		return getStr("A0161");
	}

	/**
	 * 公务员级别批准日期1
	 */
	public void setA0162(java.lang.String A0162) {
		set("A0162", A0162);
	}
	
	/**
	 * 公务员级别批准日期1
	 */
	public java.lang.String getA0162() {
		return getStr("A0162");
	}

	public void setA0180(java.lang.String A0180) {
		set("A0180", A0180);
	}
	
	public java.lang.String getA0180() {
		return getStr("A0180");
	}

	/**
	 * 与列表关联
	 */
	public void setA0191(java.lang.String A0191) {
		set("A0191", A0191);
	}
	
	/**
	 * 与列表关联
	 */
	public java.lang.String getA0191() {
		return getStr("A0191");
	}

	public void setA0192B(java.lang.String A0192B) {
		set("A0192B", A0192B);
	}
	
	public java.lang.String getA0192B() {
		return getStr("A0192B");
	}

	/**
	 * 职务层次1
	 */
	public void setA0193(java.lang.String A0193) {
		set("A0193", A0193);
	}
	
	/**
	 * 职务层次1
	 */
	public java.lang.String getA0193() {
		return getStr("A0193");
	}

	/**
	 * 该人在基层工作的时间是否2年以上-报送标准A0197
	 */
	public void setA0194U(java.lang.String A0194U) {
		set("A0194U", A0194U);
	}
	
	/**
	 * 该人在基层工作的时间是否2年以上-报送标准A0197
	 */
	public java.lang.String getA0194U() {
		return getStr("A0194U");
	}

	/**
	 * 照片路径1
	 */
	public void setA0198(java.lang.String A0198) {
		set("A0198", A0198);
	}
	
	/**
	 * 照片路径1
	 */
	public java.lang.String getA0198() {
		return getStr("A0198");
	}

	/**
	 * 用于区分是否是正在增加的人员，1为任免表导入人员；0为正常人员1
	 */
	public void setA0199(java.lang.String A0199) {
		set("A0199", A0199);
	}
	
	/**
	 * 用于区分是否是正在增加的人员，1为任免表导入人员；0为正常人员1
	 */
	public java.lang.String getA0199() {
		return getStr("A0199");
	}

	/**
	 * 最高职务层次类别1
	 */
	public void setA01K01(java.lang.String A01K01) {
		set("A01K01", A01K01);
	}
	
	/**
	 * 最高职务层次类别1
	 */
	public java.lang.String getA01K01() {
		return getStr("A01K01");
	}

	/**
	 * 该人是否有基层工作经验的标志。
	 */
	public void setA01K02(java.lang.String A01K02) {
		set("A01K02", A01K02);
	}
	
	/**
	 * 该人是否有基层工作经验的标志。
	 */
	public java.lang.String getA01K02() {
		return getStr("A01K02");
	}

	/**
	 * 呈报单审批结果
	 */
	public void setCBDRESULT(java.lang.String CBDRESULT) {
		set("CBDRESULT", CBDRESULT);
	}
	
	/**
	 * 呈报单审批结果
	 */
	public java.lang.String getCBDRESULT() {
		return getStr("CBDRESULT");
	}

	/**
	 * 呈报单位1
	 */
	public void setCBDW(java.lang.String CBDW) {
		set("CBDW", CBDW);
	}
	
	/**
	 * 呈报单位1
	 */
	public java.lang.String getCBDW() {
		return getStr("CBDW");
	}

	/**
	 * 多次保存结果1
	 */
	public void setISVALID(java.lang.String ISVALID) {
		set("ISVALID", ISVALID);
	}
	
	/**
	 * 多次保存结果1
	 */
	public java.lang.String getISVALID() {
		return getStr("ISVALID");
	}

	/**
	 * 年龄1
	 */
	public void setNL(java.lang.String NL) {
		set("NL", NL);
	}
	
	/**
	 * 年龄1
	 */
	public java.lang.String getNL() {
		return getStr("NL");
	}

	/**
	 * 拟免职务1
	 */
	public void setNMZW(java.lang.String NMZW) {
		set("NMZW", NMZW);
	}
	
	/**
	 * 拟免职务1
	 */
	public java.lang.String getNMZW() {
		return getStr("NMZW");
	}

	/**
	 * 拟任职务1
	 */
	public void setNRZW(java.lang.String NRZW) {
		set("NRZW", NRZW);
	}
	
	/**
	 * 拟任职务1
	 */
	public java.lang.String getNRZW() {
		return getStr("NRZW");
	}

	/**
	 * 历史离退人员所在的机构id
	 */
	public void setORGID(java.lang.String ORGID) {
		set("ORGID", ORGID);
	}
	
	/**
	 * 历史离退人员所在的机构id
	 */
	public java.lang.String getORGID() {
		return getStr("ORGID");
	}

	/**
	 * 最高全日制学历
	 */
	public void setQRZXL(java.lang.String QRZXL) {
		set("QRZXL", QRZXL);
	}
	
	/**
	 * 最高全日制学历
	 */
	public java.lang.String getQRZXL() {
		return getStr("QRZXL");
	}

	/**
	 * 院校系专业（最高全日制学历）
	 */
	public void setQRZXLXX(java.lang.String QRZXLXX) {
		set("QRZXLXX", QRZXLXX);
	}
	
	/**
	 * 院校系专业（最高全日制学历）
	 */
	public java.lang.String getQRZXLXX() {
		return getStr("QRZXLXX");
	}

	/**
	 * 最高全日制学位
	 */
	public void setQRZXW(java.lang.String QRZXW) {
		set("QRZXW", QRZXW);
	}
	
	/**
	 * 最高全日制学位
	 */
	public java.lang.String getQRZXW() {
		return getStr("QRZXW");
	}

	/**
	 * 院校系专业（最高全日制学位）
	 */
	public void setQRZXWXX(java.lang.String QRZXWXX) {
		set("QRZXWXX", QRZXWXX);
	}
	
	/**
	 * 院校系专业（最高全日制学位）
	 */
	public java.lang.String getQRZXWXX() {
		return getStr("QRZXWXX");
	}

	/**
	 * 任免理由1
	 */
	public void setRMLY(java.lang.String RMLY) {
		set("RMLY", RMLY);
	}
	
	/**
	 * 任免理由1
	 */
	public java.lang.String getRMLY() {
		return getStr("RMLY");
	}

	/**
	 * 状态 0完全删除 1正常 2历史库3离退人员4临时数据
	 */
	public void setSTATUS(java.lang.String STATUS) {
		set("STATUS", STATUS);
	}
	
	/**
	 * 状态 0完全删除 1正常 2历史库3离退人员4临时数据
	 */
	public java.lang.String getSTATUS() {
		return getStr("STATUS");
	}

	/**
	 * 填报人id
	 */
	public void setTBR(java.lang.String TBR) {
		set("TBR", TBR);
	}
	
	/**
	 * 填报人id
	 */
	public java.lang.String getTBR() {
		return getStr("TBR");
	}

	/**
	 * 填报人所在机构id  1-删
	 */
	public void setTBRJG(java.lang.String TBRJG) {
		set("TBRJG", TBRJG);
	}
	
	/**
	 * 填报人所在机构id  1-删
	 */
	public java.lang.String getTBRJG() {
		return getStr("TBRJG");
	}

	/**
	 * 结果集的用户名id号1
	 */
	public void setUSERLOG(java.lang.String USERLOG) {
		set("USERLOG", USERLOG);
	}
	
	/**
	 * 结果集的用户名id号1
	 */
	public java.lang.String getUSERLOG() {
		return getStr("USERLOG");
	}

	/**
	 * 修改人1
	 */
	public void setXGR(java.lang.String XGR) {
		set("XGR", XGR);
	}
	
	/**
	 * 修改人1
	 */
	public java.lang.String getXGR() {
		return getStr("XGR");
	}

	/**
	 * 最高在职学历
	 */
	public void setZZXL(java.lang.String ZZXL) {
		set("ZZXL", ZZXL);
	}
	
	/**
	 * 最高在职学历
	 */
	public java.lang.String getZZXL() {
		return getStr("ZZXL");
	}

	/**
	 * 院校系专业（最高在职学历）
	 */
	public void setZZXLXX(java.lang.String ZZXLXX) {
		set("ZZXLXX", ZZXLXX);
	}
	
	/**
	 * 院校系专业（最高在职学历）
	 */
	public java.lang.String getZZXLXX() {
		return getStr("ZZXLXX");
	}

	/**
	 * 最高在职学位
	 */
	public void setZZXW(java.lang.String ZZXW) {
		set("ZZXW", ZZXW);
	}
	
	/**
	 * 最高在职学位
	 */
	public java.lang.String getZZXW() {
		return getStr("ZZXW");
	}

	/**
	 * 院校系专业（最高在职学位）
	 */
	public void setZZXWXX(java.lang.String ZZXWXX) {
		set("ZZXWXX", ZZXWXX);
	}
	
	/**
	 * 院校系专业（最高在职学位）
	 */
	public java.lang.String getZZXWXX() {
		return getStr("ZZXWXX");
	}

	/**
	 * 公务员登记时间
	 */
	public void setA0155(java.util.Date A0155) {
		set("A0155", A0155);
	}
	
	/**
	 * 公务员登记时间
	 */
	public java.util.Date getA0155() {
		return get("A0155");
	}

	/**
	 * 年龄1
	 */
	public void setAGE(java.lang.Integer AGE) {
		set("AGE", AGE);
	}
	
	/**
	 * 年龄1
	 */
	public java.lang.Integer getAGE() {
		return getInt("AGE");
	}

	/**
	 * 计算年龄时间1
	 */
	public void setJSNLSJ(java.util.Date JSNLSJ) {
		set("JSNLSJ", JSNLSJ);
	}
	
	/**
	 * 计算年龄时间1
	 */
	public java.util.Date getJSNLSJ() {
		return get("JSNLSJ");
	}

	/**
	 * 排序号1
	 */
	public void setRESULTSORTID(java.lang.Integer RESULTSORTID) {
		set("RESULTSORTID", RESULTSORTID);
	}
	
	/**
	 * 排序号1
	 */
	public java.lang.Integer getRESULTSORTID() {
		return getInt("RESULTSORTID");
	}

	/**
	 * 填表时间
	 */
	public void setTBSJ(java.util.Date TBSJ) {
		set("TBSJ", TBSJ);
	}
	
	/**
	 * 填表时间
	 */
	public java.util.Date getTBSJ() {
		return get("TBSJ");
	}

	/**
	 * 修改时间1
	 */
	public void setXGSJ(java.util.Date XGSJ) {
		set("XGSJ", XGSJ);
	}
	
	/**
	 * 修改时间1
	 */
	public java.util.Date getXGSJ() {
		return get("XGSJ");
	}

	/**
	 * 排序字段1
	 */
	public void setSORTID(java.lang.Integer SORTID) {
		set("SORTID", SORTID);
	}
	
	/**
	 * 排序字段1
	 */
	public java.lang.Integer getSORTID() {
		return getInt("SORTID");
	}

	/**
	 * 该人在基层工作的年月   将年月计算成月份存储
	 */
	public void setA0194(java.math.BigDecimal A0194) {
		set("A0194", A0194);
	}
	
	/**
	 * 该人在基层工作的年月   将年月计算成月份存储
	 */
	public java.math.BigDecimal getA0194() {
		return get("A0194");
	}

	/**
	 * 职级（职级并行）
	 */
	public void setA0192E(java.lang.String A0192E) {
		set("A0192E", A0192E);
	}
	
	/**
	 * 职级（职级并行）
	 */
	public java.lang.String getA0192E() {
		return getStr("A0192E");
	}

	/**
	 * 工作单位及职务全称对应的，任职时间
	 */
	public void setA0192F(java.lang.String A0192F) {
		set("A0192F", A0192F);
	}
	
	/**
	 * 工作单位及职务全称对应的，任职时间
	 */
	public java.lang.String getA0192F() {
		return getStr("A0192F");
	}

	/**
	 * 最高机构
	 */
	public void setTORGID(java.lang.String TORGID) {
		set("TORGID", TORGID);
	}
	
	/**
	 * 最高机构
	 */
	public java.lang.String getTORGID() {
		return getStr("TORGID");
	}

	/**
	 * 最高机构所在机体内排序
	 */
	public void setTORDER(java.lang.String TORDER) {
		set("TORDER", TORDER);
	}
	
	/**
	 * 最高机构所在机体内排序
	 */
	public java.lang.String getTORDER() {
		return getStr("TORDER");
	}

	public void setZGXL(java.lang.String ZGXL) {
		set("ZGXL", ZGXL);
	}
	
	public java.lang.String getZGXL() {
		return getStr("ZGXL");
	}

	public void setZGXLXX(java.lang.String ZGXLXX) {
		set("ZGXLXX", ZGXLXX);
	}
	
	public java.lang.String getZGXLXX() {
		return getStr("ZGXLXX");
	}

	public void setZGXW(java.lang.String ZGXW) {
		set("ZGXW", ZGXW);
	}
	
	public java.lang.String getZGXW() {
		return getStr("ZGXW");
	}

	public void setZGXWXX(java.lang.String ZGXWXX) {
		set("ZGXWXX", ZGXWXX);
	}
	
	public java.lang.String getZGXWXX() {
		return getStr("ZGXWXX");
	}

	public void setTCSJSHOW(java.lang.String TCSJSHOW) {
		set("TCSJSHOW", TCSJSHOW);
	}
	
	public java.lang.String getTCSJSHOW() {
		return getStr("TCSJSHOW");
	}

	/**
	 * 退出方式
	 */
	public void setTCFSSHOW(java.lang.String TCFSSHOW) {
		set("TCFSSHOW", TCFSSHOW);
	}
	
	/**
	 * 退出方式
	 */
	public java.lang.String getTCFSSHOW() {
		return getStr("TCFSSHOW");
	}

	/**
	 * 全日制综述
	 */
	public void setQRZZS(java.lang.String QRZZS) {
		set("QRZZS", QRZZS);
	}
	
	/**
	 * 全日制综述
	 */
	public java.lang.String getQRZZS() {
		return getStr("QRZZS");
	}

	/**
	 * 在职综述
	 */
	public void setZZZS(java.lang.String ZZZS) {
		set("ZZZS", ZZZS);
	}
	
	/**
	 * 在职综述
	 */
	public java.lang.String getZZZS() {
		return getStr("ZZZS");
	}

	/**
	 * 公务员登记号
	 */
	public void setA0155A(java.lang.String A0155A) {
		set("A0155A", A0155A);
	}
	
	/**
	 * 公务员登记号
	 */
	public java.lang.String getA0155A() {
		return getStr("A0155A");
	}

	/**
	 * 任职时间字符串(对应全息系统)
	 */
	public void setA0243Str(java.lang.String A0243Str) {
		set("A0243Str", A0243Str);
	}
	
	/**
	 * 任职时间字符串(对应全息系统)
	 */
	public java.lang.String getA0243Str() {
		return getStr("A0243Str");
	}

	/**
	 * 任职岗位代码(对应全息系统)
	 */
	public void setA01Z101(java.lang.String A01Z101) {
		set("A01Z101", A01Z101);
	}
	
	/**
	 * 任职岗位代码(对应全息系统)
	 */
	public java.lang.String getA01Z101() {
		return getStr("A01Z101");
	}

	/**
	 * 任职说明(对应全息系统)
	 */
	public void setA01Z102(java.lang.String A01Z102) {
		set("A01Z102", A01Z102);
	}
	
	/**
	 * 任职说明(对应全息系统)
	 */
	public java.lang.String getA01Z102() {
		return getStr("A01Z102");
	}

	/**
	 * 流动方式(对应全息系统)
	 */
	public void setA01Z103(java.lang.String A01Z103) {
		set("A01Z103", A01Z103);
	}
	
	/**
	 * 流动方式(对应全息系统)
	 */
	public java.lang.String getA01Z103() {
		return getStr("A01Z103");
	}

	/**
	 * 工作熟悉领域(对应全息系统)
	 */
	public void setA01Z104(java.lang.String A01Z104) {
		set("A01Z104", A01Z104);
	}
	
	/**
	 * 工作熟悉领域(对应全息系统)
	 */
	public java.lang.String getA01Z104() {
		return getStr("A01Z104");
	}

	/**
	 * 历任重要职务标示(对应全息系统)
	 */
	public void setA01Z105(java.lang.String A01Z105) {
		set("A01Z105", A01Z105);
	}
	
	/**
	 * 历任重要职务标示(对应全息系统)
	 */
	public java.lang.String getA01Z105() {
		return getStr("A01Z105");
	}

	/**
	 * 熟悉领域
	 */
	public void setFamiliar(java.lang.String familiar) {
		set("familiar", familiar);
	}
	
	/**
	 * 熟悉领域
	 */
	public java.lang.String getFamiliar() {
		return getStr("familiar");
	}

	/**
	 * 历任经历
	 */
	public void setLiren(java.lang.String liren) {
		set("liren", liren);
	}
	
	/**
	 * 历任经历
	 */
	public java.lang.String getLiren() {
		return getStr("liren");
	}

	/**
	 * 人员最近考核时间(用于分析查询)
	 */
	public void setA01Z106(java.util.Date A01Z106) {
		set("A01Z106", A01Z106);
	}
	
	/**
	 * 人员最近考核时间(用于分析查询)
	 */
	public java.util.Date getA01Z106() {
		return get("A01Z106");
	}

	/**
	 * 是否近3年考核优秀
	 */
	public void setA01Z107(java.lang.String A01Z107) {
		set("A01Z107", A01Z107);
	}
	
	/**
	 * 是否近3年考核优秀
	 */
	public java.lang.String getA01Z107() {
		return getStr("A01Z107");
	}

	/**
	 * 是否近5年考核优秀
	 */
	public void setA01Z108(java.lang.String A01Z108) {
		set("A01Z108", A01Z108);
	}
	
	/**
	 * 是否近5年考核优秀
	 */
	public java.lang.String getA01Z108() {
		return getStr("A01Z108");
	}

	public void setA0123(java.lang.String A0123) {
		set("A0123", A0123);
	}
	
	public java.lang.String getA0123() {
		return getStr("A0123");
	}

}
