package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA05<M extends BaseA05<M>> extends Model<M> implements IBean {

	/**
	 * 人员统一标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员统一标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 主键
	 */
	public void setA0500(java.lang.String A0500) {
		set("A0500", A0500);
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getA0500() {
		return getStr("A0500");
	}

	/**
	 * 类别（职务层次、职级）(0--职务层次；1--职级)
	 */
	public void setA0531(java.lang.String A0531) {
		set("A0531", A0531);
	}
	
	/**
	 * 类别（职务层次、职级）(0--职务层次；1--职级)
	 */
	public java.lang.String getA0531() {
		return getStr("A0531");
	}

	/**
	 * 职务层次（职级层次）
	 */
	public void setA0501B(java.lang.String A0501B) {
		set("A0501B", A0501B);
	}
	
	/**
	 * 职务层次（职级层次）
	 */
	public java.lang.String getA0501B() {
		return getStr("A0501B");
	}

	/**
	 * 批准日期
	 */
	public void setA0504(java.util.Date A0504) {
		set("A0504", A0504);
	}
	
	/**
	 * 批准日期
	 */
	public java.util.Date getA0504() {
		return get("A0504");
	}

	public void setA0511(java.lang.String A0511) {
		set("A0511", A0511);
	}
	
	public java.lang.String getA0511() {
		return getStr("A0511");
	}

	/**
	 * 终止日期
	 */
	public void setA0517(java.util.Date A0517) {
		set("A0517", A0517);
	}
	
	/**
	 * 终止日期
	 */
	public java.util.Date getA0517() {
		return get("A0517");
	}

	/**
	 * 状态--在任：1，以免：0
	 */
	public void setA0524(java.lang.String A0524) {
		set("A0524", A0524);
	}
	
	/**
	 * 状态--在任：1，以免：0
	 */
	public java.lang.String getA0524() {
		return getStr("A0524");
	}

	/**
	 * 输出状态：1-输出，0：不输出
	 */
	public void setA0525(java.lang.String A0525) {
		set("A0525", A0525);
	}
	
	/**
	 * 输出状态：1-输出，0：不输出
	 */
	public java.lang.String getA0525() {
		return getStr("A0525");
	}

	public void setA0528B(java.lang.String A0528B) {
		set("A0528B", A0528B);
	}
	
	public java.lang.String getA0528B() {
		return getStr("A0528B");
	}

	public void setA0530(java.lang.String A0530) {
		set("A0530", A0530);
	}
	
	public java.lang.String getA0530() {
		return getStr("A0530");
	}

	public void setA0532(java.lang.String A0532) {
		set("A0532", A0532);
	}
	
	public java.lang.String getA0532() {
		return getStr("A0532");
	}

}
