package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOperateLog<M extends BaseOperateLog<M>> extends Model<M> implements IBean {

	/**
	 * 主键UUID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 主键UUID
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 操作人员账户
	 */
	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	/**
	 * 操作人员账户
	 */
	public java.lang.String getAccount() {
		return getStr("account");
	}

	/**
	 * 0是增加 1是修改 2删除 不能为null
	 */
	public void setOperate(java.lang.Integer operate) {
		set("operate", operate);
	}
	
	/**
	 * 0是增加 1是修改 2删除 不能为null
	 */
	public java.lang.Integer getOperate() {
		return getInt("operate");
	}

	/**
	 * 表名不能为null
	 */
	public void setTableName(java.lang.String tableName) {
		set("tableName", tableName);
	}
	
	/**
	 * 表名不能为null
	 */
	public java.lang.String getTableName() {
		return getStr("tableName");
	}

	/**
	 * sql语句,不能为null
	 */
	public void setSql(java.lang.String sql) {
		set("sql", sql);
	}
	
	/**
	 * sql语句,不能为null
	 */
	public java.lang.String getSql() {
		return getStr("sql");
	}

	/**
	 * 参数,默认是 json数组
	 */
	public void setArgs(java.lang.String args) {
		set("args", args);
	}
	
	/**
	 * 参数,默认是 json数组
	 */
	public java.lang.String getArgs() {
		return getStr("args");
	}

	/**
	 * 创建时间不能为null
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间不能为null
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
