package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWzAnnualDuty<M extends BaseWzAnnualDuty<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 人员标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 履职时间
	 */
	public void setDutyTime(java.util.Date dutyTime) {
		set("dutyTime", dutyTime);
	}
	
	/**
	 * 履职时间
	 */
	public java.util.Date getDutyTime() {
		return get("dutyTime");
	}

	/**
	 * 岗位工作情况
	 */
	public void setJobInfo(java.lang.String jobInfo) {
		set("jobInfo", jobInfo);
	}
	
	/**
	 * 岗位工作情况
	 */
	public java.lang.String getJobInfo() {
		return getStr("jobInfo");
	}

	/**
	 * 参政议政情况
	 */
	public void setPolitical(java.lang.String political) {
		set("political", political);
	}
	
	/**
	 * 参政议政情况
	 */
	public java.lang.String getPolitical() {
		return getStr("political");
	}

	/**
	 * 参加党派（团体）活动情况
	 */
	public void setActivities(java.lang.String activities) {
		set("activities", activities);
	}
	
	/**
	 * 参加党派（团体）活动情况
	 */
	public java.lang.String getActivities() {
		return getStr("activities");
	}

	/**
	 * 主要成绩
	 */
	public void setGrade(java.lang.String grade) {
		set("grade", grade);
	}
	
	/**
	 * 主要成绩
	 */
	public java.lang.String getGrade() {
		return getStr("grade");
	}

	/**
	 * 附件
	 */
	public void setFiles(java.lang.String files) {
		set("files", files);
	}
	
	/**
	 * 附件
	 */
	public java.lang.String getFiles() {
		return getStr("files");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
