package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysOperateLog<M extends BaseSysOperateLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	public java.lang.String getAccount() {
		return getStr("account");
	}

	public void setOperate(java.lang.String operate) {
		set("operate", operate);
	}
	
	public java.lang.String getOperate() {
		return getStr("operate");
	}

	public void setTableName(java.lang.String tableName) {
		set("tableName", tableName);
	}
	
	public java.lang.String getTableName() {
		return getStr("tableName");
	}

	public void setSql(java.lang.String sql) {
		set("sql", sql);
	}
	
	public java.lang.String getSql() {
		return getStr("sql");
	}

	public void setArgs(java.lang.String args) {
		set("args", args);
	}
	
	public java.lang.String getArgs() {
		return getStr("args");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
