package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUploadInfo<M extends BaseUploadInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 唯一标示
	 */
	public void setKey(java.lang.String key) {
		set("key", key);
	}
	
	/**
	 * 唯一标示
	 */
	public java.lang.String getKey() {
		return getStr("key");
	}

	/**
	 * 人或单位id
	 */
	public void setDataId(java.lang.String dataId) {
		set("dataId", dataId);
	}
	
	/**
	 * 人或单位id
	 */
	public java.lang.String getDataId() {
		return getStr("dataId");
	}

	/**
	 * 时间
	 */
	public void setDataTime(java.util.Date dataTime) {
		set("dataTime", dataTime);
	}
	
	/**
	 * 时间
	 */
	public java.util.Date getDataTime() {
		return get("dataTime");
	}

	/**
	 * 上传文件的名称
	 */
	public void setFileName(java.lang.String fileName) {
		set("fileName", fileName);
	}
	
	/**
	 * 上传文件的名称
	 */
	public java.lang.String getFileName() {
		return getStr("fileName");
	}

	/**
	 * 上传文件的url
	 */
	public void setFileUrl(java.lang.String fileUrl) {
		set("fileUrl", fileUrl);
	}
	
	/**
	 * 上传文件的url
	 */
	public java.lang.String getFileUrl() {
		return getStr("fileUrl");
	}

	/**
	 * (1:巡视情况，2:一报告两评议，2:综合研判报告，4:班子述职述廉报告，5:工作报告，6:考察材料（人），7:档案专审表（人）单条，8:综合研判（人），9:信访（人）,10:经济审查（人），11:受处分情况（人）)
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * (1:巡视情况，2:一报告两评议，2:综合研判报告，4:班子述职述廉报告，5:工作报告，6:考察材料（人），7:档案专审表（人）单条，8:综合研判（人），9:信访（人）,10:经济审查（人），11:受处分情况（人）)
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 1:人 2:单位
	 */
	public void setTableType(java.lang.String tableType) {
		set("tableType", tableType);
	}
	
	/**
	 * 1:人 2:单位
	 */
	public java.lang.String getTableType() {
		return getStr("tableType");
	}

	/**
	 * 结论
	 */
	public void setConclusion(java.lang.String conclusion) {
		set("conclusion", conclusion);
	}
	
	/**
	 * 结论
	 */
	public java.lang.String getConclusion() {
		return getStr("conclusion");
	}

	/**
	 * 摘要
	 */
	public void setDigest(java.lang.String digest) {
		set("digest", digest);
	}
	
	/**
	 * 摘要
	 */
	public java.lang.String getDigest() {
		return getStr("digest");
	}

}
