package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTempJob<M extends BaseTempJob<M>> extends Model<M> implements IBean {

	/**
	 * id主键
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * id主键
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 人员id
	 */
	public void setMemId(java.lang.String memId) {
		set("memId", memId);
	}
	
	/**
	 * 人员id
	 */
	public java.lang.String getMemId() {
		return getStr("memId");
	}

	/**
	 * 类型编码,参照字典表CDGZ,不能为null
	 */
	public void setTypeCode(java.lang.String typeCode) {
		set("typeCode", typeCode);
	}
	
	/**
	 * 类型编码,参照字典表CDGZ,不能为null
	 */
	public java.lang.String getTypeCode() {
		return getStr("typeCode");
	}

	/**
	 * 类型名称,参照字典表CDGZ,不能为null
	 */
	public void setTypeName(java.lang.String typeName) {
		set("typeName", typeName);
	}
	
	/**
	 * 类型名称,参照字典表CDGZ,不能为null
	 */
	public java.lang.String getTypeName() {
		return getStr("typeName");
	}

	/**
	 * 挂职开始时间,不能为null
	 */
	public void setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
	}
	
	/**
	 * 挂职开始时间,不能为null
	 */
	public java.util.Date getStartTime() {
		return get("startTime");
	}

	/**
	 * 挂职结束时间,不能为null
	 */
	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}
	
	/**
	 * 挂职结束时间,不能为null
	 */
	public java.util.Date getEndTime() {
		return get("endTime");
	}

	/**
	 * 挂职单位
	 */
	public void setJobUnit(java.lang.String jobUnit) {
		set("jobUnit", jobUnit);
	}
	
	/**
	 * 挂职单位
	 */
	public java.lang.String getJobUnit() {
		return getStr("jobUnit");
	}

	/**
	 * 职务
	 */
	public void setJob(java.lang.String job) {
		set("job", job);
	}
	
	/**
	 * 职务
	 */
	public java.lang.String getJob() {
		return getStr("job");
	}

	/**
	 * 鉴定情况
	 */
	public void setJobCase(java.lang.String jobCase) {
		set("jobCase", jobCase);
	}
	
	/**
	 * 鉴定情况
	 */
	public java.lang.String getJobCase() {
		return getStr("jobCase");
	}

	/**
	 * 是否删除,0 未删除 1 删除 默认为0
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("isDelete", isDelete);
	}
	
	/**
	 * 是否删除,0 未删除 1 删除 默认为0
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("isDelete");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
