package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

	/**
	 * 角色id,uuid,不能为null
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 角色id,uuid,不能为null
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 角色名称,不能为null
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 角色名称,不能为null
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 权限码1001011,不能为null,默认权限
	 */
	public void setPermission(java.lang.String permission) {
		set("permission", permission);
	}
	
	/**
	 * 权限码1001011,不能为null,默认权限
	 */
	public java.lang.String getPermission() {
		return getStr("permission");
	}

	/**
	 * 是否是内置角色,0非内置,用户自定义角色,1内置角色
	 */
	public void setIsBuiltIn(java.lang.Integer isBuiltIn) {
		set("isBuiltIn", isBuiltIn);
	}
	
	/**
	 * 是否是内置角色,0非内置,用户自定义角色,1内置角色
	 */
	public java.lang.Integer getIsBuiltIn() {
		return getInt("isBuiltIn");
	}

	/**
	 * 有效时间,内置角色有效时间为永久值为null
	 */
	public void setValidTime(java.util.Date validTime) {
		set("validTime", validTime);
	}
	
	/**
	 * 有效时间,内置角色有效时间为永久值为null
	 */
	public java.util.Date getValidTime() {
		return get("validTime");
	}

	/**
	 * 创建时间,默认不为null
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间,默认不为null
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 更新时间,默认为createTime,不能为null
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间,默认为createTime,不能为null
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	/**
	 * 角色层级码
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 角色层级码
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 创建者,角色account
	 */
	public void setCreate(java.lang.String create) {
		set("create", create);
	}
	
	/**
	 * 创建者,角色account
	 */
	public java.lang.String getCreate() {
		return getStr("create");
	}

}
