package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA53<M extends BaseA53<M>> extends Model<M> implements IBean {

	/**
	 * 人员统一标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员统一标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 拟任免信息ID
	 */
	public void setA5300(java.lang.String A5300) {
		set("A5300", A5300);
	}
	
	/**
	 * 拟任免信息ID
	 */
	public java.lang.String getA5300() {
		return getStr("A5300");
	}

	public void setA5304(java.lang.String A5304) {
		set("A5304", A5304);
	}
	
	public java.lang.String getA5304() {
		return getStr("A5304");
	}

	public void setA5315(java.lang.String A5315) {
		set("A5315", A5315);
	}
	
	public java.lang.String getA5315() {
		return getStr("A5315");
	}

	public void setA5317(java.lang.String A5317) {
		set("A5317", A5317);
	}
	
	public java.lang.String getA5317() {
		return getStr("A5317");
	}

	public void setA5319(java.lang.String A5319) {
		set("A5319", A5319);
	}
	
	public java.lang.String getA5319() {
		return getStr("A5319");
	}

	/**
	 * 计算年龄时间
	 */
	public void setA5321(java.lang.String A5321) {
		set("A5321", A5321);
	}
	
	/**
	 * 计算年龄时间
	 */
	public java.lang.String getA5321() {
		return getStr("A5321");
	}

	/**
	 * 填表时间
	 */
	public void setA5323(java.lang.String A5323) {
		set("A5323", A5323);
	}
	
	/**
	 * 填表时间
	 */
	public java.lang.String getA5323() {
		return getStr("A5323");
	}

	/**
	 * 填表人
	 */
	public void setA5327(java.lang.String A5327) {
		set("A5327", A5327);
	}
	
	/**
	 * 填表人
	 */
	public java.lang.String getA5327() {
		return getStr("A5327");
	}

	/**
	 * 用户ID
	 */
	public void setA5399(java.lang.String A5399) {
		set("A5399", A5399);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.String getA5399() {
		return getStr("A5399");
	}

	/**
	 * 标识
	 */
	public void setUPDATED(java.lang.String UPDATED) {
		set("UPDATED", UPDATED);
	}
	
	/**
	 * 标识
	 */
	public java.lang.String getUPDATED() {
		return getStr("UPDATED");
	}

}
