package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA71<M extends BaseA71<M>> extends Model<M> implements IBean {

	/**
	 * 人员统一标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员统一标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 主键
	 */
	public void setA7100(java.lang.String A7100) {
		set("A7100", A7100);
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getA7100() {
		return getStr("A7100");
	}

	public void setA7101(java.lang.String A7101) {
		set("A7101", A7101);
	}
	
	public java.lang.String getA7101() {
		return getStr("A7101");
	}

}
