package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA57Temp<M extends BaseA57Temp<M>> extends Model<M> implements IBean {

	public void setImpId(java.lang.String impId) {
		set("impId", impId);
	}
	
	public java.lang.String getImpId() {
		return getStr("impId");
	}

	/**
	 * 人员统一标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员统一标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 照片？
	 */
	public void setA5714(java.lang.String A5714) {
		set("A5714", A5714);
	}
	
	/**
	 * 照片？
	 */
	public java.lang.String getA5714() {
		return getStr("A5714");
	}

	/**
	 * 标识
	 */
	public void setUPDATED(java.lang.String UPDATED) {
		set("UPDATED", UPDATED);
	}
	
	/**
	 * 标识
	 */
	public java.lang.String getUPDATED() {
		return getStr("UPDATED");
	}

	/**
	 * 照片数据--删除
	 */
	public void setPHOTODATA(java.lang.String PHOTODATA) {
		set("PHOTODATA", PHOTODATA);
	}
	
	/**
	 * 照片数据--删除
	 */
	public java.lang.String getPHOTODATA() {
		return getStr("PHOTODATA");
	}

	public void setPHOTONAME(java.lang.String PHOTONAME) {
		set("PHOTONAME", PHOTONAME);
	}
	
	public java.lang.String getPHOTONAME() {
		return getStr("PHOTONAME");
	}

	/**
	 * 照片类型？
	 */
	public void setPHOTSTYPE(java.lang.String PHOTSTYPE) {
		set("PHOTSTYPE", PHOTSTYPE);
	}
	
	/**
	 * 照片类型？
	 */
	public java.lang.String getPHOTSTYPE() {
		return getStr("PHOTSTYPE");
	}

	/**
	 * 照片路径 如 A/C/？？
	 */
	public void setPHOTOPATH(java.lang.String PHOTOPATH) {
		set("PHOTOPATH", PHOTOPATH);
	}
	
	/**
	 * 照片路径 如 A/C/？？
	 */
	public java.lang.String getPHOTOPATH() {
		return getStr("PHOTOPATH");
	}

	/**
	 * 照片状态 0：无照片1：存在照片2：照片存在重复3：照片过小4：其他异常
	 */
	public void setPicstatus(java.lang.String picstatus) {
		set("picstatus", picstatus);
	}
	
	/**
	 * 照片状态 0：无照片1：存在照片2：照片存在重复3：照片过小4：其他异常
	 */
	public java.lang.String getPicstatus() {
		return getStr("picstatus");
	}

	/**
	 * 上传文件类型：1（lrm,lrmx,pic）,2（zip）
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 上传文件类型：1（lrm,lrmx,pic）,2（zip）
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

}
