package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSelectCadre<M extends BaseSelectCadre<M>> extends Model<M> implements IBean {

	/**
	 * 唯一标示
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 唯一标示
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 人员唯一标示
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员唯一标示
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 成为选调生的时间
	 */
	public void setSelectDate(java.util.Date selectDate) {
		set("selectDate", selectDate);
	}
	
	/**
	 * 成为选调生的时间
	 */
	public java.util.Date getSelectDate() {
		return get("selectDate");
	}

	/**
	 * 成为选调生的年份(那一届)
	 */
	public void setSelectyear(java.lang.Integer selectyear) {
		set("selectyear", selectyear);
	}
	
	/**
	 * 成为选调生的年份(那一届)
	 */
	public java.lang.Integer getSelectyear() {
		return getInt("selectyear");
	}

	/**
	 * 选调时的单位
	 */
	public void setSelectUnit(java.lang.String selectUnit) {
		set("selectUnit", selectUnit);
	}
	
	/**
	 * 选调时的单位
	 */
	public java.lang.String getSelectUnit() {
		return getStr("selectUnit");
	}

	/**
	 * 选调时的职务
	 */
	public void setSelectJob(java.lang.String selectJob) {
		set("selectJob", selectJob);
	}
	
	/**
	 * 选调时的职务
	 */
	public java.lang.String getSelectJob() {
		return getStr("selectJob");
	}

	/**
	 * 是否发生变动 1是 0否
	 */
	public void setIsChange(java.lang.Integer isChange) {
		set("isChange", isChange);
	}
	
	/**
	 * 是否发生变动 1是 0否
	 */
	public java.lang.Integer getIsChange() {
		return getInt("isChange");
	}

	/**
	 * 变动时间
	 */
	public void setChangeTime(java.util.Date changeTime) {
		set("changeTime", changeTime);
	}
	
	/**
	 * 变动时间
	 */
	public java.util.Date getChangeTime() {
		return get("changeTime");
	}

	/**
	 * 变动原因代码
	 */
	public void setChangeReason(java.lang.String changeReason) {
		set("changeReason", changeReason);
	}
	
	/**
	 * 变动原因代码
	 */
	public java.lang.String getChangeReason() {
		return getStr("changeReason");
	}

	/**
	 * 变动备注
	 */
	public void setChangeRemark(java.lang.String changeRemark) {
		set("changeRemark", changeRemark);
	}
	
	/**
	 * 变动备注
	 */
	public java.lang.String getChangeRemark() {
		return getStr("changeRemark");
	}

	/**
	 * 排序
	 */
	public void setSortId(java.lang.Long sortId) {
		set("sortId", sortId);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Long getSortId() {
		return getLong("sortId");
	}

}
