package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA37<M extends BaseA37<M>> extends Model<M> implements IBean {

	/**
	 * 人员统一标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员统一标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 办公地址   等
	 */
	public void setA3701(java.lang.String A3701) {
		set("A3701", A3701);
	}
	
	/**
	 * 办公地址   等
	 */
	public java.lang.String getA3701() {
		return getStr("A3701");
	}

	/**
	 * 办公电话   等
	 */
	public void setA3707A(java.lang.String A3707A) {
		set("A3707A", A3707A);
	}
	
	/**
	 * 办公电话   等
	 */
	public java.lang.String getA3707A() {
		return getStr("A3707A");
	}

	/**
	 * 移动电话   等
	 */
	public void setA3707C(java.lang.String A3707C) {
		set("A3707C", A3707C);
	}
	
	/**
	 * 移动电话   等
	 */
	public java.lang.String getA3707C() {
		return getStr("A3707C");
	}

	/**
	 * 秘书电话   等
	 */
	public void setA3707E(java.lang.String A3707E) {
		set("A3707E", A3707E);
	}
	
	/**
	 * 秘书电话   等
	 */
	public java.lang.String getA3707E() {
		return getStr("A3707E");
	}

	/**
	 * 住宅电话   等
	 */
	public void setA3707B(java.lang.String A3707B) {
		set("A3707B", A3707B);
	}
	
	/**
	 * 住宅电话   等
	 */
	public java.lang.String getA3707B() {
		return getStr("A3707B");
	}

	/**
	 * 电子邮箱   等
	 */
	public void setA3708(java.lang.String A3708) {
		set("A3708", A3708);
	}
	
	/**
	 * 电子邮箱   等
	 */
	public java.lang.String getA3708() {
		return getStr("A3708");
	}

	/**
	 * 家庭住址   等
	 */
	public void setA3711(java.lang.String A3711) {
		set("A3711", A3711);
	}
	
	/**
	 * 家庭住址   等
	 */
	public java.lang.String getA3711() {
		return getStr("A3711");
	}

	/**
	 * 住址邮政编码   等
	 */
	public void setA3714(java.lang.String A3714) {
		set("A3714", A3714);
	}
	
	/**
	 * 住址邮政编码   等
	 */
	public java.lang.String getA3714() {
		return getStr("A3714");
	}

	/**
	 * 标识   少
	 */
	public void setUPDATED(java.lang.String UPDATED) {
		set("UPDATED", UPDATED);
	}
	
	/**
	 * 标识   少
	 */
	public java.lang.String getUPDATED() {
		return getStr("UPDATED");
	}

}
