package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseB01<M extends BaseB01<M>> extends Model<M> implements IBean {

	/**
	 * 机构名称
	 */
	public void setB0101(java.lang.String B0101) {
		set("B0101", B0101);
	}
	
	/**
	 * 机构名称
	 */
	public java.lang.String getB0101() {
		return getStr("B0101");
	}

	/**
	 * 机构简称
	 */
	public void setB0104(java.lang.String B0104) {
		set("B0104", B0104);
	}
	
	/**
	 * 机构简称
	 */
	public java.lang.String getB0104() {
		return getStr("B0104");
	}

	/**
	 * 机构简拼
	 */
	public void setB0107(java.lang.String B0107) {
		set("B0107", B0107);
	}
	
	/**
	 * 机构简拼
	 */
	public java.lang.String getB0107() {
		return getStr("B0107");
	}

	/**
	 * 机构主键
	 */
	public void setB0111(java.lang.String B0111) {
		set("B0111", B0111);
	}
	
	/**
	 * 机构主键
	 */
	public java.lang.String getB0111() {
		return getStr("B0111");
	}

	/**
	 * 法人单位编码(机构分组编码)   少
	 */
	public void setB0114(java.lang.String B0114) {
		set("B0114", B0114);
	}
	
	/**
	 * 法人单位编码(机构分组编码)   少
	 */
	public java.lang.String getB0114() {
		return getStr("B0114");
	}

	/**
	 * 机构所在政区 ZB01
	 */
	public void setB0117(java.lang.String B0117) {
		set("B0117", B0117);
	}
	
	/**
	 * 机构所在政区 ZB01
	 */
	public java.lang.String getB0117() {
		return getStr("B0117");
	}

	/**
	 * 上级单位id
	 */
	public void setB0121(java.lang.String B0121) {
		set("B0121", B0121);
	}
	
	/**
	 * 上级单位id
	 */
	public java.lang.String getB0121() {
		return getStr("B0121");
	}

	/**
	 * 单位隶属关系 ZB87
	 */
	public void setB0124(java.lang.String B0124) {
		set("B0124", B0124);
	}
	
	/**
	 * 单位隶属关系 ZB87
	 */
	public java.lang.String getB0124() {
		return getStr("B0124");
	}

	/**
	 * 机构级别 ZB03   等
	 */
	public void setB0127(java.lang.String B0127) {
		set("B0127", B0127);
	}
	
	/**
	 * 机构级别 ZB03   等
	 */
	public java.lang.String getB0127() {
		return getStr("B0127");
	}

	/**
	 * 机构性质类别 ZB04 
	 */
	public void setB0131(java.lang.String B0131) {
		set("B0131", B0131);
	}
	
	/**
	 * 机构性质类别 ZB04 
	 */
	public java.lang.String getB0131() {
		return getStr("B0131");
	}

	/**
	 * 统计单位编码 （未用）   少
	 */
	public void setB0140(java.lang.String B0140) {
		set("B0140", B0140);
	}
	
	/**
	 * 统计单位编码 （未用）   少
	 */
	public java.lang.String getB0140() {
		return getStr("B0140");
	}

	/**
	 * 统计单位上级编码 （未用）   少
	 */
	public void setB0141(java.lang.String B0141) {
		set("B0141", B0141);
	}
	
	/**
	 * 统计单位上级编码 （未用）   少
	 */
	public java.lang.String getB0141() {
		return getStr("B0141");
	}

	/**
	 * 单位排序 （未用）   少
	 */
	public void setB0142(java.lang.Integer B0142) {
		set("B0142", B0142);
	}
	
	/**
	 * 单位排序 （未用）   少
	 */
	public java.lang.Integer getB0142() {
		return getInt("B0142");
	}

	/**
	 * 统计单位选择 （未用）   少
	 */
	public void setB0143(java.lang.String B0143) {
		set("B0143", B0143);
	}
	
	/**
	 * 统计单位选择 （未用）   少
	 */
	public java.lang.String getB0143() {
		return getStr("B0143");
	}

	/**
	 * 内设领导职数
	 */
	public void setB0150(java.lang.Integer B0150) {
		set("B0150", B0150);
	}
	
	/**
	 * 内设领导职数
	 */
	public java.lang.Integer getB0150() {
		return getInt("B0150");
	}

	public void setB0180(java.lang.String B0180) {
		set("B0180", B0180);
	}
	
	public java.lang.String getB0180() {
		return getStr("B0180");
	}

	/**
	 * 正职领导职数
	 */
	public void setB0183(java.lang.Integer B0183) {
		set("B0183", B0183);
	}
	
	/**
	 * 正职领导职数
	 */
	public java.lang.Integer getB0183() {
		return getInt("B0183");
	}

	/**
	 * 副职领导职数
	 */
	public void setB0185(java.lang.Integer B0185) {
		set("B0185", B0185);
	}
	
	/**
	 * 副职领导职数
	 */
	public java.lang.Integer getB0185() {
		return getInt("B0185");
	}

	/**
	 * 同级正职非领导职数(无效)   少
	 */
	public void setB0188(java.lang.Integer B0188) {
		set("B0188", B0188);
	}
	
	/**
	 * 同级正职非领导职数(无效)   少
	 */
	public java.lang.Integer getB0188() {
		return getInt("B0188");
	}

	/**
	 * 同级副职非领导职数(无效)   少
	 */
	public void setB0189(java.lang.Integer B0189) {
		set("B0189", B0189);
	}
	
	/**
	 * 同级副职非领导职数(无效)   少
	 */
	public java.lang.Integer getB0189() {
		return getInt("B0189");
	}

	/**
	 * 内设机构正职领导职数(无效)   少
	 */
	public void setB0190(java.lang.Integer B0190) {
		set("B0190", B0190);
	}
	
	/**
	 * 内设机构正职领导职数(无效)   少
	 */
	public java.lang.Integer getB0190() {
		return getInt("B0190");
	}

	/**
	 * 法人单位(组织机构) （未用）   少
	 */
	public void setB0191(java.lang.String B0191) {
		set("B0191", B0191);
	}
	
	/**
	 * 法人单位(组织机构) （未用）   少
	 */
	public java.lang.String getB0191() {
		return getStr("B0191");
	}

	/**
	 * 内设副职领导职数(无效)   少
	 */
	public void setB0191A(java.lang.Integer B0191A) {
		set("B0191A", B0191A);
	}
	
	/**
	 * 内设副职领导职数(无效)   少
	 */
	public java.lang.Integer getB0191A() {
		return getInt("B0191A");
	}

	/**
	 * 内设机构正职非领导职数(无效)   少
	 */
	public void setB0192(java.lang.Integer B0192) {
		set("B0192", B0192);
	}
	
	/**
	 * 内设机构正职非领导职数(无效)   少
	 */
	public java.lang.Integer getB0192() {
		return getInt("B0192");
	}

	/**
	 * 内设机构副职非领导职数(无效)   少
	 */
	public void setB0193(java.lang.Integer B0193) {
		set("B0193", B0193);
	}
	
	/**
	 * 内设机构副职非领导职数(无效)   少
	 */
	public java.lang.Integer getB0193() {
		return getInt("B0193");
	}

	/**
	 * 机构类型 1法人单位 2内设机构 3机构分组 0领导机构
	 */
	public void setB0194(java.lang.String B0194) {
		set("B0194", B0194);
	}
	
	/**
	 * 机构类型 1法人单位 2内设机构 3机构分组 0领导机构
	 */
	public java.lang.String getB0194() {
		return getStr("B0194");
	}

	/**
	 * 导出标志 （未用）   少
	 */
	public void setB01TRANS(java.lang.Integer B01TRANS) {
		set("B01TRANS", B01TRANS);
	}
	
	/**
	 * 导出标志 （未用）   少
	 */
	public java.lang.Integer getB01TRANS() {
		return getInt("B01TRANS");
	}

	/**
	 * 同步标志 （未用）   少
	 */
	public void setB01IP(java.lang.String B01IP) {
		set("B01IP", B01IP);
	}
	
	/**
	 * 同步标志 （未用）   少
	 */
	public java.lang.String getB01IP() {
		return getStr("B01IP");
	}

	/**
	 * 行政编制数   等
	 */
	public void setB0227(java.lang.Integer B0227) {
		set("B0227", B0227);
	}
	
	/**
	 * 行政编制数   等
	 */
	public java.lang.Integer getB0227() {
		return getInt("B0227");
	}

	/**
	 * 事业编制数(参公)
	 */
	public void setB0232(java.lang.Integer B0232) {
		set("B0232", B0232);
	}
	
	/**
	 * 事业编制数(参公)
	 */
	public java.lang.Integer getB0232() {
		return getInt("B0232");
	}

	/**
	 * 事业编制数(其他)
	 */
	public void setB0233(java.lang.Integer B0233) {
		set("B0233", B0233);
	}
	
	/**
	 * 事业编制数(其他)
	 */
	public java.lang.Integer getB0233() {
		return getInt("B0233");
	}

	/**
	 * 排序字段   少
	 */
	public void setSORTID(java.lang.Integer SORTID) {
		set("SORTID", SORTID);
	}
	
	/**
	 * 排序字段   少
	 */
	public java.lang.Integer getSORTID() {
		return getInt("SORTID");
	}

	/**
	 *  （未用）1   少
	 */
	public void setUSED(java.lang.String USED) {
		set("USED", USED);
	}
	
	/**
	 *  （未用）1   少
	 */
	public java.lang.String getUSED() {
		return getStr("USED");
	}

	/**
	 * 校验标识：0-未校验或校验未通过，1-校验通过   少
	 */
	public void setUPDATED(java.lang.String UPDATED) {
		set("UPDATED", UPDATED);
	}
	
	/**
	 * 校验标识：0-未校验或校验未通过，1-校验通过   少
	 */
	public java.lang.String getUPDATED() {
		return getStr("UPDATED");
	}

	/**
	 * 创建人，为空表示非本系统创建？   少
	 */
	public void setCreateUser(java.lang.String createUser) {
		set("CREATE_USER", createUser);
	}
	
	/**
	 * 创建人，为空表示非本系统创建？   少
	 */
	public java.lang.String getCreateUser() {
		return getStr("CREATE_USER");
	}

	/**
	 * 创建时间？   少
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("CREATE_DATE", createDate);
	}
	
	/**
	 * 创建时间？   少
	 */
	public java.util.Date getCreateDate() {
		return get("CREATE_DATE");
	}

	/**
	 * 修改人？   少
	 */
	public void setUpdateUser(java.lang.String updateUser) {
		set("UPDATE_USER", updateUser);
	}
	
	/**
	 * 修改人？   少
	 */
	public java.lang.String getUpdateUser() {
		return getStr("UPDATE_USER");
	}

	/**
	 * 修改时间？   少
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("UPDATE_DATE", updateDate);
	}
	
	/**
	 * 修改时间？   少
	 */
	public java.util.Date getUpdateDate() {
		return get("UPDATE_DATE");
	}

	/**
	 * 状态 （未用）？   少
	 */
	public void setSTATUS(java.lang.String STATUS) {
		set("STATUS", STATUS);
	}
	
	/**
	 * 状态 （未用）？   少
	 */
	public java.lang.String getSTATUS() {
		return getStr("STATUS");
	}

	/**
	 * 参照公务员法管理审批时间
	 */
	public void setB0238(java.lang.String B0238) {
		set("B0238", B0238);
	}
	
	/**
	 * 参照公务员法管理审批时间
	 */
	public java.lang.String getB0238() {
		return getStr("B0238");
	}

	/**
	 * 参照公务员法管理审批文号
	 */
	public void setB0239(java.lang.String B0239) {
		set("B0239", B0239);
	}
	
	/**
	 * 参照公务员法管理审批文号
	 */
	public java.lang.String getB0239() {
		return getStr("B0239");
	}

	/**
	 * 其他编制数
	 */
	public void setB0234(java.lang.Integer B0234) {
		set("B0234", B0234);
	}
	
	/**
	 * 其他编制数
	 */
	public java.lang.Integer getB0234() {
		return getInt("B0234");
	}

	/**
	 * 政法专项编制数-已经取消
	 */
	public void setB0235(java.lang.Integer B0235) {
		set("B0235", B0235);
	}
	
	/**
	 * 政法专项编制数-已经取消
	 */
	public java.lang.Integer getB0235() {
		return getInt("B0235");
	}

	/**
	 * 工勤编制数
	 */
	public void setB0236(java.lang.Integer B0236) {
		set("B0236", B0236);
	}
	
	/**
	 * 工勤编制数
	 */
	public java.lang.Integer getB0236() {
		return getInt("B0236");
	}

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 1 删除 0 未删除
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("isDelete", isDelete);
	}
	
	/**
	 * 1 删除 0 未删除
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("isDelete");
	}

	/**
	 * 统一社会性用代码
	 */
	public void setB0194A(java.lang.String B0194A) {
		set("B0194A", B0194A);
	}
	
	/**
	 * 统一社会性用代码
	 */
	public java.lang.String getB0194A() {
		return getStr("B0194A");
	}

}
