package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA64<M extends BaseA64<M>> extends Model<M> implements IBean {

	/**
	 * 人员唯一标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员唯一标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 报考准考证号   等
	 */
	public void setA6401(java.lang.String A6401) {
		set("A6401", A6401);
	}
	
	/**
	 * 报考准考证号   等
	 */
	public java.lang.String getA6401() {
		return getStr("A6401");
	}

	/**
	 * 行政职业能力分数   等
	 */
	public void setA6402(java.lang.String A6402) {
		set("A6402", A6402);
	}
	
	/**
	 * 行政职业能力分数   等
	 */
	public java.lang.String getA6402() {
		return getStr("A6402");
	}

	/**
	 * 申论分数   等
	 */
	public void setA6403(java.lang.String A6403) {
		set("A6403", A6403);
	}
	
	/**
	 * 申论分数   等
	 */
	public java.lang.String getA6403() {
		return getStr("A6403");
	}

	/**
	 * 其他科目分数   等
	 */
	public void setA6404(java.lang.String A6404) {
		set("A6404", A6404);
	}
	
	/**
	 * 其他科目分数   等
	 */
	public java.lang.String getA6404() {
		return getStr("A6404");
	}

	/**
	 * 专业能力测试分数   等
	 */
	public void setA6405(java.lang.String A6405) {
		set("A6405", A6405);
	}
	
	/**
	 * 专业能力测试分数   等
	 */
	public java.lang.String getA6405() {
		return getStr("A6405");
	}

	/**
	 * 公共科目笔试成绩总分   等
	 */
	public void setA6406(java.lang.String A6406) {
		set("A6406", A6406);
	}
	
	/**
	 * 公共科目笔试成绩总分   等
	 */
	public java.lang.String getA6406() {
		return getStr("A6406");
	}

	/**
	 * 专业考试成绩   等
	 */
	public void setA6407(java.lang.String A6407) {
		set("A6407", A6407);
	}
	
	/**
	 * 专业考试成绩   等
	 */
	public java.lang.String getA6407() {
		return getStr("A6407");
	}

	/**
	 * 面试成绩   等
	 */
	public void setA6408(java.lang.String A6408) {
		set("A6408", A6408);
	}
	
	/**
	 * 面试成绩   等
	 */
	public java.lang.String getA6408() {
		return getStr("A6408");
	}

	/**
	 * 考试标识符
	 */
	public void setA6400(java.lang.String A6400) {
		set("A6400", A6400);
	}
	
	/**
	 * 考试标识符
	 */
	public java.lang.String getA6400() {
		return getStr("A6400");
	}

	/**
	 * 考试类别   少
	 */
	public void setA64TYPE(java.lang.String A64TYPE) {
		set("A64TYPE", A64TYPE);
	}
	
	/**
	 * 考试类别   少
	 */
	public java.lang.String getA64TYPE() {
		return getStr("A64TYPE");
	}

}
