package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSelectUniversity<M extends BaseSelectUniversity<M>> extends Model<M> implements IBean {

	/**
	 * 数据唯一标示
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 数据唯一标示
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 学校名称
	 */
	public void setUniversityName(java.lang.String universityName) {
		set("universityName", universityName);
	}
	
	/**
	 * 学校名称
	 */
	public java.lang.String getUniversityName() {
		return getStr("universityName");
	}

	/**
	 * 学校类型
	 */
	public void setUniversityType(java.lang.String universityType) {
		set("universityType", universityType);
	}
	
	/**
	 * 学校类型
	 */
	public java.lang.String getUniversityType() {
		return getStr("universityType");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 排序号
	 */
	public void setSortId(java.lang.Integer sortId) {
		set("sortId", sortId);
	}
	
	/**
	 * 排序号
	 */
	public java.lang.Integer getSortId() {
		return getInt("sortId");
	}

}
