package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYoungReport<M extends BaseYoungReport<M>> extends Model<M> implements IBean {

	/**
	 * 唯一标示
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 唯一标示
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 人员标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 考察时间
	 */
	public void setDataTime(java.util.Date dataTime) {
		set("dataTime", dataTime);
	}
	
	/**
	 * 考察时间
	 */
	public java.util.Date getDataTime() {
		return get("dataTime");
	}

	/**
	 * 考察说明
	 */
	public void setInspectExplain(java.lang.String inspectExplain) {
		set("inspectExplain", inspectExplain);
	}
	
	/**
	 * 考察说明
	 */
	public java.lang.String getInspectExplain() {
		return getStr("inspectExplain");
	}

	/**
	 * 文件名
	 */
	public void setFileName(java.lang.String fileName) {
		set("fileName", fileName);
	}
	
	/**
	 * 文件名
	 */
	public java.lang.String getFileName() {
		return getStr("fileName");
	}

	/**
	 * 文件路径
	 */
	public void setFileUrl(java.lang.String fileUrl) {
		set("fileUrl", fileUrl);
	}
	
	/**
	 * 文件路径
	 */
	public java.lang.String getFileUrl() {
		return getStr("fileUrl");
	}

	/**
	 * 文件路径（页面展示）
	 */
	public void setPdfUrl(java.lang.String pdfUrl) {
		set("pdfUrl", pdfUrl);
	}
	
	/**
	 * 文件路径（页面展示）
	 */
	public java.lang.String getPdfUrl() {
		return getStr("pdfUrl");
	}

	/**
	 * 1考察材料 2综合研判报告
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 1考察材料 2综合研判报告
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

}
