package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLoginLog<M extends BaseLoginLog<M>> extends Model<M> implements IBean {

	/**
	 * uuid不能为null
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * uuid不能为null
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 用户账号
	 */
	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	/**
	 * 用户账号
	 */
	public java.lang.String getAccount() {
		return getStr("account");
	}

	/**
	 * 用户密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 用户密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 用户登录IP
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * 用户登录IP
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}

	/**
	 * 0 登录失败 1登录成功
	 */
	public void setIsOK(java.lang.Integer isOK) {
		set("isOK", isOK);
	}
	
	/**
	 * 0 登录失败 1登录成功
	 */
	public java.lang.Integer getIsOK() {
		return getInt("isOK");
	}

	/**
	 * 创建时间不能为null
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间不能为null
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
