package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQxVerifyMsg<M extends BaseQxVerifyMsg<M>> extends Model<M> implements IBean {

	/**
	 * 唯一标示
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 唯一标示
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 人员的唯一标示与a01对应
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员的唯一标示与a01对应
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 错误错误信息
	 */
	public void setErrorMessage(java.lang.String errorMessage) {
		set("errorMessage", errorMessage);
	}
	
	/**
	 * 错误错误信息
	 */
	public java.lang.String getErrorMessage() {
		return getStr("errorMessage");
	}

	/**
	 * 警告信息
	 */
	public void setWarnMessage(java.lang.String warnMessage) {
		set("warnMessage", warnMessage);
	}
	
	/**
	 * 警告信息
	 */
	public java.lang.String getWarnMessage() {
		return getStr("warnMessage");
	}

	/**
	 * 校核时间
	 */
	public void setVerifyTime(java.util.Date verifyTime) {
		set("verifyTime", verifyTime);
	}
	
	/**
	 * 校核时间
	 */
	public java.util.Date getVerifyTime() {
		return get("verifyTime");
	}

	/**
	 * 机构id
	 */
	public void setOrgId(java.lang.String orgId) {
		set("orgId", orgId);
	}
	
	/**
	 * 机构id
	 */
	public java.lang.String getOrgId() {
		return getStr("orgId");
	}

	/**
	 * 1:是人员 2:机构
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 1:是人员 2:机构
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 身份证 (只有身份证重复才会存)
	 */
	public void setA0184(java.lang.String A0184) {
		set("A0184", A0184);
	}
	
	/**
	 * 身份证 (只有身份证重复才会存)
	 */
	public java.lang.String getA0184() {
		return getStr("A0184");
	}

}
