package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQxVerifyRule<M extends BaseQxVerifyRule<M>> extends Model<M> implements IBean {

	/**
	 * 数据唯一标示
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 数据唯一标示
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 校核规则名称
	 */
	public void setVerifyName(java.lang.String verifyName) {
		set("verifyName", verifyName);
	}
	
	/**
	 * 校核规则名称
	 */
	public java.lang.String getVerifyName() {
		return getStr("verifyName");
	}

	/**
	 * 针对字段
	 */
	public void setFieldEffect(java.lang.String fieldEffect) {
		set("fieldEffect", fieldEffect);
	}
	
	/**
	 * 针对字段
	 */
	public java.lang.String getFieldEffect() {
		return getStr("fieldEffect");
	}

	/**
	 * 校核规则执行sql
	 */
	public void setSqlStr(java.lang.String sqlStr) {
		set("sqlStr", sqlStr);
	}
	
	/**
	 * 校核规则执行sql
	 */
	public java.lang.String getSqlStr() {
		return getStr("sqlStr");
	}

	/**
	 * 1:人员 2:机构
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 1:人员 2:机构
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

}
