package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA61<M extends BaseA61<M>> extends Model<M> implements IBean {

	/**
	 * 人员统一标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员统一标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 选调生   等
	 */
	public void setA2970(java.lang.String A2970) {
		set("A2970", A2970);
	}
	
	/**
	 * 选调生   等
	 */
	public java.lang.String getA2970() {
		return getStr("A2970");
	}

	/**
	 * 来源   等
	 */
	public void setA2970A(java.lang.String A2970A) {
		set("A2970A", A2970A);
	}
	
	/**
	 * 来源   等
	 */
	public java.lang.String getA2970A() {
		return getStr("A2970A");
	}

	/**
	 * 初始工作单位   等
	 */
	public void setA2970B(java.lang.String A2970B) {
		set("A2970B", A2970B);
	}
	
	/**
	 * 初始工作单位   等
	 */
	public java.lang.String getA2970B() {
		return getStr("A2970B");
	}

	/**
	 * 进入选调生时间   等
	 */
	public void setA6104(java.lang.String A6104) {
		set("A6104", A6104);
	}
	
	/**
	 * 进入选调生时间   等
	 */
	public java.lang.String getA6104() {
		return getStr("A6104");
	}

	/**
	 * 在基层乡镇机关工作时间   等
	 */
	public void setA2970C(java.lang.Integer A2970C) {
		set("A2970C", A2970C);
	}
	
	/**
	 * 在基层乡镇机关工作时间   等
	 */
	public java.lang.Integer getA2970C() {
		return getInt("A2970C");
	}

	/**
	 * 选调时政治面貌   等
	 */
	public void setA6107(java.lang.String A6107) {
		set("A6107", A6107);
	}
	
	/**
	 * 选调时政治面貌   等
	 */
	public java.lang.String getA6107() {
		return getStr("A6107");
	}

	/**
	 * 选调时学历名称   等
	 */
	public void setA6108(java.lang.String A6108) {
		set("A6108", A6108);
	}
	
	/**
	 * 选调时学历名称   等
	 */
	public java.lang.String getA6108() {
		return getStr("A6108");
	}

	/**
	 * 选调时学历代码   等
	 */
	public void setA6109(java.lang.String A6109) {
		set("A6109", A6109);
	}
	
	/**
	 * 选调时学历代码   等
	 */
	public java.lang.String getA6109() {
		return getStr("A6109");
	}

	/**
	 * 选调时学位名称   等
	 */
	public void setA6110(java.lang.String A6110) {
		set("A6110", A6110);
	}
	
	/**
	 * 选调时学位名称   等
	 */
	public java.lang.String getA6110() {
		return getStr("A6110");
	}

	/**
	 * 选调时学位代码   等
	 */
	public void setA6111(java.lang.String A6111) {
		set("A6111", A6111);
	}
	
	/**
	 * 选调时学位代码   等
	 */
	public java.lang.String getA6111() {
		return getStr("A6111");
	}

	/**
	 * 是否退役大学生士兵   等
	 */
	public void setA6112(java.lang.String A6112) {
		set("A6112", A6112);
	}
	
	/**
	 * 是否退役大学生士兵   等
	 */
	public java.lang.String getA6112() {
		return getStr("A6112");
	}

	/**
	 * 是否有海外留学经历   等
	 */
	public void setA6113(java.lang.String A6113) {
		set("A6113", A6113);
	}
	
	/**
	 * 是否有海外留学经历   等
	 */
	public java.lang.String getA6113() {
		return getStr("A6113");
	}

	/**
	 * 留学年限   等
	 */
	public void setA6114(java.lang.Integer A6114) {
		set("A6114", A6114);
	}
	
	/**
	 * 留学年限   等
	 */
	public java.lang.Integer getA6114() {
		return getInt("A6114");
	}

	/**
	 * 是否有海外工作经历   等
	 */
	public void setA6115(java.lang.String A6115) {
		set("A6115", A6115);
	}
	
	/**
	 * 是否有海外工作经历   等
	 */
	public java.lang.String getA6115() {
		return getStr("A6115");
	}

	/**
	 * 海外工作年限   等
	 */
	public void setA6116(java.lang.Integer A6116) {
		set("A6116", A6116);
	}
	
	/**
	 * 海外工作年限   等
	 */
	public java.lang.Integer getA6116() {
		return getInt("A6116");
	}

}
