package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA60<M extends BaseA60<M>> extends Model<M> implements IBean {

	/**
	 * 人员统一标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员统一标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 考试录用人员   等
	 */
	public void setA6001(java.lang.String A6001) {
		set("A6001", A6001);
	}
	
	/**
	 * 考试录用人员   等
	 */
	public java.lang.String getA6001() {
		return getStr("A6001");
	}

	/**
	 * 录用时间   等
	 */
	public void setA6002(java.lang.String A6002) {
		set("A6002", A6002);
	}
	
	/**
	 * 录用时间   等
	 */
	public java.lang.String getA6002() {
		return getStr("A6002");
	}

	/**
	 * 录用时政治面貌   等
	 */
	public void setA6003(java.lang.String A6003) {
		set("A6003", A6003);
	}
	
	/**
	 * 录用时政治面貌   等
	 */
	public java.lang.String getA6003() {
		return getStr("A6003");
	}

	/**
	 * 录用时学历名称   等
	 */
	public void setA6004(java.lang.String A6004) {
		set("A6004", A6004);
	}
	
	/**
	 * 录用时学历名称   等
	 */
	public java.lang.String getA6004() {
		return getStr("A6004");
	}

	/**
	 * 录用时学历代码   等
	 */
	public void setA6005(java.lang.String A6005) {
		set("A6005", A6005);
	}
	
	/**
	 * 录用时学历代码   等
	 */
	public java.lang.String getA6005() {
		return getStr("A6005");
	}

	/**
	 * 录用时学位名称   等
	 */
	public void setA6006(java.lang.String A6006) {
		set("A6006", A6006);
	}
	
	/**
	 * 录用时学位名称   等
	 */
	public java.lang.String getA6006() {
		return getStr("A6006");
	}

	/**
	 * 录用时学位代码   等
	 */
	public void setA6007(java.lang.String A6007) {
		set("A6007", A6007);
	}
	
	/**
	 * 录用时学位代码   等
	 */
	public java.lang.String getA6007() {
		return getStr("A6007");
	}

	/**
	 * 录用时基层工作时间   等
	 */
	public void setA6008(java.lang.Integer A6008) {
		set("A6008", A6008);
	}
	
	/**
	 * 录用时基层工作时间   等
	 */
	public java.lang.Integer getA6008() {
		return getInt("A6008");
	}

	/**
	 * 人员来源情况   等
	 */
	public void setA6009(java.lang.String A6009) {
		set("A6009", A6009);
	}
	
	/**
	 * 人员来源情况   等
	 */
	public java.lang.String getA6009() {
		return getStr("A6009");
	}

	/**
	 * 是否服务基层项目人员   等
	 */
	public void setA6010(java.lang.String A6010) {
		set("A6010", A6010);
	}
	
	/**
	 * 是否服务基层项目人员   等
	 */
	public java.lang.String getA6010() {
		return getStr("A6010");
	}

	/**
	 * 是否退役士兵   等
	 */
	public void setA6011(java.lang.String A6011) {
		set("A6011", A6011);
	}
	
	/**
	 * 是否退役士兵   等
	 */
	public java.lang.String getA6011() {
		return getStr("A6011");
	}

	/**
	 * 是否退役大学生士兵   等
	 */
	public void setA6012(java.lang.String A6012) {
		set("A6012", A6012);
	}
	
	/**
	 * 是否退役大学生士兵   等
	 */
	public java.lang.String getA6012() {
		return getStr("A6012");
	}

	/**
	 * 是否残疾人   等
	 */
	public void setA6013(java.lang.String A6013) {
		set("A6013", A6013);
	}
	
	/**
	 * 是否残疾人   等
	 */
	public java.lang.String getA6013() {
		return getStr("A6013");
	}

	/**
	 * 是否有海外留学经历   等
	 */
	public void setA6014(java.lang.String A6014) {
		set("A6014", A6014);
	}
	
	/**
	 * 是否有海外留学经历   等
	 */
	public java.lang.String getA6014() {
		return getStr("A6014");
	}

	/**
	 * 留学年限   等
	 */
	public void setA6015(java.lang.Integer A6015) {
		set("A6015", A6015);
	}
	
	/**
	 * 留学年限   等
	 */
	public java.lang.Integer getA6015() {
		return getInt("A6015");
	}

	/**
	 * 是否有海外工作经历   等
	 */
	public void setA6016(java.lang.String A6016) {
		set("A6016", A6016);
	}
	
	/**
	 * 是否有海外工作经历   等
	 */
	public java.lang.String getA6016() {
		return getStr("A6016");
	}

	/**
	 * 海外工作年限   等
	 */
	public void setA6017(java.lang.Integer A6017) {
		set("A6017", A6017);
	}
	
	/**
	 * 海外工作年限   等
	 */
	public java.lang.Integer getA6017() {
		return getInt("A6017");
	}

}
