package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA11<M extends BaseA11<M>> extends Model<M> implements IBean {

	/**
	 * 人员统一标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员统一标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 培训信息ID
	 */
	public void setA1100(java.lang.String A1100) {
		set("A1100", A1100);
	}
	
	/**
	 * 培训信息ID
	 */
	public java.lang.String getA1100() {
		return getStr("A1100");
	}

	/**
	 * 培训类别 ZB29
	 */
	public void setA1101(java.lang.String A1101) {
		set("A1101", A1101);
	}
	
	/**
	 * 培训类别 ZB29
	 */
	public java.lang.String getA1101() {
		return getStr("A1101");
	}

	/**
	 * 培训离岗状态 ZB30
	 */
	public void setA1104(java.lang.String A1104) {
		set("A1104", A1104);
	}
	
	/**
	 * 培训离岗状态 ZB30
	 */
	public java.lang.String getA1104() {
		return getStr("A1104");
	}

	/**
	 * 培训开始日期
	 */
	public void setA1107(java.lang.String A1107) {
		set("A1107", A1107);
	}
	
	/**
	 * 培训开始日期
	 */
	public java.lang.String getA1107() {
		return getStr("A1107");
	}

	/**
	 * 培训时间月
	 */
	public void setA1107A(java.lang.Integer A1107A) {
		set("A1107A", A1107A);
	}
	
	/**
	 * 培训时间月
	 */
	public java.lang.Integer getA1107A() {
		return getInt("A1107A");
	}

	/**
	 * 培训时间天
	 */
	public void setA1107B(java.lang.Integer A1107B) {
		set("A1107B", A1107B);
	}
	
	/**
	 * 培训时间天
	 */
	public java.lang.Integer getA1107B() {
		return getInt("A1107B");
	}

	/**
	 * 培训结束日期
	 */
	public void setA1111(java.lang.String A1111) {
		set("A1111", A1111);
	}
	
	/**
	 * 培训结束日期
	 */
	public java.lang.String getA1111() {
		return getStr("A1111");
	}

	/**
	 * 培训主办单位
	 */
	public void setA1114(java.lang.String A1114) {
		set("A1114", A1114);
	}
	
	/**
	 * 培训主办单位
	 */
	public java.lang.String getA1114() {
		return getStr("A1114");
	}

	/**
	 * 培训机构名称
	 */
	public void setA1121A(java.lang.String A1121A) {
		set("A1121A", A1121A);
	}
	
	/**
	 * 培训机构名称
	 */
	public java.lang.String getA1121A() {
		return getStr("A1121A");
	}

	/**
	 * 培训机构类别 ZB27
	 */
	public void setA1127(java.lang.String A1127) {
		set("A1127", A1127);
	}
	
	/**
	 * 培训机构类别 ZB27
	 */
	public java.lang.String getA1127() {
		return getStr("A1127");
	}

	/**
	 * 培训名称
	 */
	public void setA1131(java.lang.String A1131) {
		set("A1131", A1131);
	}
	
	/**
	 * 培训名称
	 */
	public java.lang.String getA1131() {
		return getStr("A1131");
	}

	/**
	 * 培训班类别
	 */
	public void setA1134(java.lang.String A1134) {
		set("A1134", A1134);
	}
	
	/**
	 * 培训班类别
	 */
	public java.lang.String getA1134() {
		return getStr("A1134");
	}

	/**
	 * 出国（出境）培训标识
	 */
	public void setA1151(java.lang.String A1151) {
		set("A1151", A1151);
	}
	
	/**
	 * 出国（出境）培训标识
	 */
	public java.lang.String getA1151() {
		return getStr("A1151");
	}

	/**
	 * 标识
	 */
	public void setUPDATED(java.lang.String UPDATED) {
		set("UPDATED", UPDATED);
	}
	
	/**
	 * 标识
	 */
	public java.lang.String getUPDATED() {
		return getStr("UPDATED");
	}

	/**
	 * 学时
	 */
	public void setA1108(java.lang.Integer A1108) {
		set("A1108", A1108);
	}
	
	/**
	 * 学时
	 */
	public java.lang.Integer getA1108() {
		return getInt("A1108");
	}

	/**
	 * 培训时长（天）
	 */
	public void setA1107C(java.lang.Integer A1107C) {
		set("A1107C", A1107C);
	}
	
	/**
	 * 培训时长（天）
	 */
	public java.lang.Integer getA1107C() {
		return getInt("A1107C");
	}

}
