package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA33<M extends BaseA33<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setA3300(java.lang.String A3300) {
		set("A3300", A3300);
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getA3300() {
		return getStr("A3300");
	}

	/**
	 * 人员标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 基本工资
	 */
	public void setA3310(java.math.BigDecimal A3310) {
		set("A3310", A3310);
	}
	
	/**
	 * 基本工资
	 */
	public java.math.BigDecimal getA3310() {
		return get("A3310");
	}

	/**
	 * 国家统一的津贴补贴
	 */
	public void setA3321(java.math.BigDecimal A3321) {
		set("A3321", A3321);
	}
	
	/**
	 * 国家统一的津贴补贴
	 */
	public java.math.BigDecimal getA3321() {
		return get("A3321");
	}

	/**
	 * 乡镇工作补贴
	 */
	public void setA3321C(java.math.BigDecimal A3321C) {
		set("A3321C", A3321C);
	}
	
	/**
	 * 乡镇工作补贴
	 */
	public java.math.BigDecimal getA3321C() {
		return get("A3321C");
	}

	/**
	 * 高海拔地区折算工龄补贴
	 */
	public void setA3321D(java.math.BigDecimal A3321D) {
		set("A3321D", A3321D);
	}
	
	/**
	 * 高海拔地区折算工龄补贴
	 */
	public java.math.BigDecimal getA3321D() {
		return get("A3321D");
	}

	/**
	 * 规范津贴补贴
	 */
	public void setA3322(java.math.BigDecimal A3322) {
		set("A3322", A3322);
	}
	
	/**
	 * 规范津贴补贴
	 */
	public java.math.BigDecimal getA3322() {
		return get("A3322");
	}

	/**
	 * 改革性补贴
	 */
	public void setA3323(java.math.BigDecimal A3323) {
		set("A3323", A3323);
	}
	
	/**
	 * 改革性补贴
	 */
	public java.math.BigDecimal getA3323() {
		return get("A3323");
	}

	/**
	 * 年终一次性奖金
	 */
	public void setA3331(java.math.BigDecimal A3331) {
		set("A3331", A3331);
	}
	
	/**
	 * 年终一次性奖金
	 */
	public java.math.BigDecimal getA3331() {
		return get("A3331");
	}

	/**
	 * 立功受奖一次性奖金
	 */
	public void setA3332(java.math.BigDecimal A3332) {
		set("A3332", A3332);
	}
	
	/**
	 * 立功受奖一次性奖金
	 */
	public java.math.BigDecimal getA3332() {
		return get("A3332");
	}

	/**
	 * 奖励性补贴
	 */
	public void setA3333(java.math.BigDecimal A3333) {
		set("A3333", A3333);
	}
	
	/**
	 * 奖励性补贴
	 */
	public java.math.BigDecimal getA3333() {
		return get("A3333");
	}

	/**
	 * 其他（工资）
	 */
	public void setA3350(java.math.BigDecimal A3350) {
		set("A3350", A3350);
	}
	
	/**
	 * 其他（工资）
	 */
	public java.math.BigDecimal getA3350() {
		return get("A3350");
	}

	/**
	 * 工资待遇 XZ95
	 */
	public void setA3360(java.lang.String A3360) {
		set("A3360", A3360);
	}
	
	/**
	 * 工资待遇 XZ95
	 */
	public java.lang.String getA3360() {
		return getStr("A3360");
	}

	/**
	 * 工资级别 xz96
	 */
	public void setA3361(java.lang.String A3361) {
		set("A3361", A3361);
	}
	
	/**
	 * 工资级别 xz96
	 */
	public java.lang.String getA3361() {
		return getStr("A3361");
	}

	/**
	 * 工资档次
	 */
	public void setA3362(java.lang.String A3362) {
		set("A3362", A3362);
	}
	
	/**
	 * 工资档次
	 */
	public java.lang.String getA3362() {
		return getStr("A3362");
	}

	/**
	 * 享受艰苦边远地区津贴级别 xz97
	 */
	public void setA3371(java.lang.String A3371) {
		set("A3371", A3371);
	}
	
	/**
	 * 享受艰苦边远地区津贴级别 xz97
	 */
	public java.lang.String getA3371() {
		return getStr("A3371");
	}

	/**
	 * 享受艰苦边远地区津贴分类区 xz94
	 */
	public void setA3372(java.lang.String A3372) {
		set("A3372", A3372);
	}
	
	/**
	 * 享受艰苦边远地区津贴分类区 xz94
	 */
	public java.lang.String getA3372() {
		return getStr("A3372");
	}

	/**
	 * 工作年限增加
	 */
	public void setA3381(java.lang.Integer A3381) {
		set("A3381", A3381);
	}
	
	/**
	 * 工作年限增加
	 */
	public java.lang.Integer getA3381() {
		return getInt("A3381");
	}

	/**
	 * 工作年限扣减
	 */
	public void setA3382(java.lang.Integer A3382) {
		set("A3382", A3382);
	}
	
	/**
	 * 工作年限扣减
	 */
	public java.lang.Integer getA3382() {
		return getInt("A3382");
	}

	/**
	 * 年内领取工资月数
	 */
	public void setA3385(java.lang.Integer A3385) {
		set("A3385", A3385);
	}
	
	/**
	 * 年内领取工资月数
	 */
	public java.lang.Integer getA3385() {
		return getInt("A3385");
	}

}
