package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA41<M extends BaseA41<M>> extends Model<M> implements IBean {

	/**
	 * 培训班唯一标识
	 */
	public void setA4100(java.lang.String A4100) {
		set("A4100", A4100);
	}
	
	/**
	 * 培训班唯一标识
	 */
	public java.lang.String getA4100() {
		return getStr("A4100");
	}

	/**
	 * 培训人员标识
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 培训人员标识
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 培训班标识
	 */
	public void setA1100(java.lang.String A1100) {
		set("A1100", A1100);
	}
	
	/**
	 * 培训班标识
	 */
	public java.lang.String getA1100() {
		return getStr("A1100");
	}

	/**
	 * 请假标识
	 */
	public void setA4101(java.lang.String A4101) {
		set("A4101", A4101);
	}
	
	/**
	 * 请假标识
	 */
	public java.lang.String getA4101() {
		return getStr("A4101");
	}

	/**
	 * 缺席标识
	 */
	public void setA4102(java.lang.String A4102) {
		set("A4102", A4102);
	}
	
	/**
	 * 缺席标识
	 */
	public java.lang.String getA4102() {
		return getStr("A4102");
	}

	/**
	 * 论文成绩标识
	 */
	public void setA4103(java.lang.String A4103) {
		set("A4103", A4103);
	}
	
	/**
	 * 论文成绩标识
	 */
	public java.lang.String getA4103() {
		return getStr("A4103");
	}

	/**
	 * 学分标识
	 */
	public void setA4104(java.lang.String A4104) {
		set("A4104", A4104);
	}
	
	/**
	 * 学分标识
	 */
	public java.lang.String getA4104() {
		return getStr("A4104");
	}

	/**
	 * 培训意见标识
	 */
	public void setA4105(java.lang.String A4105) {
		set("A4105", A4105);
	}
	
	/**
	 * 培训意见标识
	 */
	public java.lang.String getA4105() {
		return getStr("A4105");
	}

	/**
	 * 备注标识
	 */
	public void setA4199(java.lang.String A4199) {
		set("A4199", A4199);
	}
	
	/**
	 * 备注标识
	 */
	public java.lang.String getA4199() {
		return getStr("A4199");
	}

}
