package com.wdy.generator.postgreSQL.model.base;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.sql.SQLException;
import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA01Temp<M extends BaseA01Temp<M>> extends Model<M> implements IBean {

    public M setImpId(java.lang.String impId) {
        set("impId", impId);
        return (M) this;
    }

    public java.lang.String getImpId() {
        return getStr("impId");
    }

    /**
     * 人员统一标识符
     */
    public M setA0000(java.lang.String A0000) {
        set("A0000", A0000);
        return (M) this;
    }

    /**
     * 人员统一标识符
     */
    public java.lang.String getA0000() {
        return getStr("A0000");
    }

    /**
     * 姓名   等
     */
    public M setA0101(java.lang.String A0101) {
        set("A0101", A0101);
        return (M) this;
    }

    /**
     * 姓名   等
     */
    public java.lang.String getA0101() {
        return getStr("A0101");
    }

    /**
     * 姓名拼音缩写   等
     */
    public M setA0102(java.lang.String A0102) {
        set("A0102", A0102);
        return (M) this;
    }

    /**
     * 姓名拼音缩写   等
     */
    public java.lang.String getA0102() {
        return getStr("A0102");
    }

    /**
     * 性别   等
     */
    public M setA0104(java.lang.String A0104) {
        set("A0104", A0104);
        return (M) this;
    }

    /**
     * 性别   等
     */
    public java.lang.String getA0104() {
        return getStr("A0104");
    }

    /**
     * 出生日期   等
     */
    public M setA0107(java.util.Date A0107) {
        set("A0107", A0107);
        return (M) this;
    }

    /**
     * 出生日期   等
     */
    public java.util.Date getA0107() {
        return get("A0107");
    }

    /**
     * 籍贯   等
     */
    public M setA0111A(java.lang.String A0111A) {
        set("A0111A", A0111A);
        return (M) this;
    }

    /**
     * 籍贯   等
     */
    public java.lang.String getA0111A() {
        return getStr("A0111A");
    }

    /**
     * 出生地   等
     */
    public M setA0114A(java.lang.String A0114A) {
        set("A0114A", A0114A);
        return (M) this;
    }

    /**
     * 出生地   等
     */
    public java.lang.String getA0114A() {
        return getStr("A0114A");
    }

    /**
     * 成长地    多
     */
    public M setA0115A(java.lang.String A0115A) {
        set("A0115A", A0115A);
        return (M) this;
    }

    /**
     * 成长地    多
     */
    public java.lang.String getA0115A() {
        return getStr("A0115A");
    }

    /**
     * 民族   等
     */
    public M setA0117(java.lang.String A0117) {
        set("A0117", A0117);
        return (M) this;
    }

    /**
     * 民族   等
     */
    public java.lang.String getA0117() {
        return getStr("A0117");
    }

    /**
     * 健康状况   等
     */
    public M setA0128(java.lang.String A0128) {
        set("A0128", A0128);
        return (M) this;
    }

    /**
     * 健康状况   等
     */
    public java.lang.String getA0128() {
        return getStr("A0128");
    }

    /**
     * 参加工作时间   等
     */
    public M setA0134(java.util.Date A0134) {
        set("A0134", A0134);
        return (M) this;
    }

    /**
     * 参加工作时间   等
     */
    public java.util.Date getA0134() {
        return get("A0134");
    }

    /**
     * 入党时间文字   等
     */
    public M setA0140(java.lang.String A0140) {
        set("A0140", A0140);
        return (M) this;
    }

    /**
     * 入党时间文字   等
     */
    public java.lang.String getA0140() {
        return getStr("A0140");
    }

    /**
     * 政治面貌   等
     */
    public M setA0141(java.lang.String A0141) {
        set("A0141", A0141);
        return (M) this;
    }

    /**
     * 政治面貌   等
     */
    public java.lang.String getA0141() {
        return getStr("A0141");
    }

    /**
     * 入党时间   等
     */
    public M setA0144(java.util.Date A0144) {
        set("A0144", A0144);
        return (M) this;
    }

    /**
     * 入党时间   等
     */
    public java.util.Date getA0144() {
        return get("A0144");
    }

    /**
     * 第二党派   等
     */
    public M setA3921(java.lang.String A3921) {
        set("A3921", A3921);
        return (M) this;
    }

    /**
     * 第二党派   等
     */
    public java.lang.String getA3921() {
        return getStr("A3921");
    }

    /**
     * 第三党派   等
     */
    public M setA3927(java.lang.String A3927) {
        set("A3927", A3927);
        return (M) this;
    }

    /**
     * 第三党派   等
     */
    public java.lang.String getA3927() {
        return getStr("A3927");
    }

    /**
     * 人员类别   等
     */
    public M setA0160(java.lang.String A0160) {
        set("A0160", A0160);
        return (M) this;
    }

    /**
     * 人员类别   等
     */
    public java.lang.String getA0160() {
        return getStr("A0160");
    }

    /**
     * 人员管理状态   等
     */
    public M setA0163(java.lang.String A0163) {
        set("A0163", A0163);
        return (M) this;
    }

    /**
     * 人员管理状态   等
     */
    public java.lang.String getA0163() {
        return getStr("A0163");
    }

    /**
     * 管理类别   等
     */
    public M setA0165(java.lang.String A0165) {
        set("A0165", A0165);
        return (M) this;
    }

    /**
     * 管理类别   等
     */
    public java.lang.String getA0165() {
        return getStr("A0165");
    }

    /**
     * 公民身份号码   等
     */
    public M setA0184(java.lang.String A0184) {
        set("A0184", A0184);
        return (M) this;
    }

    /**
     * 公民身份号码   等
     */
    public java.lang.String getA0184() {
        return getStr("A0184");
    }

    /**
     * 专长   等
     */
    public M setA0187A(java.lang.String A0187A) {
        set("A0187A", A0187A);
        return (M) this;
    }

    /**
     * 专长   等
     */
    public java.lang.String getA0187A() {
        return getStr("A0187A");
    }

    /**
     * 现工作单位及职务简称   等
     */
    public M setA0192(java.lang.String A0192) {
        set("A0192", A0192);
        return (M) this;
    }

    /**
     * 现工作单位及职务简称   等
     */
    public java.lang.String getA0192() {
        return getStr("A0192");
    }

    /**
     * 现工作单位及职务全称   等
     */
    public M setA0192A(java.lang.String A0192A) {
        set("A0192A", A0192A);
        return (M) this;
    }

    /**
     * 现工作单位及职务全称   等
     */
    public java.lang.String getA0192A() {
        return getStr("A0192A");
    }

    /**
     * 职务层次    多
     */
    public M setA0221(java.lang.String A0221) {
        set("A0221", A0221);
        return (M) this;
    }

    /**
     * 职务层次    多
     */
    public java.lang.String getA0221() {
        return getStr("A0221");
    }

    /**
     * 任现职务层次时间   多
     */
    public M setA0288(java.util.Date A0288) {
        set("A0288", A0288);
        return (M) this;
    }

    /**
     * 任现职务层次时间   多
     */
    public java.util.Date getA0288() {
        return get("A0288");
    }

    /**
     * 职级   等
     */
    public M setA0192D(java.lang.String A0192D) {
        set("A0192D", A0192D);
        return (M) this;
    }

    /**
     * 职级   等
     */
    public java.lang.String getA0192D() {
        return getStr("A0192D");
    }

    /**
     * 任该职级时间   多
     */
    public M setA0192C(java.util.Date A0192C) {
        set("A0192C", A0192C);
        return (M) this;
    }

    /**
     * 任该职级时间   多
     */
    public java.util.Date getA0192C() {
        return get("A0192C");
    }

    /**
     * 专业技术职务   等
     */
    public M setA0196(java.lang.String A0196) {
        set("A0196", A0196);
        return (M) this;
    }

    /**
     * 专业技术职务   等
     */
    public java.lang.String getA0196() {
        return getStr("A0196");
    }

    /**
     * 是否具有两年以上基层工作经历   多 1 是 0 否
     */
    public M setA0197(java.lang.String A0197) {
        set("A0197", A0197);
        return (M) this;
    }

    /**
     * 是否具有两年以上基层工作经历   多 1 是 0 否
     */
    public java.lang.String getA0197() {
        return getStr("A0197");
    }

    /**
     * 统计关系所在单位   等
     */
    public M setA0195(java.lang.String A0195) {
        set("A0195", A0195);
        return (M) this;
    }

    /**
     * 统计关系所在单位   等
     */
    public java.lang.String getA0195() {
        return getStr("A0195");
    }

    /**
     * 简历   等
     */
    public M setA1701(java.lang.String A1701) {
        set("A1701", A1701);
        return (M) this;
    }

    /**
     * 简历   等
     */
    public java.lang.String getA1701() {
        return getStr("A1701");
    }

    public M setA14Z101(java.lang.String A14Z101) {
        set("A14Z101", A14Z101);
        return (M) this;
    }

    public java.lang.String getA14Z101() {
        return getStr("A14Z101");
    }

    public M setA15Z101(java.lang.String A15Z101) {
        set("A15Z101", A15Z101);
        return (M) this;
    }

    public java.lang.String getA15Z101() {
        return getStr("A15Z101");
    }

    /**
     * 级别   等
     */
    public M setA0120(java.lang.String A0120) {
        set("A0120", A0120);
        return (M) this;
    }

    /**
     * 级别   等
     */
    public java.lang.String getA0120() {
        return getStr("A0120");
    }

    /**
     * 编制类型   等
     */
    public M setA0121(java.lang.String A0121) {
        set("A0121", A0121);
        return (M) this;
    }

    /**
     * 编制类型   等
     */
    public java.lang.String getA0121() {
        return getStr("A0121");
    }

    /**
     * 公务员登记时间   多
     */
    public M setA2949(java.util.Date A2949) {
        set("A2949", A2949);
        return (M) this;
    }

    /**
     * 公务员登记时间   多
     */
    public java.util.Date getA2949() {
        return get("A2949");
    }

    /**
     * 专业技术类公务员任职资格   等
     */
    public M setA0122(java.lang.String A0122) {
        set("A0122", A0122);
        return (M) this;
    }

    /**
     * 专业技术类公务员任职资格   等
     */
    public java.lang.String getA0122() {
        return getStr("A0122");
    }

    /**
     * 性别(汉字)1
     */
    public M setA0104A(java.lang.String A0104A) {
        set("A0104A", A0104A);
        return (M) this;
    }

    /**
     * 性别(汉字)1
     */
    public java.lang.String getA0104A() {
        return getStr("A0104A");
    }

    /**
     * 籍贯
     */
    public M setA0111(java.lang.String A0111) {
        set("A0111", A0111);
        return (M) this;
    }

    /**
     * 籍贯
     */
    public java.lang.String getA0111() {
        return getStr("A0111");
    }

    /**
     * 出生地
     */
    public M setA0114(java.lang.String A0114) {
        set("A0114", A0114);
        return (M) this;
    }

    /**
     * 出生地
     */
    public java.lang.String getA0114() {
        return getStr("A0114");
    }

    /**
     * 民族(汉字)1
     */
    public M setA0117A(java.lang.String A0117A) {
        set("A0117A", A0117A);
        return (M) this;
    }

    /**
     * 民族(汉字)1
     */
    public java.lang.String getA0117A() {
        return getStr("A0117A");
    }

    /**
     * 健康状况1
     */
    public M setA0128B(java.lang.String A0128B) {
        set("A0128B", A0128B);
        return (M) this;
    }

    /**
     * 健康状况1
     */
    public java.lang.String getA0128B() {
        return getStr("A0128B");
    }

    /**
     * 记录本人三个政治面貌1
     */
    public M setA0141D(java.lang.String A0141D) {
        set("A0141D", A0141D);
        return (M) this;
    }

    /**
     * 记录本人三个政治面貌1
     */
    public java.lang.String getA0141D() {
        return getStr("A0141D");
    }

    /**
     * 参加组织时间二1
     */
    public M setA0144B(java.lang.String A0144B) {
        set("A0144B", A0144B);
        return (M) this;
    }

    /**
     * 参加组织时间二1
     */
    public java.lang.String getA0144B() {
        return getStr("A0144B");
    }

    /**
     * 参加组织时间三1
     */
    public M setA0144C(java.lang.String A0144C) {
        set("A0144C", A0144C);
        return (M) this;
    }

    /**
     * 参加组织时间三1
     */
    public java.lang.String getA0144C() {
        return getStr("A0144C");
    }

    /**
     * 最高职务层次
     */
    public M setA0148(java.lang.String A0148) {
        set("A0148", A0148);
        return (M) this;
    }

    /**
     * 最高职务层次
     */
    public java.lang.String getA0148() {
        return getStr("A0148");
    }

    /**
     * 职务层次批准时间1
     */
    public M setA0148C(java.lang.String A0148C) {
        set("A0148C", A0148C);
        return (M) this;
    }

    /**
     * 职务层次批准时间1
     */
    public java.lang.String getA0148C() {
        return getStr("A0148C");
    }

    /**
     * 职务层次
     */
    public M setA0149(java.lang.String A0149) {
        set("A0149", A0149);
        return (M) this;
    }

    /**
     * 职务层次
     */
    public java.lang.String getA0149() {
        return getStr("A0149");
    }

    /**
     * 该人参加公务员登记的标识。1—登记；2—暂缓登记；3—不予登记。
     */
    public M setA0151(java.lang.String A0151) {
        set("A0151", A0151);
        return (M) this;
    }

    /**
     * 该人参加公务员登记的标识。1—登记；2—暂缓登记；3—不予登记。
     */
    public java.lang.String getA0151() {
        return getStr("A0151");
    }

    /**
     * 公务员登记类别1—公务员；02—参照管理人员；3—其他
     */
    public M setA0153(java.lang.String A0153) {
        set("A0153", A0153);
        return (M) this;
    }

    /**
     * 公务员登记类别1—公务员；02—参照管理人员；3—其他
     */
    public java.lang.String getA0153() {
        return getStr("A0153");
    }

    /**
     * 人事关系所在单位名称1
     */
    public M setA0157(java.lang.String A0157) {
        set("A0157", A0157);
        return (M) this;
    }

    /**
     * 人事关系所在单位名称1
     */
    public java.lang.String getA0157() {
        return getStr("A0157");
    }

    /**
     * 公务员级别1
     */
    public M setA0158(java.lang.String A0158) {
        set("A0158", A0158);
        return (M) this;
    }

    /**
     * 公务员级别1
     */
    public java.lang.String getA0158() {
        return getStr("A0158");
    }

    /**
     * 公务员登记后所定职务
     */
    public M setA0159(java.lang.String A0159) {
        set("A0159", A0159);
        return (M) this;
    }

    /**
     * 公务员登记后所定职务
     */
    public java.lang.String getA0159() {
        return getStr("A0159");
    }

    /**
     * 职务拼接方式1
     */
    public M setA015A(java.lang.String A015A) {
        set("A015A", A015A);
        return (M) this;
    }

    /**
     * 职务拼接方式1
     */
    public java.lang.String getA015A() {
        return getStr("A015A");
    }

    public M setA0161(java.lang.String A0161) {
        set("A0161", A0161);
        return (M) this;
    }

    public java.lang.String getA0161() {
        return getStr("A0161");
    }

    /**
     * 公务员级别批准日期1
     */
    public M setA0162(java.lang.String A0162) {
        set("A0162", A0162);
        return (M) this;
    }

    /**
     * 公务员级别批准日期1
     */
    public java.lang.String getA0162() {
        return getStr("A0162");
    }

    public M setA0180(java.lang.String A0180) {
        set("A0180", A0180);
        return (M) this;
    }

    public java.lang.String getA0180() {
        return getStr("A0180");
    }

    /**
     * 与列表关联
     */
    public M setA0191(java.lang.String A0191) {
        set("A0191", A0191);
        return (M) this;
    }

    /**
     * 与列表关联
     */
    public java.lang.String getA0191() {
        return getStr("A0191");
    }

    public M setA0192B(java.lang.String A0192B) {
        set("A0192B", A0192B);
        return (M) this;
    }

    public java.lang.String getA0192B() {
        return getStr("A0192B");
    }

    /**
     * 职务层次1
     */
    public M setA0193(java.lang.String A0193) {
        set("A0193", A0193);
        return (M) this;
    }

    /**
     * 职务层次1
     */
    public java.lang.String getA0193() {
        return getStr("A0193");
    }

    /**
     * 该人在基层工作的时间是否2年以上-报送标准A0197
     */
    public M setA0194U(java.lang.String A0194U) {
        set("A0194U", A0194U);
        return (M) this;
    }

    /**
     * 该人在基层工作的时间是否2年以上-报送标准A0197
     */
    public java.lang.String getA0194U() {
        return getStr("A0194U");
    }

    /**
     * 照片路径1
     */
    public M setA0198(java.lang.String A0198) {
        set("A0198", A0198);
        return (M) this;
    }

    /**
     * 照片路径1
     */
    public java.lang.String getA0198() {
        return getStr("A0198");
    }

    /**
     * 用于区分是否是正在增加的人员，1为任免表导入人员；0为正常人员1
     */
    public M setA0199(java.lang.String A0199) {
        set("A0199", A0199);
        return (M) this;
    }

    /**
     * 用于区分是否是正在增加的人员，1为任免表导入人员；0为正常人员1
     */
    public java.lang.String getA0199() {
        return getStr("A0199");
    }

    /**
     * 最高职务层次类别1
     */
    public M setA01K01(java.lang.String A01K01) {
        set("A01K01", A01K01);
        return (M) this;
    }

    /**
     * 最高职务层次类别1
     */
    public java.lang.String getA01K01() {
        return getStr("A01K01");
    }

    /**
     * 该人是否有基层工作经验的标志。
     */
    public M setA01K02(java.lang.String A01K02) {
        set("A01K02", A01K02);
        return (M) this;
    }

    /**
     * 该人是否有基层工作经验的标志。
     */
    public java.lang.String getA01K02() {
        return getStr("A01K02");
    }

    /**
     * 呈报单审批结果
     */
    public M setCBDRESULT(java.lang.String CBDRESULT) {
        set("CBDRESULT", CBDRESULT);
        return (M) this;
    }

    /**
     * 呈报单审批结果
     */
    public java.lang.String getCBDRESULT() {
        return getStr("CBDRESULT");
    }

    /**
     * 呈报单位1
     */
    public M setCBDW(java.lang.String CBDW) {
        set("CBDW", CBDW);
        return (M) this;
    }

    /**
     * 呈报单位1
     */
    public java.lang.String getCBDW() {
        return getStr("CBDW");
    }

    /**
     * 多次保存结果1
     */
    public M setISVALID(java.lang.String ISVALID) {
        set("ISVALID", ISVALID);
        return (M) this;
    }

    /**
     * 多次保存结果1
     */
    public java.lang.String getISVALID() {
        return getStr("ISVALID");
    }

    /**
     * 年龄1
     */
    public M setNL(java.lang.String NL) {
        set("NL", NL);
        return (M) this;
    }

    /**
     * 年龄1
     */
    public java.lang.String getNL() {
        return getStr("NL");
    }

    /**
     * 拟免职务1
     */
    public M setNMZW(java.lang.String NMZW) {
        set("NMZW", NMZW);
        return (M) this;
    }

    /**
     * 拟免职务1
     */
    public java.lang.String getNMZW() {
        return getStr("NMZW");
    }

    /**
     * 拟任职务1
     */
    public M setNRZW(java.lang.String NRZW) {
        set("NRZW", NRZW);
        return (M) this;
    }

    /**
     * 拟任职务1
     */
    public java.lang.String getNRZW() {
        return getStr("NRZW");
    }

    /**
     * 历史离退人员所在的机构id
     */
    public M setORGID(java.lang.String ORGID) {
        set("ORGID", ORGID);
        return (M) this;
    }

    /**
     * 历史离退人员所在的机构id
     */
    public java.lang.String getORGID() {
        return getStr("ORGID");
    }

    /**
     * 最高全日制学历
     */
    public M setQRZXL(java.lang.String QRZXL) {
        set("QRZXL", QRZXL);
        return (M) this;
    }

    /**
     * 最高全日制学历
     */
    public java.lang.String getQRZXL() {
        return getStr("QRZXL");
    }

    /**
     * 院校系专业（最高全日制学历）
     */
    public M setQRZXLXX(java.lang.String QRZXLXX) {
        set("QRZXLXX", QRZXLXX);
        return (M) this;
    }

    /**
     * 院校系专业（最高全日制学历）
     */
    public java.lang.String getQRZXLXX() {
        return getStr("QRZXLXX");
    }

    /**
     * 最高全日制学位
     */
    public M setQRZXW(java.lang.String QRZXW) {
        set("QRZXW", QRZXW);
        return (M) this;
    }

    /**
     * 最高全日制学位
     */
    public java.lang.String getQRZXW() {
        return getStr("QRZXW");
    }

    /**
     * 院校系专业（最高全日制学位）
     */
    public M setQRZXWXX(java.lang.String QRZXWXX) {
        set("QRZXWXX", QRZXWXX);
        return (M) this;
    }

    /**
     * 院校系专业（最高全日制学位）
     */
    public java.lang.String getQRZXWXX() {
        return getStr("QRZXWXX");
    }

    /**
     * 任免理由1
     */
    public M setRMLY(java.lang.String RMLY) {
        set("RMLY", RMLY);
        return (M) this;
    }

    /**
     * 任免理由1
     */
    public java.lang.String getRMLY() {
        return getStr("RMLY");
    }

    /**
     * 状态 0完全删除 1正常 2历史库3离退人员4临时数据
     */
    public M setSTATUS(java.lang.String STATUS) {
        set("STATUS", STATUS);
        return (M) this;
    }

    /**
     * 状态 0完全删除 1正常 2历史库3离退人员4临时数据
     */
    public java.lang.String getSTATUS() {
        return getStr("STATUS");
    }

    /**
     * 填报人id
     */
    public M setTBR(java.lang.String TBR) {
        set("TBR", TBR);
        return (M) this;
    }

    /**
     * 填报人id
     */
    public java.lang.String getTBR() {
        return getStr("TBR");
    }

    /**
     * 填报人所在机构id  1-删
     */
    public M setTBRJG(java.lang.String TBRJG) {
        set("TBRJG", TBRJG);
        return (M) this;
    }

    /**
     * 填报人所在机构id  1-删
     */
    public java.lang.String getTBRJG() {
        return getStr("TBRJG");
    }

    /**
     * 结果集的用户名id号1
     */
    public M setUSERLOG(java.lang.String USERLOG) {
        set("USERLOG", USERLOG);
        return (M) this;
    }

    /**
     * 结果集的用户名id号1
     */
    public java.lang.String getUSERLOG() {
        return getStr("USERLOG");
    }

    /**
     * 修改人1
     */
    public M setXGR(java.lang.String XGR) {
        set("XGR", XGR);
        return (M) this;
    }

    /**
     * 修改人1
     */
    public java.lang.String getXGR() {
        return getStr("XGR");
    }

    /**
     * 最高在职学历
     */
    public M setZZXL(java.lang.String ZZXL) {
        set("ZZXL", ZZXL);
        return (M) this;
    }

    /**
     * 最高在职学历
     */
    public java.lang.String getZZXL() {
        return getStr("ZZXL");
    }

    /**
     * 院校系专业（最高在职学历）
     */
    public M setZZXLXX(java.lang.String ZZXLXX) {
        set("ZZXLXX", ZZXLXX);
        return (M) this;
    }

    /**
     * 院校系专业（最高在职学历）
     */
    public java.lang.String getZZXLXX() {
        return getStr("ZZXLXX");
    }

    /**
     * 最高在职学位
     */
    public M setZZXW(java.lang.String ZZXW) {
        set("ZZXW", ZZXW);
        return (M) this;
    }

    /**
     * 最高在职学位
     */
    public java.lang.String getZZXW() {
        return getStr("ZZXW");
    }

    /**
     * 院校系专业（最高在职学位）
     */
    public M setZZXWXX(java.lang.String ZZXWXX) {
        set("ZZXWXX", ZZXWXX);
        return (M) this;
    }

    /**
     * 院校系专业（最高在职学位）
     */
    public java.lang.String getZZXWXX() {
        return getStr("ZZXWXX");
    }

    /**
     * 公务员登记时间
     */
    public M setA0155(java.util.Date A0155) {
        set("A0155", A0155);
        return (M) this;
    }

    /**
     * 公务员登记时间
     */
    public java.util.Date getA0155() {
        return get("A0155");
    }

    /**
     * 年龄1
     */
    public M setAGE(java.lang.Integer AGE) {
        set("AGE", AGE);
        return (M) this;
    }

    /**
     * 年龄1
     */
    public java.lang.Integer getAGE() {
        return getInt("AGE");
    }

    /**
     * 计算年龄时间1
     */
    public M setJSNLSJ(java.util.Date JSNLSJ) {
        set("JSNLSJ", JSNLSJ);
        return (M) this;
    }

    /**
     * 计算年龄时间1
     */
    public java.util.Date getJSNLSJ() {
        return get("JSNLSJ");
    }

    /**
     * 排序号1
     */
    public M setRESULTSORTID(java.lang.Integer RESULTSORTID) {
        set("RESULTSORTID", RESULTSORTID);
        return (M) this;
    }

    /**
     * 排序号1
     */
    public java.lang.Integer getRESULTSORTID() {
        return getInt("RESULTSORTID");
    }

    /**
     * 填表时间
     */
    public M setTBSJ(java.util.Date TBSJ) {
        set("TBSJ", TBSJ);
        return (M) this;
    }

    /**
     * 填表时间
     */
    public java.util.Date getTBSJ() {
        return get("TBSJ");
    }

    /**
     * 修改时间1
     */
    public M setXGSJ(java.util.Date XGSJ) {
        set("XGSJ", XGSJ);
        return (M) this;
    }

    /**
     * 修改时间1
     */
    public java.util.Date getXGSJ() {
        return get("XGSJ");
    }

    /**
     * 排序字段1
     */
    public M setSORTID(java.lang.Integer SORTID) {
        set("SORTID", SORTID);
        return (M) this;
    }

    /**
     * 排序字段1
     */
    public java.lang.Integer getSORTID() {
        return getInt("SORTID");
    }

    /**
     * 该人在基层工作的年月   将年月计算成月份存储
     */
    public M setA0194(java.lang.Integer A0194) {
        set("A0194", A0194);
        return (M) this;
    }

    /**
     * 该人在基层工作的年月   将年月计算成月份存储
     */
    public java.lang.Integer getA0194() {
        return getInt("A0194");
    }

    /**
     * 职级（职级并行）
     */
    public M setA0192E(java.lang.String A0192E) {
        set("A0192E", A0192E);
        return (M) this;
    }

    /**
     * 职级（职级并行）
     */
    public java.lang.String getA0192E() {
        return getStr("A0192E");
    }

    /**
     * 工作单位及职务全称对应的，任职时间
     */
    public M setA0192F(java.lang.String A0192F) {
        set("A0192F", A0192F);
        return (M) this;
    }

    /**
     * 工作单位及职务全称对应的，任职时间
     */
    public java.lang.String getA0192F() {
        return getStr("A0192F");
    }

    /**
     * 最高机构
     */
    public M setTORGID(java.lang.String TORGID) {
        set("TORGID", TORGID);
        return (M) this;
    }

    /**
     * 最高机构
     */
    public java.lang.String getTORGID() {
        return getStr("TORGID");
    }

    /**
     * 最高机构所在机体内排序
     */
    public M setTORDER(java.lang.String TORDER) {
        set("TORDER", TORDER);
        return (M) this;
    }

    /**
     * 最高机构所在机体内排序
     */
    public java.lang.String getTORDER() {
        return getStr("TORDER");
    }

    public M setZGXL(java.lang.String ZGXL) {
        set("ZGXL", ZGXL);
        return (M) this;
    }

    public java.lang.String getZGXL() {
        return getStr("ZGXL");
    }

    public M setZGXLXX(java.lang.String ZGXLXX) {
        set("ZGXLXX", ZGXLXX);
        return (M) this;
    }

    public java.lang.String getZGXLXX() {
        return getStr("ZGXLXX");
    }

    public M setZGXW(java.lang.String ZGXW) {
        set("ZGXW", ZGXW);
        return (M) this;
    }

    public java.lang.String getZGXW() {
        return getStr("ZGXW");
    }

    public M setZGXWXX(java.lang.String ZGXWXX) {
        set("ZGXWXX", ZGXWXX);
        return (M) this;
    }

    public java.lang.String getZGXWXX() {
        return getStr("ZGXWXX");
    }

    public M setTCSJSHOW(java.lang.String TCSJSHOW) {
        set("TCSJSHOW", TCSJSHOW);
        return (M) this;
    }

    public java.lang.String getTCSJSHOW() {
        return getStr("TCSJSHOW");
    }

    /**
     * 退出方式
     */
    public M setTCFSSHOW(java.lang.String TCFSSHOW) {
        set("TCFSSHOW", TCFSSHOW);
        return (M) this;
    }

    /**
     * 退出方式
     */
    public java.lang.String getTCFSSHOW() {
        return getStr("TCFSSHOW");
    }

    /**
     * 全日制综述
     */
    public M setQRZZS(java.lang.String QRZZS) {
        set("QRZZS", QRZZS);
        return (M) this;
    }

    /**
     * 全日制综述
     */
    public java.lang.String getQRZZS() {
        return getStr("QRZZS");
    }

    /**
     * 在职综述
     */
    public M setZZZS(java.lang.String ZZZS) {
        set("ZZZS", ZZZS);
        return (M) this;
    }

    /**
     * 在职综述
     */
    public java.lang.String getZZZS() {
        return getStr("ZZZS");
    }

    /**
     * 公务员登记号
     */
    public M setA0155A(java.lang.String A0155A) {
        set("A0155A", A0155A);
        return (M) this;
    }

    /**
     * 公务员登记号
     */
    public java.lang.String getA0155A() {
        return getStr("A0155A");
    }

    /**
     * 原人员数据信息，例如：[{"A0000":"123","A0184":"身份证","A0192":"现任职务","A0107":"出生日期","A0101":"姓名","A0255":"是否在任"}]
     */
    public M setOldDataArray(JSONArray oldDataArray) {
//		JSON.toJSONString(oldDataArray);
//		PGobject pGobject = new PGobject();
//		pGobject.setType("json");
//		pGobject.setValue(oldDataArray.toJSONString());
        set("oldDataArray", JSON.toJSONString(oldDataArray));
        return (M) this;
    }

    /**
     * 原人员数据信息，例如：[{"A0000":"123","A0184":"身份证","A0192":"现任职务","A0107":"出生日期","A0101":"姓名","A0255":"是否在任"}]
     */
    public JSONArray getOldDataArray() {
        String oldDataArray1 = getStr("oldDataArray");
        return JSONArray.parseArray(oldDataArray1);
//		PGobject oldDataArray = get("oldDataArray");
//		if(ObjectUtil.isNull(oldDataArray)){
//			return new JSONArray();
//		}
//		return JSONArray.parseArray(oldDataArray.getValue());
    }

    /**
     * 需要更新的原人员数据A0000
     */
    public M setToA0000(java.lang.String toA0000) {
        set("toA0000", toA0000);
        return (M) this;
    }

    /**
     * 需要更新的原人员数据A0000
     */
    public java.lang.String getToA0000() {
        return getStr("toA0000");
    }

    /**
     * 对比结果（与系统一致，系统无此人）
     */
    public M setResult(java.lang.String result) {
        set("result", result);
        return (M) this;
    }

    /**
     * 对比结果（与系统一致，系统无此人）
     */
    public java.lang.String getResult() {
        return getStr("result");
    }

    /**
     * 上传文件类型：1（lrm,lrmx,pic）,2（zip）
     */
    public M setType(java.lang.String type) {
        set("type", type);
        return (M) this;
    }

    /**
     * 上传文件类型：1（lrm,lrmx,pic）,2（zip）
     */
    public java.lang.String getType() {
        return getStr("type");
    }

    /**
     * 公务员所属具体职位分类 XZ93
     */
    public M setA0123(String A0123) {
        set("A0123", A0123);
        return (M) this;
    }


    /**
     * 人员最近考核年度
     */
    public M setA01Z106(Date A01Z106) {
        set("A01Z106", A01Z106);
        return (M) this;
    }

    /**
     * 人员最近考核年度
     */
    public Date getA01Z106() {
        return getDate("A01Z106");
    }


    /**
     * 是否进3年考核为优秀
     */
    public M setA01Z107(java.lang.String A01Z107) {
        set("A01Z107", A01Z107);
        return (M) this;
    }

    /**
     * 是否进3年考核为优秀
     */
    public java.lang.String getA01Z107() {
        return getStr("A01Z107");
    }


    /**
     * 是否近5年考核为优秀
     */
    public M setA01Z108(java.lang.String A01Z108) {
        set("A01Z108", A01Z108);
        return (M) this;
    }

    /**
     * 是否近5年考核为优秀
     */
    public java.lang.String getA01Z108() {
        return getStr("A01Z108");
    }

    /**
     * 公务员所属具体职位分类 XZ93
     */
    public String getA0123() {
        return getStr("A0123");
    }

    public M setA15Z191(String A15Z191) {
        set("A15Z191", A15Z191);
        return (M) this;
    }

    public String getA15Z191() {
        return getStr("A15Z191");
    }

    /**
     * 是否副省级
     */
    public M setFSJ(String FSJ) {
        set("FSJ", FSJ);
        return (M) this;
    }

    /**
     * 是否副省级
     */
    public String getFSJ() {
        return getStr("FSJ");
    }

}
