package com.wdy.generator.postgreSQL.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA31<M extends BaseA31<M>> extends Model<M> implements IBean {

	/**
	 * 人员统一标识符
	 */
	public void setA0000(java.lang.String A0000) {
		set("A0000", A0000);
	}
	
	/**
	 * 人员统一标识符
	 */
	public java.lang.String getA0000() {
		return getStr("A0000");
	}

	/**
	 * 离退类别 ZB132
	 */
	public void setA3101(java.lang.String A3101) {
		set("A3101", A3101);
	}
	
	/**
	 * 离退类别 ZB132
	 */
	public java.lang.String getA3101() {
		return getStr("A3101");
	}

	/**
	 * 离退批准时间
	 */
	public void setA3104(java.lang.String A3104) {
		set("A3104", A3104);
	}
	
	/**
	 * 离退批准时间
	 */
	public java.lang.String getA3104() {
		return getStr("A3104");
	}

	/**
	 * 离退前职务层次 ZB09
	 */
	public void setA3107(java.lang.String A3107) {
		set("A3107", A3107);
	}
	
	/**
	 * 离退前职务层次 ZB09
	 */
	public java.lang.String getA3107() {
		return getStr("A3107");
	}

	/**
	 * 离退后管理单位
	 */
	public void setA3117A(java.lang.String A3117A) {
		set("A3117A", A3117A);
	}
	
	/**
	 * 离退后管理单位
	 */
	public java.lang.String getA3117A() {
		return getStr("A3117A");
	}

	/**
	 * 曾任最高职务
	 */
	public void setA3118(java.lang.String A3118) {
		set("A3118", A3118);
	}
	
	/**
	 * 曾任最高职务
	 */
	public java.lang.String getA3118() {
		return getStr("A3118");
	}

	/**
	 * 离退批准文号
	 */
	public void setA3137(java.lang.String A3137) {
		set("A3137", A3137);
	}
	
	/**
	 * 离退批准文号
	 */
	public java.lang.String getA3137() {
		return getStr("A3137");
	}

	/**
	 * 离退批准单位
	 */
	public void setA3138(java.lang.String A3138) {
		set("A3138", A3138);
	}
	
	/**
	 * 离退批准单位
	 */
	public java.lang.String getA3138() {
		return getStr("A3138");
	}

	/**
	 * 标识
	 */
	public void setUPDATED(java.lang.String UPDATED) {
		set("UPDATED", UPDATED);
	}
	
	/**
	 * 标识
	 */
	public java.lang.String getUPDATED() {
		return getStr("UPDATED");
	}

	/**
	 * 离退前级别 ZB134
	 */
	public void setA3110(java.lang.String A3110) {
		set("A3110", A3110);
	}
	
	/**
	 * 离退前级别 ZB134
	 */
	public java.lang.String getA3110() {
		return getStr("A3110");
	}

	/**
	 * 离退前职务等级
	 */
	public void setA3109(java.lang.String A3109) {
		set("A3109", A3109);
	}
	
	/**
	 * 离退前职务等级
	 */
	public java.lang.String getA3109() {
		return getStr("A3109");
	}

	/**
	 * 离退前职级
	 */
	public void setA3108(java.lang.String A3108) {
		set("A3108", A3108);
	}
	
	/**
	 * 离退前职级
	 */
	public java.lang.String getA3108() {
		return getStr("A3108");
	}

}
