package com.wdy.generator.postgreSQL.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("SysLoginLog", "id", SysLoginLog.class);
		arp.addMapping("SysOperateLog", "id", SysOperateLog.class);
		arp.addMapping("SysPermission", "id", SysPermission.class);
		arp.addMapping("SysRole", "id", SysRole.class);
		arp.addMapping("SysUser", "id", SysUser.class);
		arp.addMapping("SysUserRolePermission", "id", SysUserRolePermission.class);
	}
}

