package com.wdy.generator.postgreSQL.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("QxVerifyMsg", "id", QxVerifyMsg.class);
		arp.addMapping("QxVerifyRule", "id", QxVerifyRule.class);
		arp.addMapping("SysPermission", "id", Permission.class);
		arp.addMapping("SysUserB01Permission", "id", UserB01Permission.class);
		arp.addMapping("SysUserRolePermission", "id", UserRolePermission.class);
		arp.addMapping("TempJob", "id", TempJob.class);
		arp.addMapping("UploadInfo", "id", UploadInfo.class);
		arp.addMapping("WzAnnualDuty", "id", WzAnnualDuty.class);
		arp.addMapping("WzHonorAward", "id", WzHonorAward.class);
		arp.addMapping("a01", "A0000", A01.class);
		// Composite Primary Key order: impId,A0000
		arp.addMapping("a01_temp", "impId,A0000", A01Temp.class);
		arp.addMapping("a02", "A0200", A02.class);
		arp.addMapping("a02_temp", "A0200", A02Temp.class);
		arp.addMapping("a05", "A0500", A05.class);
		arp.addMapping("a05_temp", "A0500", A05Temp.class);
		arp.addMapping("a06", "A0600", A06.class);
		arp.addMapping("a06_temp", "A0600", A06Temp.class);
		arp.addMapping("a08", "A0800", A08.class);
		arp.addMapping("a08_temp", "A0800", A08Temp.class);
		arp.addMapping("a14_temp", "A1400", A14Temp.class);
		arp.addMapping("a15", "A1500", A15.class);
		arp.addMapping("a15_temp", "A1500", A15Temp.class);
		arp.addMapping("a30", "A3000", A30.class);
		arp.addMapping("a30_temp", "A3000", A30Temp.class);
		arp.addMapping("a33", "A3300", A33.class);
		arp.addMapping("a36_temp", "A3600", A36Temp.class);
		// Composite Primary Key order: A0000,impId
		arp.addMapping("a57_temp", "A0000,impId", A57Temp.class);
		arp.addMapping("a99z1_temp", "A99Z100", A99z1Temp.class);
		arp.addMapping("b01", "id", B01.class);
		arp.addMapping("code_value", "CODE_VALUE_SEQ", CodeValue.class);
		arp.addMapping("impFile", "fileId", ImpFile.class);
		arp.addMapping("selectCadre", "id", SelectCadre.class);
		arp.addMapping("selectUniversity", "id", SelectUniversity.class);
		arp.addMapping("verify_rule", "VRU009", VerifyRule.class);
		arp.addMapping("youngCadre", "id", YoungCadre.class);
		arp.addMapping("youngFouMust", "id", YoungFouMust.class);
		arp.addMapping("youngReport", "id", YoungReport.class);
		arp.addMapping("youngStudy", "id", YoungStudy.class);
	}
}

