package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A01 extends BaseA01<A01> {
	
}
