package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA01Temp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A01Temp extends BaseA01Temp<A01Temp> {
	
}
