package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA02;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A02 extends BaseA02<A02> {
	
}
