package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA02Temp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A02Temp extends BaseA02Temp<A02Temp> {
	
}
