package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA05;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A05 extends BaseA05<A05> {
	
}
