package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA05Temp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A05Temp extends BaseA05Temp<A05Temp> {
	
}
