package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA06;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A06 extends BaseA06<A06> {
	
}
