package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA06Temp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A06Temp extends BaseA06Temp<A06Temp> {
	
}
