package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA08;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A08 extends BaseA08<A08> {
	
}
