package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA08Temp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A08Temp extends BaseA08Temp<A08Temp> {
	
}
