package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA11;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A11 extends BaseA11<A11> {
	
}
