package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA14;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A14 extends BaseA14<A14> {
	
}
