package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA14Temp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A14Temp extends BaseA14Temp<A14Temp> {
	
}
