package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA15;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A15 extends BaseA15<A15> {
	
}
