package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA15Temp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A15Temp extends BaseA15Temp<A15Temp> {
	
}
