package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA30;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A30 extends BaseA30<A30> {
	
}
