package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA30Temp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A30Temp extends BaseA30Temp<A30Temp> {
	
}
