package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA31;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A31 extends BaseA31<A31> {
	
}
