package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA32;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A32 extends BaseA32<A32> {
	
}
