package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA33;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A33 extends BaseA33<A33> {
	
}
