package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA36;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A36 extends BaseA36<A36> {
	
}
