package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA36Temp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A36Temp extends BaseA36Temp<A36Temp> {
	
}
