package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA37;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A37 extends BaseA37<A37> {
	
}
