package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA41;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A41 extends BaseA41<A41> {
	
}
