package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA53;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A53 extends BaseA53<A53> {
	
}
