package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA57;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A57 extends BaseA57<A57> {
	
}
