package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA57Temp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A57Temp extends BaseA57Temp<A57Temp> {
	
}
