package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA60;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A60 extends BaseA60<A60> {
	
}
