package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA61;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A61 extends BaseA61<A61> {
	
}
