package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA62;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A62 extends BaseA62<A62> {
	
}
