package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA63;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A63 extends BaseA63<A63> {
	
}
