package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA64;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A64 extends BaseA64<A64> {
	
}
