package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA71;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A71 extends BaseA71<A71> {
	
}
