package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA99z1Temp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A99z1Temp extends BaseA99z1Temp<A99z1Temp> {
	
}
