package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseA99z1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class A99z1 extends BaseA99z1<A99z1> {
	
}
