package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseB01;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class B01 extends BaseB01<B01> {
	
}
