package com.wdy.generator.postgreSQL.model;


import com.wdy.generator.postgreSQL.model.base.BaseB01Temp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class B01Temp extends BaseB01Temp<B01Temp> {

}
