package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseCodeValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CodeValue extends BaseCodeValue<CodeValue> {
	
}
