package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseCodeTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CodeTable extends BaseCodeTable<CodeTable> {
	
}
