package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseDrop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Drop extends BaseDrop<Drop> {
	
}
