package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseImpFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImpFile extends BaseImpFile<ImpFile> {
	
}
