package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseJobInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JobInfo extends BaseJobInfo<JobInfo> {
	
}
