package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoginLog extends BaseLoginLog<LoginLog> {
	
}
