package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseMemUnitInstitution;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemUnitInstitution extends BaseMemUnitInstitution<MemUnitInstitution> {

}
