package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseOperateLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OperateLog extends BaseOperateLog<OperateLog> {
	
}
