package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BasePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {
	
}
