package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseQxVerifyMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QxVerifyMsg extends BaseQxVerifyMsg<QxVerifyMsg> {
	
}
