package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseQxVerifyRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QxVerifyRule extends BaseQxVerifyRule<QxVerifyRule> {
	
}
