package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseSelectCadre;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SelectCadre extends BaseSelectCadre<SelectCadre> {
	
}
