package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseSelectUniversity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SelectUniversity extends BaseSelectUniversity<SelectUniversity> {
	
}
