package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseSysLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysLoginLog extends BaseSysLoginLog<SysLoginLog> {
	
}
