package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseSysOperateLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOperateLog extends BaseSysOperateLog<SysOperateLog> {
	
}
