package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseSysPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysPermission extends BaseSysPermission<SysPermission> {
	
}
