package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseSysUserRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserRolePermission extends BaseSysUserRolePermission<SysUserRolePermission> {
	
}
