package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseTempJob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TempJob extends BaseTempJob<TempJob> {
	
}
