package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseUnitInstitution;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UnitInstitution extends BaseUnitInstitution<UnitInstitution> {

}
