package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseUploadInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UploadInfo extends BaseUploadInfo<UploadInfo> {
	
}
