package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseUserRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRolePermission extends BaseUserRolePermission<UserRolePermission> {
	
}
