package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseUserB01Permission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserB01Permission extends BaseUserB01Permission<UserB01Permission> {
	
}
