package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseVerifyRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VerifyRule extends BaseVerifyRule<VerifyRule> {
	
}
