package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseWzAnnualDuty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WzAnnualDuty extends BaseWzAnnualDuty<WzAnnualDuty> {
	
}
