package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseWzHonorAward;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WzHonorAward extends BaseWzHonorAward<WzHonorAward> {
	
}
