package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseYoungFouMust;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YoungFouMust extends BaseYoungFouMust<YoungFouMust> {
	
}
