package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseYoungCadre;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YoungCadre extends BaseYoungCadre<YoungCadre> {
	
}
