package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseYoungReport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YoungReport extends BaseYoungReport<YoungReport> {
	
}
