package com.wdy.generator.postgreSQL.model;

import com.wdy.generator.postgreSQL.model.base.BaseYoungStudy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YoungStudy extends BaseYoungStudy<YoungStudy> {
	
}
