package com.wdy.generator.mysql.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setKey(java.lang.String key) {
		set("key", key);
	}
	
	public java.lang.String getKey() {
		return getStr("key");
	}

	/**
	 * 登录名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 登录名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 用户姓名
	 */
	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	/**
	 * 用户姓名
	 */
	public java.lang.String getAccount() {
		return getStr("account");
	}

	/**
	 * 密码(MD5加密)
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码(MD5加密)
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setSalt2(java.lang.String salt2) {
		set("salt2", salt2);
	}
	
	public java.lang.String getSalt2() {
		return getStr("salt2");
	}

	public void setOrgKey(java.lang.String orgKey) {
		set("org_key", orgKey);
	}
	
	public java.lang.String getOrgKey() {
		return getStr("org_key");
	}

	public void setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
	}
	
	public java.lang.String getOrgName() {
		return getStr("org_name");
	}

	public void setPicture(java.lang.String picture) {
		set("picture", picture);
	}
	
	public java.lang.String getPicture() {
		return getStr("picture");
	}

	/**
	 * 照片对象
	 */
	public void setPictureObj(java.lang.String pictureObj) {
		set("picture_obj", pictureObj);
	}
	
	/**
	 * 照片对象
	 */
	public java.lang.String getPictureObj() {
		return getStr("picture_obj");
	}

	public void setOpenId(java.lang.String openId) {
		set("open_id", openId);
	}
	
	public java.lang.String getOpenId() {
		return getStr("open_id");
	}

	public void setUnionId(java.lang.String unionId) {
		set("union_id", unionId);
	}
	
	public java.lang.String getUnionId() {
		return getStr("union_id");
	}

	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}
	
	public java.lang.Integer getGender() {
		return getInt("gender");
	}

	/**
	 * 邮件地址
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 邮件地址
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}

	/**
	 * 联系电话
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 联系电话
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 状态 {1:正常,2:锁定,3:禁用}
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态 {1:正常,2:锁定,3:禁用}
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setOnlineStatus(java.lang.Integer onlineStatus) {
		set("online_status", onlineStatus);
	}
	
	public java.lang.Integer getOnlineStatus() {
		return getInt("online_status");
	}

	/**
	 * 登录失败次数
	 */
	public void setLoginFailTimes(java.lang.Integer loginFailTimes) {
		set("login_fail_times", loginFailTimes);
	}
	
	/**
	 * 登录失败次数
	 */
	public java.lang.Integer getLoginFailTimes() {
		return getInt("login_fail_times");
	}

	/**
	 * 登录时间
	 */
	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}
	
	/**
	 * 登录时间
	 */
	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	/**
	 * 解锁时间(密码错误五次锁定账户24小时)
	 */
	public void setUnlockTime(java.util.Date unlockTime) {
		set("unlock_time", unlockTime);
	}
	
	/**
	 * 解锁时间(密码错误五次锁定账户24小时)
	 */
	public java.util.Date getUnlockTime() {
		return get("unlock_time");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdator(java.lang.String updator) {
		set("updator", updator);
	}
	
	public java.lang.String getUpdator() {
		return getStr("updator");
	}

	public void setVersion(java.util.Date version) {
		set("version", version);
	}
	
	public java.util.Date getVersion() {
		return get("version");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setDeleted(java.lang.Boolean deleted) {
		set("deleted", deleted);
	}
	
	public java.lang.Boolean getDeleted() {
		return get("deleted");
	}

	public void setManagerLevel(java.lang.String managerLevel) {
		set("manager_level", managerLevel);
	}
	
	public java.lang.String getManagerLevel() {
		return getStr("manager_level");
	}

	public void setManagerLevelName(java.lang.String managerLevelName) {
		set("manager_level_name", managerLevelName);
	}
	
	public java.lang.String getManagerLevelName() {
		return getStr("manager_level_name");
	}

}
